/*______________
|       ______  |   B U I L T     O N     U I Z E     F R A M E W O R K
|     /      /  |   ---------------------------------------------------
|    /    O /   |   This JavaScript application is developed using the object
|   /    / /    |   oriented UIZE JavaScript framework as its foundation.
|  /    / /  /| |
| /____/ /__/_| |    ONLINE : http://www.uize.com
|          /___ |   LICENSE : Available under MIT License or GNU General Public License
|_______________|             http://www.uize.com/license.html
*/

/*______________
|       ______  |   U I Z E    J A V A S C R I P T    F R A M E W O R K
|     /      /  |   ---------------------------------------------------
|    /    O /   |    MODULE : UizeDotCom.WidgetToGoPage.Calendar.library Library Module
|   /    / /    |
|  /    / /  /| |    ONLINE : http://www.uize.com
| /____/ /__/_| | COPYRIGHT : (c)2009-2011 UIZE
|          /___ |   LICENSE : Available under MIT License or GNU General Public License
|_______________|             http://www.uize.com/license.html
*/

/*?
	Introduction
		The =UizeDotCom.WidgetToGoPage.Calendar.library= module is a library module that bundles together all the JavaScript modules needed by the calendar Widgets To Go widget.

		*DEVELOPERS:* `Chris van Rensburg`
*/



Uize.module({name:'UizeDotCom'});


Uize.module({name:'Uize.Node',builder:function(){var _a=function(){},_b,_c='string',_d='object',_e='function',_f=true,_g=false,_h=null,_i=typeof navigator!='undefined',_j=_i?navigator:{userAgent:'',appName:''},_k=_j.userAgent.toLowerCase(),_l=_j.appName=='Microsoft Internet Explorer',_m=_k.indexOf('applewebkit')> -1,_n=_k.indexOf('gecko')> -1,_o=_k.indexOf('opera')> -1,_p=_n||_o,_q='hidden',_r=Uize.copyInto;var _s=_a._s=function(_t){_u.clientX=_t.clientX;_u.clientY=_t.clientY;_u.pageX=_t.pageX;_u.pageY=_t.pageY;};function _v(_w){var _x=document.getElementById(_w);return(!_l||(_x&&_x.id==_w))?_x:_h;}function _y(){return document[_m?'body':'documentElement'];}function _z(_A){var _B=(_A=_A+'').slice(_A.indexOf('(')+1,_A.indexOf(')'));return Function.apply({},(_B?_B.split(','):[]).concat(_A.slice(_A.indexOf('{')+1,_A.lastIndexOf('}'))));}function _C(_D){if(_D.charCodeAt(0)==111&&_D.charCodeAt(1)==110)_D=_D.slice(2);return(_D.charCodeAt(_D.length-1)==41&&_a.VirtualEvent?_a.VirtualEvent.resolve(_D):_D);}
function _E(_F,_G){for(var _H= -1,_x={},_I=Math.min(_F.length,_G.length);++_H<_I;)_x[_F[_H]]=_G[_H];return _x;}var _J=_a._J={},_K={},_L=0,_M={string:1,number:1,boolean:1},_u={clientX:0,clientY:0,pageX:0,pageY:0};var _N='table-',_O=_N+'row',_P=_N+'cell',_Q=_r({SPAN:'inline',THEAD:_N+'header-group',TFOOT:_N+'footer-group',LI:'list-item'},_l&&typeof DOMImplementation=='undefined'?_h:{TABLE:'table',TR:_O,TH:_P,TD:_P,TBODY:_O+'-group',COLGROUP:_N+'column-group',COL:_N+'column',CAPTION:_N+'caption'});_a.display=function(_R,_S){_S=_S===_b|| !!_S;_T(_R,function(_U){_U.style.display=_S?(_Q[_U.tagName]||'block'):'none';});};var _T=_a.doForAll=function(_R,_A,_V,_W){if(typeof _R==_c)_R=_X(_R,_V,_W);if(_R!=_b){if(_Y(_R)){_A(_R);}else{var _Z=typeof _R;if((_Z==_d||_Z==_e)&&typeof _R.length=='number'){for(var _0= -1,_1=_R.length;++_0<_1;)_T(_R[_0],_A,_V,_W);}else if(_Z==_d){for(var _2 in _R)_T(_R[_2],_A,_V,_W);}}}};var _3=_a.doRectanglesOverlap=function(_4,_5,_6,_7,_8,_9,_ba,_bb){return(_6-1+ +_4>=_8&&_ba-1+ +_8>=_4&&
_7-1+ +_5>=_9&&_bb-1+ +_9>=_5);};var _X=_a.getById=function(_U,_V,_W){if(typeof _U!=_c)return _U;var _x=_W?_W[_U]:_b;if(_x===_b){var _bc=_bd(_V,_U);(_x=_v(_bc))||(((_x=document.getElementsByName(_bc)).length<2)&&(_x=_x[0]||_h));if(_W)_W[_U]=_x;}return _x;};_a.find=function(_be){if(typeof _be!=_d|| !_be||typeof _be.length=='number'||_Y(_be))return _be;var _bf=document,_bg=[],_bh=_r({},_be),_bi='root'in _bh?_X(_bh.root):_bf;delete _bh.root;if(_bi){var _bj=_bh.tagName;if('id'in _bh&&_M[typeof _bh.id]){var _U=_v(_bh.id);_U&&_bg.push(_U);delete _bh.id;}else if('name'in _bh&&_M[typeof _bh.name]){_bg=_bf.getElementsByName(_bh.name);delete _bh.name;}else{var _bk=_M[typeof _bj];_bk&&delete _bh.tagName;_bg=_bi.getElementsByTagName(_bj&&_bk?_bj:'*');_bi=_h;}if(_bi==_bf)_bi=_h;if(!_bj||_bj=='*')delete _bh.tagName;}var _bl=_bg.length;for(var _bm in _bh)break;if(!_bl||(_bm==_b&& !_bi))return _bg;var _bn=[],_bo;for(var _bp= -1;++_bp<_bl;){var _U=_bg[_bp];if(_bo=_bi?_bq(_U,_bi):_f){for(var _br in _bh){var _bs=_U[_br],
_bt=_bh[_br],_bu=Uize.isFunction;if(!(_M[typeof _bt]?_bs==_bt:(_bt instanceof RegExp?_bt.test(_bs||''):(_bu(_bt)?_bt.call(_U,_bs):_f)))){_bo=_g;break;}}}_bo&&_bn.push(_U);}return _bn;};var _bv=_a.getCoords=function(_U){var _bw=0,_bx=0,_by=0,_bz=0,_bA=_f,_bB=_y(),_bC=_bD(window);function _bE(){_bw+=_bB.scrollLeft;_bx+=_bB.scrollTop;}if(_U==window){_bE();_by=_bC.width;_bz=_bC.height;}else if(_Y(_U=_X(_U))){_by=_U.offsetWidth;_bz=_U.offsetHeight;if(!(_by&&_bz)&&_U.tagName=='DIV'){for(var _bF=_U.childNodes,_bG=_bF.length;--_bG>=0;){if(_bF[_bG].nodeName.charAt(0)!='#'){var _bH=_bv(_bF[_bG]);if(_bH.width||_bH.height){_by=Math.max(_by,_bH.right-_bw+1);_bz=Math.max(_bz,_bH.bottom-_bx+1);}}}}function _bI(_U){return _bJ(_U,'display')=='none'||_bJ(_U,'visibility')==_q;}if(_U.tagName=='A'&&_U.childNodes.length==1&&_U.childNodes[0].tagName=='IMG')_U=_U.childNodes[0];var _bK=_bA= !_bI(_U),_bL=_U,_bM=_U;while(_bM.parentNode&&typeof _bM.parentNode!='unknown'){var _bN=_bM.offsetLeft||0,_bO=_bM.offsetTop||0,
_bP=_bM.offsetWidth,_bQ=_bM.offsetHeight;if(_bA&&_bI(_bM))_bA=_g;if(_bM==_bL){_bw+=_bN+(parseInt(_bJ(_bM,'borderLeftWidth'))||0);_bx+=_bO+(parseInt(_bJ(_bM,'borderTopWidth'))||0);_bL=_bM.offsetParent;_bJ(_bM,'position')=='fixed'&&_bE();}if(_bM!=_U&&_bM!=document.body&&_bM!=document.documentElement&&(_bM.scrollWidth>_bP||_bM.scrollHeight>_bQ)){_bw-=_bM.scrollLeft;_bx-=_bM.scrollTop;if(_l){_bw+=_bM.clientLeft;_bx+=_bM.clientTop;}if(_bA)_bA=_3(_bw,_bx,_by,_bz,_bN,_bO,_bP,_bQ);}_bM=_bM.parentNode;}if(_bA)_bA=_3(_bw,_bx,_by,_bz,_bB.scrollLeft,_bB.scrollTop,_bC.width,_bC.height);}return{x:_bw,y:_bx,width:_by,height:_bz,area:_by*_bz,left:_bw,top:_bx,right:_bw+_by-1,bottom:_bx+_bz-1,seen:_bA};};var _bD=_a.getDimensions=function(_U){if(_U==window){var _bB=document.documentElement;return{width:_bB.clientWidth||window.innerWidth||_bB.offsetWidth,height:_bB.clientHeight||window.innerHeight||_bB.offsetHeight};}else if(_U=_X(_U)){return{width:_U.offsetWidth||parseInt(_bJ(_U,'width'))||0,
height:_U.offsetHeight||parseInt(_bJ(_U,'height'))||0};}else{return{width:0,height:0};}};var _bR={borderColor:['border','Color'],borderWidth:['border','Width'],padding:1,margin:1},_bJ=_a.getStyle=function(_U,_bS){var _bT='';if(typeof _bS==_c){if(_U){var _bU=_l&&_bS=='opacity',_bV=document.defaultView,_bW=_bV&&_bV.getComputedStyle(_U,'');if(_bU)_bS='filter';if(_bW){if(!(_bT=_bW[_bS])){var _bX=_bR[_bS];if(_bX){var _bY=_bX[0]||_bS,_bZ=_bX[1]||'',_b0=_bW[_bY+'Top'+_bZ],_b1=_bW[_bY+'Right'+_bZ],_b2=_bW[_bY+'Bottom'+_bZ],_b3=_bW[_bY+'Left'+_bZ];_bT=_b0==_b1&&_b1==_b2&&_b2==_b3?_b3:_b0+' '+_b1+' '+_b2+' '+_b3;}}}else{var _b4=_U.currentStyle;_bT=_b4?_b4.getAttribute(_bS):_U.style[_bS];}if(_bU){var _b5=_bT.match(/alpha\s*\(\s*opacity\s*=([^\)]*)\)/i);_bT=_b5?_b5[1]/100:1;}}}else{_bT={};if(_U)for(_bS in _bS)_bT[_bS]=_bJ(_U,_bS);}return _bT;};var _b6=_a.getText=function(_U){var _b7='';if(_U=_X(_U)){function _b8(_U){if(typeof _U.innerText==_c){_b7+=_U.innerText.replace(/\r|\n|\r\n/g,'');
}else if(typeof _U.textContent==_c){_b7+=_U.textContent;}else{if(_U.nodeType==3)_b7+=_U.data;if(_U.childNodes){for(var _bG= -1,_bF=_U.childNodes,_b9=_bF.length;++_bG<_b9;)_b6(_bF[_bG]);}}}_b8(_U);}return _b7;};_a.getValue=function(_U){var _bT;if(_U=_X(_U)){if(_Y(_U)){var _ca=_U.tagName;if(_ca=='TEXTAREA'){_bT=_U.value;}else if(_ca=='INPUT'){_bT=_U.type=='checkbox'?_U.checked:_U.value;}else if(_ca=='SELECT'){if(_U.multiple){_bT=[];for(var _cb= -1,_cc=_U.options,_cd=_cc.length,_ce;++_cb<_cd;)(_ce=_cc[_cb]).selected&&_bT.push(_ce.value);}else{_bT=_U.value;}}else if(_ca=='IMG'){_bT=_U.src;}else{_bT=_U.innerHTML.replace(/<br\/?>/gi,'\n').replace(/&nbsp;/g,' ');}}else{_bT=(Uize.findRecord(_U,{tagName:'INPUT',type:'radio',checked:_f})||{}).value;}}return _bT;};_a.injectHtml=function(_R,_cf,_cg){var _ch,_ci,_cj,_ck,_cl,_cm;((_ch=_cg=='inner replace')||(_ci=_cg=='outer replace')||(_cj=_cg=='inner top')||(_ck=_cg=='outer top')||(_cl=_cg=='outer bottom')||(_cm=_f));_cf+='';_T(_R,function(_U){var _cn=_U.childNodes;
function _co(_cp){return _cp&&/<script/i.test(_cp);}function _cq(){return _co(_cf);}if((_ch||(!_cn.length&&(_cj||_cm)))&& !_cq()){_U.innerHTML=_cf;}else if(_ci&&_l&& !_cq()){_U.outerHTML=_cf;}else{if(_ch)_U.innerHTML='';var _cr=document.createElement('DIV');_cr.innerHTML=_cf;var _cs=_cj?_cn[0]:_cl?_U.nextSibling:_U,_ct=_cr.childNodes,_cu=_U.parentNode;function _cv(_U){if(_U.tagName=='SCRIPT'){var _cw=document.createElement('script');if(_U.id)_cw.id=_U.id;if(_U.type)_cw.type=_U.type;_cw.text=_U.text;if(_U.src)_cw.src=_U.src;_U.parentNode.replaceChild(_cw,_U);}else if(_co(_U.innerHTML)){for(var _bG= -1,_cn=_U.childNodes,_cx=_cn.length;++_bG<_cx;)_cv(_cn[_bG]);}}while(_ct.length){var _cy=_ct[0];if(_cm||_ch){_U.appendChild(_cy);}else if(_cj){_cs?_U.insertBefore(_cy,_cs):_U.appendChild(_cy);}else if(_ck||_ci){_cu.insertBefore(_cy,_cs);}else if(_cl){_cs?_cu.insertBefore(_cy,_cs):_cu.appendChild(_cy);}_cv(_cy);}_ci&&_cu.removeChild(_U);}});};var _Y=_a.isNode=function(_U){return!!(_U&&typeof _U==_d&&
(_U.getAttribute||_U.documentElement||(_U.self&&_U.self==_U)));};var _bq=_a.isOnNodeTree=function(_U,_cz){_U=_X(_U);_cz=_X(_cz);while(_U){if(_U==_cz)return _f;_U=_U.parentNode;}return _g;};var _bd=_a.joinIdPrefixAndNodeId=function(_V,_w){return(_V||'')+(_V&&_w?'-':'')+_w;};_a.remove=function(_R){_T(_R,function(_U){_U.parentNode.removeChild(_U)});};_a.setClipRect=function(_R,_b0,_b1,_b2,_b3){var _cA='rect('+_b0+'px, '+_b1+'px, '+_b2+'px, '+_b3+'px)';_T(_R,function(_U){_U.style.clip=_cA});};var _cB=['left','top','width','height'];_a.setCoords=function(_R,_cC){_cD(_R,typeof _cC.length=='number'?_E(_cB,_cC):_cC);};_a.centerInWindow=function(_R){var _cE=_bv(window);_T(_R,function(_U){var _cF=_bD(_U);_a.setCoords(_U,{left:_cE.x+((_cE.width-_cF.width)>>1),top:_cE.y+((_cE.height-_cF.height)>>1)});});};_a.getEventAbsPos=function(_cG){var _cH=(_cG||(_cG=_u)).targetTouches;if(_cH&&_cH.length)_cG=_cH[0];if(_cG.pageX!=_b){return{left:_cG.pageX,top:_cG.pageY};}else{var _bB=_y();return{left:_cG.clientX+_bB.scrollLeft,
top:_cG.clientY+_bB.scrollTop};}};var _cI=_a.setAbsPos=function(_R,_cJ,_cK){_cK=typeof _cK=='number'?{x:_cK,y:_cK}:(_cK||{x:0,y:0});var _bB=document[_m?'body':'documentElement'],_cL=_bD(window);_T(_R,function(_U){function _cM(_cN,_cO,_cP,_cQ){var _cR=_cJ[_cN],_cS=_cK[_cQ],_cT=_cR-_bB[_cO],_cU=_cS+_cF[_cP];return(_cR+(_cT+_cU>_cL[_cP]?Math.max(-_cU,-_cT):_cS));}var _cF=_bD(_U);_cD(_U,{left:_cM('left','scrollLeft','width','x'),top:_cM('top','scrollTop','height','y'),right:'auto',bottom:'auto'});});};_a.setAbsPosAdjacentTo=function(_R,_cV,_cW){_cV=_X(_cV);var _cX=_bv(_cV),_cY=_cX.width/2,_cZ=_cX.height/2,_c0=_cW=='x'? -1:1;if(!_cY&& !_cZ)_cX=_a.getEventAbsPos();_T(_R,function(_U){_cI(_U,{left:_cX.left+_cY,top:_cX.top+_cZ},{x:-_cY*_c0,y:_cZ*_c0});});};_a.setInnerHtml=function(_R,_cp){_cp+='';_T(_R,function(_U){_U.innerHTML=_cp});};var _c1={};_a.setOpacity=function(_R,_c2){_c1.opacity=_c2;_cD(_R,_c1);};_a.setProperties=function(_R,_be){_T(_R,function(_U){_r(_U,_be)});};var _cD=_a.setStyle=function(_R,_be){_T(_R,
function(_U){var _c3=_U.style,_c4;if(_l&&'opacity'in _be)_c3.filter=(_c4=Math.round(_be.opacity*100))<100?'alpha(opacity='+_c4+')':'';for(var _bS in _be)_c3[_bS]=(typeof(_c4=_be[_bS])==_d&&_c4?(_c4=_c4.valueOf()):_c4)!=_b?(typeof _c4=='number'&&_bS!='opacity'&&_bS!='zIndex'?Math.round(_c4)+'px':_c4+''):'';});};_a.setValue=function(_R,_bT){_bT+='';_T(_R,function(_U){var _ca=_U.tagName,_c5=_U.readOnly;if(_c5)_U.readOnly=_g;if(_ca=='TEXTAREA'){_U.value=_bT;}else if(_ca=='INPUT'){var _c6=_U.type;if(_c6=='text'||_c6==_q||_c6=='password'){_U.value=_bT;}else if(_c6=='checkbox'){_U.checked=_bT=='true';}else if(_c6=='radio'){_U.checked=_U.value==_bT;}}else if(_ca=='SELECT'){if(!_bT){_U.selectedIndex= -1;}else{var _cc=_U.options;if(_U.multiple&&(_bT=='*'||_bT.indexOf(',')> -1)){var _c7;if(_bT!='*'){_c7={};for(var _G=_bT.split(','),_H=_G.length;--_H>=0;)_c7[_G[_H]]=1;}for(var _cb=_cc.length,_ce;--_cb>=0;)(_ce=_cc[_cb]).selected= !_c7||_c7[_ce.value];}else{
_U.selectedIndex=Uize.findRecordNo(_cc,{value:_bT},_U.selectedIndex);}}}else if(_ca=='IMG'){if(_bT)_U.src=_bT;}else{_ca=='PRE'&&_l?(_U.innerText=_bT):(_U.innerHTML=_bT.replace(/</g,'&lt;').replace(/\n/g,'<br/>'));}if(_c5)_U.readOnly=_c5;});};_a.show=function(_R,_c8){_cD(_R,{visibility:_c8||_c8===_b?'inherit':_q});};_a.showClickable=function(_R,_c9){_cD(_R,{cursor:_c9||_c9===_b?(_l?'hand':'pointer'):'default'});};var _da=_a.unwire=function(_R,_db,_dc,_dd){if(typeof _db==_d&&_db&& !_db.virtualDomEvent){for(var _D in _db)_da(_R,_D,_db[_D],_dc);}else{_a.unwireEventsByOwnerId(_dd,_R!==_b||_db!=_b||_dc!=_b?{node:_R,eventName:_db,handler:_dc}:_b);}};_a.unwireEventsByOwnerId=function(_de,_df){var _dg=_K[_de=_de||''];if(_dg){function _dh(_di){if(_di!==_h){var _dj=_df&&_df.eventName,_dk=_df&&_df.handler,_dl=_di||_dj||_dk;if(_dj&&_dj.charCodeAt)_dj=_C(_dj);for(var _dm=_dg.length;--_dm>=0;){var _dn=_dg[_dm],_do=_J[_dn],_U=_do._U,_D=_do._D;if(!_dl||((!_di||_di==(_do._dp||_U))&&(!_dj||_dj==_D)&&(!_dk||_dk==_do._dq))){
_dl&&_dg.splice(_dm,1);if(_do._dr){_a.unwireEventsByOwnerId(_do._dr)}else{try{_U==window?_ds.unwire(_D,_do._dt):_l?_U.detachEvent('on'+_D,_do._dt):_U.removeEventListener(_D,_do._dt,_g);}catch(_du){}}delete _J[_dn];}}(_dl&&_dg.length)||delete _K[_de];}}_df&&_df.node!==_b?_T(_df.node,_dh):_dh();}};var _dv=_z(function(_dn){return(function(_t){var _do=window.Uize&&Uize.Node._J[_dn];return _do&&_do._dq.call(_do._U,_t.windowEvent);});}),_dw=_z(function(_dn){return(function(_t){var _do=window.Uize&&Uize.Node._J[_dn];return _do&&_do._dq.call(_do._U,_t||window.event);});}),_dx={click:_dw,mouseover:_z(function(_dn){return(function(_t){var _do=window.Uize&&Uize.Node._J[_dn],_dy=(_t||(_t=window.event)).fromElement||_t.relatedTarget;if(_do){if(_dy){try{if(!_dy.Uize_Widget_Drag_shield&& !Uize.Node.isOnNodeTree(_dy,_do._U))_dy=null;}catch(_du){_dy=null;}}if(!_dy){Uize.Node._s(_t);return _do._dq.call(_do._U,_t);}}});}),mouseout:_z(function(_dn){return(function(_t){var _do=window.Uize&&Uize.Node._J[_dn],
_dz=(_t||(_t=window.event)).toElement||_t.relatedTarget;if(_do){if(_dz){try{if(!_dz.Uize_Widget_Drag_shield&& !Uize.Node.isOnNodeTree(_dz,_do._U))_dz=null;}catch(_du){_dz=null;}}if(!_dz)return _do._dq.call(_do._U,_t);}});}),mousedown:_dw,mouseup:_dw};_a.wire=function(_R,_D,_dq,_de){if(!_D)return;if(_de==_b)_de='';var _dA;if(_D.charCodeAt)_D=_C(_D);if(typeof _D==_d&& !(_dA= !!_D.virtualDomEvent)){_de=arguments[2]||'';for(var _t in _D)_a.wire(_R,_t,_D[_t],_de);return;}_T(_R,function(_U){var _ca=_U.tagName;(_K[_de]||(_K[_de]=[])).push(_L);var _dt=(_dA?_a.returnFalse:_U==window?_dv:_dx[_D]||_dw)(_L);var _do=_J[_L++]={_U:_U,_D:_D,_dq:_dq,_dt:_dt};if(_p&&_ca=='BODY'&&_D=='scroll'){_do._dp=_U;_U=_do._U=document;}if(_dt){var _dB='on'+_D;_U==window?_ds.wire(_D,_dt):_l?_U.attachEvent(_dB,_dt):_U.addEventListener(_D,_dt,_g);if(_ca=='A'&&(_D=='mousedown'||_D=='click')&& !_U[_dB])_U[_dB]=_a.returnFalse;}else if(_dA){_D.wire(_U,_dq,_do._dr=Uize.getGuid());}});};_a.returnFalse=new Function('return false');
_a.returnTrue=new Function('return true');_a.isIe=_l;_a.isSafari=_m;_a.isMozilla=_n;if(_i){_a.wire(document.documentElement,'mousemove',_s);var _ds=new Uize,_dC=setTimeout(function(){_ds.fire('load')},15000);function _dD(_dE){var _dF='on'+_dE,_dG=window[_dF]||_a.returnFalse;window[_dF]=function(_t){_dE=='load'&&clearTimeout(_dC);_dG.call(window,_t||(_t=window.event));_ds.fire({name:_dE,windowEvent:_t});};}for(var _dE in{focus:1,blur:1,load:1,beforeunload:1,unload:1,resize:1,scroll:1})_dD(_dE);;}return _a;}});


Uize.module({name:'Uize.Widget',required:'Uize.Node',builder:function(b_a){var b_b=null,b_c=true,b_d=false,b_e='string',b_f=Uize.isFunction,b_g='concatenated',b_h,b_i=Uize.Node,b_j=b_i.doForAll,b_k=b_i.isNode,b_l=b_i.getById;var b_m=b_a.subclass(function(b_n){var b_o=this;if(b_n){var b_p=b_o.b_q(b_n.idPrefix,b_n.parent);b_p&&Uize.copyInto(b_n,b_p);delete b_n.widgetClass;}b_o.b_r={};b_o.children=b_o.b_s={};}),b_t=b_m.prototype;b_t.b_q=function(b_u,b_v){var b_n,b_w;(b_u&&(b_n=window[b_w='$'+b_u])&&typeof b_n=='object'&&(!b_v||b_u!=b_v.b_u))?(window[b_w]=b_h):(b_n=b_h);return b_n;};b_t.b_x=function(){var b_o=this,b_p=b_o.b_q(b_o.b_u,b_o.parent);b_p&&b_o.set(b_p);};b_t.b_y=function(b_z,b_A,b_B,b_C){return((!b_C||b_C==b_g)&&b_z!=b_h?(b_z+(b_B!==''?'_':'')+b_B):(b_C=='same as parent'?b_z:b_A));};var b_D={b_E:b_d,b_F:b_c};b_t.b_G=function(){(this.b_H=='inherit'?(this.parent||b_D).b_E:this.b_H)!=this.b_E&&this.set({b_E:!this.b_E});};b_t.b_I=function(){(this.b_J=='inherit'?(this.parent||b_D).b_F:this.b_J)!=this.b_F&&
this.set({b_F:!this.b_F});};b_t.b_K=function(b_L,b_M,b_N){var b_O='show'+Uize.capFirstChar(b_L);this.getProvider(b_O)?this.callInherited(b_O)(b_M):setTimeout(function(){var b_P=b_N();(b_M.callback||(b_P?b_M.yesHandler:b_M.noHandler)||function(){})(b_P)},0);};b_t.confirm=function(b_M){this.b_K('confirm',b_M,function(){return confirm(b_M.message)});};b_t.showInform=b_t.showConfirm=b_h;b_t.inform=function(b_M){this.b_K('inform',b_M,function(){alert(b_M.message);return b_c})};b_t.ajax=function(b_Q,b_R){this.callInherited('performAjax')(b_Q,Uize.isFunction(b_R)?{callback:b_R}:b_R||{})};b_t.localize=function(b_S,b_T,b_U){var b_V,b_W=this;while(!(b_V=b_W.b_X?b_W.b_X[b_S]:b_h)&&(b_W=b_W.parent));return(b_f(b_V)?b_V.call(this,b_T):Uize.substituteInto(b_V,b_T,b_U||'{KEY}'));};b_t.buildHtml=function(b_Y){var b_o=this,b_Z=b_o.b_Z;if(b_Z!=b_h){var b_0=b_o.b_1||b_o.getNode('shell')||b_o.getNode();if(b_Z===b_c){b_Z=b_o.b_Z=Uize.Template&&b_0?{process:Uize.Template.compile((
b_i.find({root:b_0,tagName:'SCRIPT',type:'text/jst'})[0]||b_0).innerHTML,{openerToken:'[%',closerToken:'%]'})}:b_h;if(!b_Z)return;}b_o.b_u||b_o.set({b_u:b_o.instanceId});var b_2=Uize.copyInto({pathToResources:Uize.pathToResources,blankGif:b_m.getBlankImageUrl()},b_Y||b_o.get());b_i.injectHtml(b_0||document.body,typeof b_Z!=b_e&&b_f(b_Z.process)?b_Z.process.call(b_o,b_2):Uize.substituteInto(b_f(b_Z)?b_o.b_Z(b_2):b_Z,b_2),b_o.b_3||(b_0?'inner replace':'inner bottom'));b_o.b_4=b_b;b_o.set({b_5:b_c});}};function b_6(b_7,b_8){b_t[b_7+'Node'+b_8]=new Function('arguments.length'+'?(arguments[0]=this.getNode(arguments[0]))'+':(arguments[arguments.length++]=this.getNode());'+'return Uize.Node.'+b_7+b_8+'.apply(0,arguments)');}b_t.getNode=function(b_9){if(b_9==b_b){if(b_9===b_b)return b_b;b_9='';}var b_o=this;if(b_o.b_ba&&typeof b_9==b_e){var b_bb=b_o.b_ba[b_9];if(b_bb!==b_h)b_9=b_bb;}if(typeof b_9==b_e){return b_l(b_9,b_o.b_u,b_o.b_4||(b_o.b_4={}));}else if(b_k(b_9)){return b_9;}else{var b_bc=b_b;b_j(b_9,
function(b_bd){(b_bc||(b_bc=[])).push(b_bd)},b_o.b_u,b_o.b_4||(b_o.b_4={}));return b_bc;}};b_6('get','Style');b_6('get','Value');b_t.flushNodeCache=function(b_be){if(this.b_4)b_be==b_h?(this.b_4=b_b):delete this.b_4[b_be];};b_t.globalizeNode=function(b_bf){var b_o=this,b_bg=document.body;b_j(b_o.getNode(b_bf),function(b_bd){if(b_bd.parentNode!=b_bg){(b_o.b_bh||(b_o.b_bh=[])).push(b_bd);b_i.setStyle(b_bd,{position:'absolute',left:-10000,top:-10000});b_bg.appendChild(b_bd);}});};b_6('display','');b_6('inject','Html');b_t.removeNode=function(b_bf){b_i.remove(this.getNode(b_bf));this.flushNodeCache(b_bf);};b_6('set','Properties');b_6('set','Opacity');b_6('set','Style');b_6('set','ClipRect');b_6('set','InnerHtml');b_6('set','Value');b_6('show','');b_t.wireNode=function(b_bf,b_bi,b_bj){arguments.length==3?b_i.wire(this.getNode(b_bf),b_bi,b_bj,this.instanceId):b_i.wire(this.getNode(b_bf),b_bi,this.instanceId);};b_t.unwireNode=function(b_bf,b_bi,b_bj){if(b_bf!==b_h)b_bf=this.getNode(b_bf);arguments.length==2&&
typeof b_bi=='object'&&b_bi&& !b_bi.virtualDomEvent?b_i.unwire(b_bf,b_bi,this.instanceId):b_i.unwire(b_bf,b_bi,b_bj,this.instanceId);};b_t.unwireNodeEventsByMatch=function(b_bf,b_bk){this.unwireNode(b_bf,(b_bk||(b_bk={})).eventName,b_bk.handler);};b_t.addChild=function(b_B,b_bl,b_n){if(!b_n)b_n={};var b_o=this,b_u=b_o.b_u,b_bm=Uize.isInstance(b_bl)?b_bl:b_b,b_A='idPrefix'in b_n?b_n.idPrefix:b_n.node,b_bn=b_n.idPrefixConstruction;b_n.parent=b_o;if(b_B==b_h)b_B=b_n.name;if(b_bm){if(b_B==b_h)b_B=b_bm.b_bo;if(b_A==b_h)b_A=b_bm.b_u;if(!b_bn)b_bn=b_bm.b_C;}b_n.idPrefix=b_o.b_y(b_u,b_A,b_n.name=b_B,b_n.idPrefixConstruction=b_bn||(b_A==b_h?b_g:'explicit'));var b_r=b_o.b_r,b_bp=b_r[b_B];if(b_bp){Uize.copyInto(b_n,b_bp);delete b_r[b_B];}b_bm&&b_bm.set(b_n);return b_o.b_s[b_B]=b_bm||new b_bl(b_n);};b_t.removeChild=function(b_bq){var b_s=this.b_s,b_B=typeof b_bq==b_e||Uize.isNumber(b_bq)?b_bq:b_bq.b_bo,b_bm=b_s[b_B];if(b_bm){b_bm.unwireUi();delete b_bm.parent;delete b_s[b_B];}};b_t.getProvider=function(b_br){var
 b_bs=this,b_bt;while(((b_bt=b_bs.get(b_br))==='inherit'||b_bt===b_h)&&(b_bs=b_bs.parent));return b_bs;};b_t.getInherited=function(b_br){var b_bu=this.getProvider(b_br);return b_bu?b_bu.get(b_br):b_h;};b_t.setInherited=function(b_n){var b_bu;for(var b_bv in b_n){if(b_bu=this.getProvider(b_bv))b_bu.set(b_bv,b_n[b_bv]);}};b_t.callInherited=function(b_br){var b_o=this;return(function(){var b_bu=b_o.getProvider(b_br),b_bc;if(b_bu){var b_bw=b_bu.get(b_br);if(b_f(b_bw))b_bc=b_bw.apply(b_bu,arguments);}return b_bc;});};b_t.kill=function(){Uize.callOn(this.b_s,'kill');b_a.prototype.kill.call(this);};b_t.insertOrWireUi=function(){this.b_5?this.wireUi():this.insertUi();};b_t.insertUi=function(){this.buildHtml();this.wireUi();};b_t.removeUi=function(){this.unwireUi();this.removeNode();b_i.remove(this.b_bh);this.b_bh=b_h;Uize.callOn(this.b_s,'removeUi');this.set({b_5:b_d});};b_t.updateUi=function(){};b_t.wireUi=function(){if(!this.isWired){this.b_x();this.set({wired:b_c});var b_s=this.b_s;for(var b_B in b_s)
b_s[b_B].insertOrWireUi();this.updateUi();}};b_t.unwireUi=function(){if(this.isWired){this.b_4=b_b;this.unwireNode();Uize.callOn(this.b_s,'unwireUi');this.set({wired:b_d});}};b_m.getBlankImageUrl=function(){return Uize.pathToResources+'Uize/blank.gif';};b_m.spawn=function(b_n,b_v){var b_o=this,b_bx=[],b_bs,b_by=b_v&&b_v.b_u?b_v.b_u+'_':'',b_bz=b_by.length;b_j(Uize.Node.find(b_n.idPrefix),function(b_bd){b_n.idPrefix=b_bd;b_v?(b_bs=b_v.addChild(b_bd.id.slice(0,b_bz)==b_by?b_bd.id.slice(b_bz):'generatedChildName'+Uize.getGuid(),b_o,b_n)):(b_bs=new b_o(b_n)).insertOrWireUi();b_bx.push(b_bs);});return b_bx;};b_m.registerProperties({b_5:{name:'built',value:b_c},b_H:{name:'busy',onChange:b_t.b_G,value:'inherit'},b_E:{name:'busyInherited',onChange:function(){Uize.callOn(this.b_s,b_t.b_G)},value:b_d},b_s:{name:'children',conformer:function(b_bt){if(b_bt){var b_s=this.b_s,b_r=this.b_r;for(var b_B in b_bt){var b_bA=b_bt[b_B];b_s[b_B]?b_s[b_B].set(b_bA):b_r[b_B]=b_bA;}}return this.b_s;}},b_1:'container',b_J:{
name:'enabled',onChange:b_t.b_I,value:'inherit'},b_F:{name:'enabledInherited',onChange:function(){Uize.callOn(this.b_s,b_t.b_I)},value:b_c},b_Z:'html',b_u:{name:'idPrefix|node',conformer:function(b_u){return b_k(b_u)?(b_u.id||(b_u.id=Uize.getGuid())):b_u;},onChange:function(){var b_o=this,b_u=b_o.b_u;b_o.b_4=b_b;if(b_u!=b_h){b_o.b_x();var b_s=b_o.b_s,b_bm;for(var b_B in b_s)(b_bm=b_s[b_B]).set({b_u:b_o.b_y(b_u,b_bm.b_u,b_B,b_bm.b_C)});if(b_o.isWired){b_o.set({wired:b_d});b_o.wireUi();}}}},b_C:'idPrefixConstruction',b_3:'insertionMode',b_X:'localized',b_bo:'name',b_ba:'nodeMap',isWired:{name:'wired',value:b_d}});return b_m;}});


Uize.module({name:'Uize.Widget.Page',required:'Uize.Node',builder:function(c_a){var c_b=true,c_c=false,c_d,c_e=Uize.Node;var c_f=c_a.subclass(null,function(){c_f.xDeferredLinks&&this.wireDeferredLinks()}),c_g=c_f.prototype;function c_h(c_i){return(Uize.isFunction(c_i)&&c_i)||c_i.callback||Object;}c_g.c_j=function(c_k,c_l,c_m){var c_n=this;c_n.useDialog({component:c_n.c_o.component,widgetClassName:c_n.c_o.widgetClassName||'Uize.Widget.Dialog.Confirm',widgetProperties:{name:'confirmDialog',title:c_m.title||'',message:(c_m.message+'').replace(/\n/g,'<br/>'),mode:c_k,state:c_m.state||c_l,okText:c_m.okText||null,cancelText:c_m.cancelText||null},submitHandler:function(c_p){var c_q=c_m.callback||(c_p?c_m.yesHandler:c_m.noHandler);c_q&&c_q(c_p);}});};c_g.c_r=function(c_s){c_s=c_s||Object;var c_n=this,c_t=c_n.get('idPrefix'),c_u=window;function c_v(c_w,c_x){var c_y,c_z;for(var c_A in c_x)(typeof(c_y=c_w[c_A])=='object'&&typeof(c_z=c_x[c_A])=='object'&&c_y&&c_z)?c_v(c_y,c_z):(c_w[c_A]=c_x[c_A]);}var c_B={},c_C=c_c,
c_D='$'+c_t+'_',c_E=c_D.length,c_F;for(var c_A in c_u){if(c_A.charAt(0)=='$'&&c_A.substr(0,c_E)==c_D&&typeof(c_F=c_u[c_A])=='object'&&c_F&&c_F.widgetClass){c_C=c_b;for(var c_G= -1,c_H=c_B,c_I=c_A.substr(c_E).split('_'),c_J,c_K=c_I.length;++c_G<c_K;){var c_L=c_H[c_J=c_I[c_G]];if(c_G<c_K-1){c_H=(c_L||(c_L=c_H[c_J]={})).children||(c_L.children={});}else{c_L?c_v(c_L,c_F):(c_H[c_J]=c_F);c_u[c_A]=c_d;}}}}if(c_C){function c_M(c_N,c_O){function c_P(c_Q,c_R,c_S){var c_T=c_S.children,c_U=c_N(c_Q,c_R,c_S);c_T&&c_V(c_U,c_T);c_O&&c_O(c_U);}function c_V(c_Q,c_W){for(var c_R in c_W)c_P(c_Q,c_R,c_W[c_R]);}c_V(c_n,c_B);}var c_X={},c_Y=[];c_M(function(c_Q,c_R,c_S){var c_Z=c_S.widgetClass;if(c_Z&& !c_X[c_Z]){c_X[c_Z]=1;c_Y.push(c_Z);}});Uize.module({required:c_Y,builder:function(){c_n.set({children:c_B});c_M(function(c_Q,c_R,c_S){var c_U=c_Q.children[c_R];if(!c_U){var c_Z=eval(c_S.widgetClass||'Uize.Widget');c_U=c_R.charCodeAt(0)==36&&c_R.charCodeAt(1)==36?c_Z.spawn(c_S,c_Q):c_Q.addChild(c_R,c_Z);}return c_U;},
c_n.isWired&&function(c_U){Uize.callOn(c_U,'insertOrWireUi')});c_s();}});}else{c_s();}};c_g.loadHtmlIntoNode=function(c_0,c_1,c_2){var c_n=this,c_3=c_0.rootNodeId,c_s=c_h(c_2),c_4={callback:function(c_5){var c_6=document.body,c_7=c_0.node!=undefined?c_n.getNode(c_0.node):(c_3?c_e.getById(c_3+'-shell'):c_8)||c_6;c_e.injectHtml(c_7,c_5,c_0.injectMode||(c_7==c_6?'inner bottom':'inner replace'));c_n.c_r(c_s);}};c_0.alwaysReplace===c_c&&c_3&&c_e.getById(c_3)?c_s():c_n.loadHtml(c_1,typeof c_2=='object'&&c_2?Uize.copyInto({},c_2,c_4):c_4);};c_g.performAjax=function(){};c_g.useDialog=function(c_m){var c_n=this,c_9=Uize.copyInto({},c_n.c_ba,c_m.widgetProperties),c_bb=c_9.parent||c_n,c_bc=c_9.name,c_bd=c_bb.children[c_bc],c_be=c_m.component,c_bf;if(c_be){var c_3=c_9.idPrefix||(c_bb.get('idPrefix')+'_'+c_bc);c_bf={name:c_be.name,rootNodeId:c_3,params:Uize.copyInto({idPrefix:c_3},c_be.params)};}function c_bg(c_bh){var c_bi=c_n.get('productType');c_bd.fire({name:'Track Event',extra:c_bh+(c_bi?(' ('+c_bi+')'):''),
bubble:c_b});}function c_bj(c_bk){setTimeout(function(){function c_bl(c_bm,c_bn){var c_q=c_m[c_bm];c_q&&c_q.apply(0,c_bn);}function c_bo(c_bp){var c_bn=[c_bp];c_bl(c_bp.name.toLowerCase()+'Handler',c_bn);c_bl('dismissHandler',c_bn);}c_bd.unwire(c_bd.eventHandlersForUseDialog||{});c_bd.eventHandlersForUseDialog={'Submission Complete':function(c_bp){c_bl('submitHandler',[c_bp.result,c_bp])},Close:c_bo,Cancel:c_bo};c_bd.wire(c_bd.eventHandlersForUseDialog);c_bd.set(c_9);c_bd.set({shown:c_b});c_bg(c_bk);},0);}if(c_bd&&(c_bd.componentProfile==c_bf||Uize.Data.identical(c_bd.componentProfile,c_bf))){c_bj('subsequent');}else{var c_bq=c_bf&& !!c_bd;if(c_bq){c_bd.removeUi();c_bb.removeChild(c_bc);}function c_br(){var c_bs=c_m.widgetClassName;Uize.module({required:c_bs,builder:function(){(c_bd=c_bb.children[c_bc])?c_bd.set(c_9):(c_bd=c_bb.addChild(c_bc,eval(c_bs),c_9));c_bd.componentProfile=c_bf;c_bd.wire(c_m.widgetEventHandlers);c_bd.insertOrWireUi();c_bj(c_bq?'refetched':'initial');}});}c_bf?c_n.loadHtmlIntoNode({
rootNodeId:c_bf.rootNodeId,injectMode:'inner bottom',alwaysReplace:c_c},Uize.copyInto({cp:c_bf.name},c_bf.params),{cache:'memory',callback:c_br}):c_br();}};c_g.wireUi=function(){var c_n=this;if(!c_n.isWired){c_n.c_r();c_a.prototype.wireUi.call(c_n);}};var c_bt={yes:1,on:1,1:1,'true':1};c_f.launchPopup=c_g.launchPopup=function(c_m){if(!c_m)c_m={};if(c_m.width==c_d)c_m.width=850;if(c_m.height==c_d)c_m.height=600;var c_bu=window.screen;if(c_m.left==c_d)c_m.left=Math.max((c_bu.width-c_m.width-10)>>1,0);if(c_m.top==c_d)c_m.top=Math.max((c_bu.height-c_m.height-40)>>1,0);function c_bv(c_bw){return c_bw+'='+c_m[c_bw];}function c_bx(c_bw,c_by){return(c_bw+'='+(c_bt[c_m[c_bw]==c_d?c_by:c_m[c_bw]+'']?'yes':'no'));}var c_bz=window.open(c_m.url||'',c_m.name==c_d?'popupWindow':c_m.name,[c_bv('width'),c_bv('height'),c_bv('top'),c_bv('left'),c_bx('toolbar',0),c_bx('location',0),c_bx('directories',0),c_bx('status',0),c_bx('menubar',0),c_bx('scrollbars',1),c_bx('resizable',1)].join(','));c_bz&&c_bz.focus();return c_bz;};
c_f.registerProperties({c_o:{name:'confirmDialog',value:{}},c_ba:'dialogProperties'});c_f.set({idPrefix:'page'});c_g.loadHtml=function(c_1,c_i){c_h(c_i)('');};c_g.showConfirm=function(c_m){this.c_j('confirm','confirm',c_m);};c_g.showInform=function(c_m){this.c_j('alert','info',c_m);};return c_f;}});


Uize.module({name:'UizeDotCom.Templates'});


Uize.module({name:'UizeDotCom.Templates.WidgetToGoTitle',builder:function(){var _a=function(){};_a.process=function(input){var output=[];
output.push('<div class="widgetHeader">\r\n	<div id="',input.idPrefix,'_menu_selector" title="Click to show/hide widget options..." class="widgetTitle">\r\n		<div class="logo"></div>\r\n		<div class="textShadow">',input.title,'</div>\r\n		<div class="textHighlight">',input.title,'</div>\r\n		<div class="textMain">',input.title,'</div>\r\n	</div>\r\n	<div id="',input.idPrefix,'_menu-palette" class="subMenuShell">\r\n		<a id="',input.idPrefix,'_menu-getThisWidget" href="javascript://" class="subMenuItem">GET THIS WIDGET</a>\r\n		<div class="divider"></div>\r\n		<a id="',input.idPrefix,'_menu-aboutThisWidget" href="javascript://" class="subMenuItem">About This Widget</a>\r\n		<a id="',input.idPrefix,'_menu-openInNewWindow" href="javascript://" class="subMenuItem">Open Widget in New Window</a>\r\n		<div class="divider"></div>\r\n		<a id="',input.idPrefix,'_menu-moreWidgets"  href="javascript://" class="subMenuItem">More UIZE Widgets...</a>\r\n		<a id="',input.idPrefix,'_menu-uize" href="javascript://" class="subMenuItem">UIZE JavaScript Framework</a>\r\n	</div>\r\n</div>\r\n\r\n');
return output.join('');};_a.input={idPrefix:'string',title:'string'};return _a;}});


Uize.module({name:'Uize.Fade',builder:function(b_a){var b_b,b_c='object',b_d=Uize.constrain;var b_e={},b_f=[],b_g=false,b_h;function b_i(){if((b_g= !!b_f.length)!= !!b_h)b_h=b_g?setInterval(b_j,10):clearInterval(b_h);}function b_j(){for(var b_k= -1,b_l;++b_k<b_f.length;)(b_l=b_f[b_k]).b_m?b_l.b_j():b_f.splice(b_k--,1);b_i();}function b_n(b_o){return b_o}var b_p=b_a.subclass(),b_q=b_p.prototype;b_q.b_r=function(){var b_s=this,b_o=b_t(b_s.b_u,b_s.b_v,b_s.b_w,b_s.b_x,b_s.b_y,b_s.b_o);if(b_o!=b_e)b_o!=b_s.b_o?b_s.set({b_o:b_o}):b_s.fire('Changed.value');};b_q.b_j=function(){var b_z=Math.min(((Date.now?Date.now(): +new Date)-this.b_A)/this.b_B,1);this.set({b_w:this.b_C?1-b_z:b_z});if(b_z==1){this.stop();this.fire('Done');}};b_q.stop=function(){this.set({b_m:false});};b_q.start=function(b_D){this.stop();this.set(Uize.copyInto({b_m:true},b_D));};var b_t=b_p.blendValues=function(b_E,b_F,b_G,b_x,b_y,b_H){if(b_E===b_F){return b_H!==b_b&&b_E===b_H?b_e:b_E;}else{if(Uize.isFunction(b_y)){b_G=b_y(b_G);b_y=b_b;}
if(typeof b_E==b_c&&b_E&& !(b_E instanceof RegExp)){var b_I=b_H&&typeof b_H==b_c,b_J=b_x&&typeof b_x==b_c,b_K=b_y&&typeof b_y==b_c,b_L=b_I?b_H:Uize.isArray(b_E)?[]:{},b_M;for(var b_N in b_E){var b_O=b_t(b_E[b_N],b_F[b_N],b_G,b_J?b_x[b_N]:b_x,b_K?b_y[b_N]:b_y,b_M=b_L[b_N]);if(b_I)b_I=b_O==b_e||(typeof b_O!=b_c&&b_O==b_M);if(b_O!=b_e)b_L[b_N]=b_O;}return b_I?b_e:b_L;}else{var b_L= !b_G?b_E:b_G==1?b_F: !b_x?b_E+(b_F-b_E)*b_G:b_G>0&&b_G<1?b_d(b_E+Math.round((b_F-b_E)*b_G/b_x)*b_x,b_E,b_F):b_E+Math.round((b_F-b_E)*b_G/b_x)*b_x;return b_H!==b_b&&b_L===b_H?b_e:b_L;}}};b_p.celeration=function(b_P,b_Q){var b_R=1-(b_P=b_P||0)-(b_Q=b_Q||0),b_S=2/(1+b_R),b_T=b_P?b_S/b_P:0,b_U=b_T/2,b_V=b_Q? -b_S/b_Q:0,b_W=b_V/2,b_X=b_P*b_P,b_Y;return(b_R>=1?b_n:function(b_o){return((b_o=(b_P?b_d(b_o*b_o,0,b_X)*b_U:0)+(b_R?b_S*b_d(b_o-b_P,0,b_R):0)+(b_Q?((b_S+(b_Y=b_d(b_o-b_P-b_R,0,b_Q))*b_W)*b_Y):0))>1?1:b_o);});};function b_Z(){this.set({b_y:this.b_P||this.b_Q?b_p.celeration(this.b_P,this.b_Q):null});}function b_0(){this.b_o=null;
this.b_r();}b_p.registerProperties({b_P:{name:'acceleration',onChange:b_Z},b_y:{name:'curve',onChange:b_0},b_Q:{name:'deceleration',onChange:b_Z},b_B:{name:'duration',value:2000},b_v:{name:'endValue',onChange:b_0,value:100},b_m:{name:'inProgress',onChange:function(){var b_s=this;if(b_s.b_m){b_s.b_A=Date.now?Date.now(): +new Date;b_s.fire('Start');b_s.b_o=b_s.b_w=null;b_s.b_j();b_f.push(b_s);b_i();}},value:false},b_w:{name:'progress',onChange:b_q.b_r,value:0},b_C:'reverse',b_u:{name:'startValue',onChange:b_0,value:0},b_x:'quantization',b_o:{name:'value',value:0}});return b_p;}});


Uize.module({name:'Uize.Widget.Button',required:'Uize.Node',builder:function(c_a){var c_b,c_c=true,c_d=false,c_e=Uize.Node;var c_f=c_a.subclass(null,function(){var c_g=this;function c_h(){if(c_g.isWired){c_g.c_i()||c_g.set({c_j:''});c_g.c_h();}}c_g.wire({'Changed.busyInherited':c_h,'Changed.enabledInherited':c_h});}),c_k=c_f.prototype;var c_l,c_m={},c_n={grayed:16,'':8,over:4,active:2,playing:1},c_o='(Grayed|Over|Active|Playing)',c_p=new RegExp(c_o),c_q=new RegExp('(?:(?:(\\S+)\\s+\\1'+c_o+'))','g'),c_r=new RegExp('\\S*'+c_o+'\\b','g'),c_s=/\b(disabled|over|active|playing)\b/,c_t={},c_u={mouseover:['over','Over'],mouseout:['','Out'],mousedown:['down','Down'],mouseup:['over','Up'],click:['over','Click']};c_k.c_v=c_d;c_k.c_i=function(){var c_g=this;return!!(c_g.get('enabledInherited')&& !c_g.get('busyInherited')&&(!c_g.c_w||c_g.c_x||c_g.c_y));};c_k.c_z=function(){this.c_A!=c_b&&this.isWired&&this.setNodeInnerHtml('text',this.c_A);};var c_h=c_k.c_h=function(){var c_g=this;if(c_g.isWired){var c_B=c_g.c_B,
c_C=c_g.get('enabledInherited'),c_D=c_g.get('busyInherited'),c_E=(!c_C?16:0)|(!c_g.c_j||c_D?8:0)|(c_g==c_l?4:0)|(c_g.c_j=='down'||c_g.c_w?2:0)|(c_g.c_F?1:0),c_G=c_g.c_H[c_E];if(c_G==c_b){for(var c_I= -1,c_J=c_g.c_J,c_K=c_J.length;++c_I<c_K;){var c_L=c_J[c_I];if(c_E&c_n[c_L]){c_G=c_L;break;}}c_g.c_H[c_E]=c_G;}if(c_g.c_M=='classes'){var c_N=c_B.className,c_O='';if(c_g.c_P=='disambiguated'){var c_Q=c_g.c_Q;if(c_Q==c_b){var c_R=c_N.match(c_q);if(c_R){c_Q=c_R[c_R.length-1].split(' ',2)[0];}else{c_R=c_N.replace(c_r,'').match(/(\S+)\s*$/);if(c_R)c_Q=c_R[c_R.length-1];}if(c_g.c_Q=c_Q=c_Q||'')c_g.c_S=c_t[c_Q]||(c_t[c_Q]=new RegExp(c_Q+'(\\s+'+c_Q+c_o+')?'));}var c_T=c_G?' '+c_Q+Uize.capFirstChar(c_G):'';c_O=c_Q?c_N.replace(c_g.c_S,c_Q+c_T):c_N.replace(c_p,'')+c_T;}else{var c_U=c_G=='grayed'?'disabled':c_G;c_O=c_s.test(c_N)?c_N.replace(c_s,c_U):c_N+(c_U?' ':'')+c_U;}if(c_O!=c_N)c_B.className=c_O;}else if(c_g.c_M=='frames'){c_g.c_V.style.top='-'+(c_g.c_W.c_X[c_G]*c_g.c_Y.height)+'px';}if(c_g.c_Z&&Uize.Tooltip){
var c_0=c_g.c_j=='over'&&c_C&& !c_g.c_w;c_0!=c_g.c_v&&Uize.Tooltip.showTooltip(c_g.c_Z,c_g.c_v=c_0);}c_g.get('busyInherited')?c_e.setStyle(c_B,{cursor:'wait'}):c_e.showClickable(c_B,c_g.c_i());}};c_k.c_1=function(c_2){var c_g=this;if(c_g.isWired){var c_3=c_2.type,c_4=c_3=='click',c_i=c_g.c_i();if(!c_g.c_5){c_g.c_5=c_c;function c_1(c_2){c_g.c_1(c_2)}c_g.wireNode(c_g.c_B,{mouseout:c_1,mousedown:c_1,mouseup:c_1});}if(c_4)c_2.cancelBubble=c_c;if(c_i){var c_6=c_u[c_3];c_g.set({c_j:c_6[0]});c_g.fire({name:c_6[1],domEvent:c_2});c_4&&(c_g.c_w?c_g.c_x:c_g.c_7)&&c_g.set({c_w:!c_g.c_w});}}};c_k.updateUi=function(){this.c_h();this.c_z();};c_k.wireUi=function(){var c_g=this;if(!c_g.isWired){c_g.c_V=c_b;var c_B=c_g.c_B=c_g.getNode();if(c_B){var c_8=c_B.childNodes;if(c_8.length&&(c_8.length>1||c_8[0].nodeType!=3)&&(c_g.c_V=c_g.getNode('frames'))){c_g.c_M='frames';c_g.c_Y=c_e.getDimensions(c_g.c_V.parentNode);}if(c_g.c_9&&c_B.tagName=='A'&& !c_B.onclick)c_B.onclick=c_e.returnTrue;function c_1(c_2){c_g.c_1(c_2)}c_g.wireNode(
c_B,{mouseover:c_1,click:c_1});if(c_g.c_A==c_b){var c_ba=c_g.getNode('text');c_ba&&c_g.set({c_A:c_ba.innerHtml});}c_a.prototype.wireUi.call(c_g);}}};c_f.addChildButton=function(c_bb,c_bc){var c_g=this,c_bd;function c_be(){c_bd.wire('Click',function(c_bf){if(c_bc)typeof c_bc=='string'?c_g.fire(c_bc):c_bc(c_bf);c_g.fire(c_bf);});}if(c_g==c_f){c_bd=new c_f({idPrefix:c_bb,name:c_bb,c_9:c_c});c_be();(window[c_bd.instanceId]=c_bd).wireUi();}else{c_bd=c_g.children[c_bb];if(!c_bd){c_bd=c_g.addChild(c_bb,c_f);c_be();}}return c_bd;};c_f.registerProperties({c_y:{name:'allowClickWhenSelected',onChange:c_h},c_7:'clickToSelect',c_x:{name:'clickToDeselect',onChange:c_h},c_P:{name:'classNamingForStates',value:'disambiguated'},c_W:{name:'frameOrder',onChange:function(){var c_W=this.c_W;if(!c_W.c_X){for(var c_bg= -1,c_bh=c_W.length,c_X=c_W.c_X={};++c_bg<c_bh;)c_X[c_W[c_bg]]=c_bg;}},value:['grayed','','over','active','playing']},c_9:{name:'followLink',value:c_d},c_M:{name:'mode',value:'classes'},c_F:{name:'playing',
onChange:c_h,value:c_d},c_w:{name:'selected',onChange:c_h,value:c_d},c_j:{name:'state',onChange:function(){var c_g=this;if(!c_g.c_j){if(c_l==c_g)c_l=c_b;}else if(c_g.c_j=='over'){c_l&&c_l!=c_g&&c_l.set({c_j:''});c_l=c_g;}c_g.isWired&&c_g.c_h();},value:''},c_J:{name:'statePrecedence',onChange:function(){var c_g=this,c_bi=c_g.c_J.c_bj||(c_g.c_J.c_bj=c_g.c_J.join(','));c_g.c_H=c_m[c_bi]||(c_m[c_bi]={});c_g.isWired&&c_g.c_h();},value:['playing','active','grayed','over','']},c_A:{name:'text',onChange:c_k.c_z},c_Z:'tooltip'});return c_f;}});


Uize.module({name:'Uize.Widget.PopupPalette',required:['Uize.Node','Uize.Fade','Uize.Widget.Button'],builder:function(c_a){var c_b=true,c_c=false,c_d=null,c_e=Uize.Node;var c_f=c_a.subclass(null,function(){var c_g=this;c_g.fade=new Uize.Fade({duration:750,curve:Uize.Fade.celeration(0,1)});c_g.fade.wire({'Changed.value':function(){c_g.setNodeOpacity('palette',c_g.fade)},Done:function(){c_g.c_h(c_g.c_i)}});var c_j=c_g.c_j=c_g.c_k('selector',function(){c_g.toggle('shown')}),c_l;c_j.set({clickToDeselect:c_b});c_g.c_m();function c_n(c_o){var c_p=c_o.name=='Over',c_q=c_g.c_q;function c_r(){c_g.set({c_i:c_b})}if(c_p){if(c_q===c_b||c_q===0)c_r();else if(c_q>0)c_l=setTimeout(c_r,c_q);c_g.c_s()}else{clearTimeout(c_l);c_g.c_t();}}c_j.wire({Down:c_u,Over:c_n,Out:c_n});c_v[c_g.instanceId]=c_g;}),c_w=c_f.prototype,c_v={};c_w.c_m=function(){this.c_j.set({selected:this.c_i})};c_w.c_x=function(){return this.c_i&&(this.c_q!==c_c||this.c_y);};c_w.c_s=function(){this.c_x()&&this.c_z();this.fire('Over');};c_w.c_t=function(){
this.c_x()&&this.c_A();this.fire('Out');};c_w.c_k=Uize.Widget.Button.addChildButton;c_w.c_h=function(c_B){var c_g=this;c_g.displayNode('palette',c_B);c_B&&c_g.setNodeStyle('palette',{filter:''});c_g.fire({name:'Palette '+(c_B?'Shown':'Dismissed'),bubble:c_b});};c_w.c_z=function(){var c_g=this;if(c_g.c_C){clearTimeout(c_g.c_C);c_g.c_C=null;}};c_w.c_A=function(){var c_g=this;c_g.c_z();c_g.c_C=setTimeout(function(){c_g.set({c_i:c_c})},250);};c_w.kill=function(){delete c_v[this.instanceId];c_a.prototype.kill.call(this);};c_w.wireUi=function(){var c_g=this;if(!c_g.isWired){c_g.wireNode('palette',{mousedown:c_u,mouseup:function(c_o){c_g.c_D&&c_o.target!=c_g.getNode('palette')&&c_g.set({c_i:c_c});},mouseover:function(){c_g.c_s()},mouseout:function(){c_g.c_t()}});c_g.wireNode('paletteClose','click',function(){c_g.set({c_i:c_c})});if(c_g.c_E!='none'){var c_F=document.body,c_G=c_g.getNode('palette');if(c_G&&c_G.parentNode!=c_F){c_F.insertBefore(c_G,c_F.childNodes[0]);c_g.setNodeStyle(c_G,{zIndex:10000,
position:'absolute',left:'',top:'',right:'',bottom:'',width:c_g.getNodeStyle(c_G,'width')});}}c_a.prototype.wireUi.call(c_g);}};c_f.registerProperties({c_H:{name:'exclusive',value:c_b},c_y:{name:'hideWhenOut',value:c_c},c_D:{name:'hideOnClick',value:c_b},c_E:{name:'positioning',value:'none'},c_i:{name:'shown',onChange:function(){var c_g=this,c_i=c_g.c_i,c_E=c_g.c_E;c_g.c_j&&c_g.c_m();if(c_g.isWired){c_g.c_z();if(c_i){c_g.fire('Before Palette Shown');c_g.c_H&&c_I(c_g);if(c_E!='none'){var c_G=c_g.getNode('palette'),c_J=Uize.isFunction(c_E)?c_E(c_G):c_g.c_j.getNode();function c_K(c_L){c_g.showNode('palette',!c_L);c_g.displayNode('palette',c_L);}if(c_e.isNode(c_J)){c_K(c_b);c_e.setAbsPosAdjacentTo(c_G,c_J);c_K(c_c);}}}if(c_g.fade.get('duration')>0){c_i&&c_g.displayNode('palette');c_g.fade.start({startValue:c_i?0:1,endValue:c_i?1:0});}else{c_g.c_h(c_i);}}},value:c_c},c_q:{name:'showWhenOver',value:c_c}});function c_I(c_M){for(var c_N in c_v){var c_O=c_v[c_N];c_O!=c_M&&c_O.c_H&&c_O.set({c_i:c_c});}}
function c_u(){c_P=c_b}if(typeof navigator!='undefined'){var c_P=c_c,c_Q=document.onmousedown;document.onmousedown=function(c_o){if(!c_o)c_o=event;c_P?(c_P=c_c):c_I();Uize.isFunction(c_Q)&&c_Q(c_o);};}return c_f;}});


Uize.module({name:'UizeDotCom.WidgetToGoPage',superclass:'Uize.Widget.Page',required:['Uize.Node','UizeDotCom.Templates.WidgetToGoTitle','Uize.Widget.PopupPalette'],builder:function(d_a){var d_b=d_a.subclass(null,function(){this.addChild('menu',Uize.Widget.PopupPalette,{hideWhenOut:true,positioning:'absolute'}).fade.set({duration:0});}),d_c=d_b.prototype;d_c.wireUi=function(){var d_d=this;if(!d_d.isWired){Uize.Node.injectHtml(document.body,UizeDotCom.Templates.WidgetToGoTitle.process({idPrefix:d_d.get('idPrefix'),title:document.title}));Uize.module({required:[d_d.d_e,d_d.d_f],builder:function(){d_d.addChild('widget',eval(d_d.d_e),{built:false,html:eval(d_d.d_f)}).insertOrWireUi();}});var d_g=d_d.children.menu,d_h='../'+d_d.d_i.toLowerCase().replace(/\s+/g,'-')+'.html';function d_j(d_k,d_l,d_m,d_n,d_o){page.launchPopup({name:d_k,url:d_l,width:d_m,height:d_n,toolbar:d_o,location:d_o,directories:d_o,status:d_o,menubar:d_o,scrollbars:d_o,resizable:d_o});}function d_p(d_q,d_l){
d_g.wireNode(d_q,'click',function(){d_j(null,d_l,1010,690,1)});}d_p('getThisWidget',d_h);d_p('aboutThisWidget',d_h);d_p('moreWidgets','../../javascript-widgets.html');d_p('uize','../../index.html');d_g.wireNode('openInNewWindow','click',function(){var d_r=Uize.Node.getDimensions(window);d_j('',location.href,d_r.width,d_r.height,0);});d_a.prototype.wireUi.call(d_d);}};d_b.registerProperties({d_i:'title',d_e:'widgetClass',d_f:'widgetHtml'});return d_b;}});


Uize.module({name:'Uize.Node.Event',builder:function(){var _a=function(_b){return _b||event};_a.abort=function(_b){_a.preventDefault(_b||(_b=event));_a.stopPropagation(_b);};_a.charCode=function(_b){_b||(_b=event);if(_b.ctrlKey||_b.altKey||_b.which<1)return 0;return'charCode'in _b?_b.charCode:_a.keyCode(_b);};_a.fix=function(_b){_b||(_b=event);_b.target=_a.target(_b);_b.relatedTarget=_a.relatedTarget(_b);_b.charCode=_a.charCode(_b);_b.keyCode=_a.keyCode(_b);_b.preventDefault||(_b.preventDefault=_c);_b.stopPropagation||(_b.stopPropagation=_d);return _b;};var _e={Backspace:8,Delete:46,Insert:45,Enter:13,Escape:27,Space:32,Tab:9,PageUp:33,PageDown:34,End:35,Home:36,LeftArrow:37,RightArrow:39,UpArrow:38,DownArrow:40};function _f(_g,_h){_a['isKey'+_g]=function(_b){return _a.keyCode(_b)==_h};}for(var _g in _e)_f(_g,_e[_g]);_a.keyCode=function(_b){return'which'in(_b||(_b=event))?_b.which:_b.keyCode;};function _c(){this.preventDefault?this.preventDefault():(this.returnValue=false);}
_a.preventDefault=function(_b){_c.call(_b||event)};_a.relatedTarget=function(_b){return('relatedTarget'in(_b||(_b=event))?_b.relatedTarget:(_b.type=='mouseout'?_b.toElement:_b.fromElement));};function _d(){this.stopPropagation?this.stopPropagation():(this.cancelBubble=true);}_a.stopPropagation=function(_b){_d.call(_b||event)};_a.target=function(_b){return(_b||(_b=event)).target||_b.srcElement;};return _a;}});


Uize.module({name:'Uize.Tooltip',required:['Uize.Node','Uize.Fade'],builder:function(){var _a=function(){},_b=true,_c=false,_d,_e=Uize.Node;var _f=Uize.getGuid(),_g=[],_h,_i=16;function _j(_k){return _e.getById(Uize.isFunction(_k)?_k():_k);}function _l(){_m()}function _n(_o){if(_o!=_h){if(_o){if(_h){_p.stop();_q();}if(!_o._r){_e.wire(document.body,'scroll',_l,_f);_e.wire(document.documentElement,'mousemove',_l,_f);}_h=_o;_e.setStyle(_h._s,{position:'absolute',zIndex:5000,left:-50000,top:-50000});_e.display(_h._s);_m();}else{_p.get('duration')>0?_p.start():_q();}}else if(_o){_p.stop();_e.setOpacity(_h._s,1);}}_a.showTooltip=function(_k,_t,_r){if(_k=_j(_k)){if(_t!==_c){_g.push({_s:_k,_r:_r});}else{for(var _u=_g.length;--_u> -1;)if(_g[_u]._s==_k)break;_u> -1&&_g.splice(_u,1);}_n(_g[_g.length-1]);}};_a.hideTooltip=function(_k){_a.showTooltip(_k,_c)};var _m=_a.positionTooltip=function(_k,_v){_h&&(_k===_d?(_k=_h._s):_h._s==_j(_k))&&_e.setAbsPos(_k,_e.getEventAbsPos(_v),_i);};
var _p=_a.fade=new Uize.Fade({duration:0});function _q(){_h._r||_e.unwireEventsByOwnerId(_f);_e.display(_h._s,_c);_e.setOpacity(_h._s,1);_h=null;}_p.wire({'Changed.value':function(){_e.setOpacity(_h._s,1-_p.get('progress'))},Done:_q});return _a;}});


Uize.module({name:'Uize.Templates'});


Uize.module({name:'Uize.Date',builder:function(){var _a=function(_b,_c,_d,_e,_f,_g,_h){var _i=new Date(+_b+(_b<100&&400),(+_c||1)-1,+_d||1,+_e||0,+_f||0,+_g||0,+_h||0);_b<100&&_i.setFullYear(_b);return _i;},_j;function _k(_l){return isNaN(_l)?'??':(_l<10?'0':'')+_l}function _m(_l){return(isNaN(_l)?'???':(_l<10?'00':_l<100?'0':'')+_l);}function _n(_l){return(isNaN(_l)?'????':(_l<10?'000':_l<100?'00':_l<1000?'0':'')+_l);}var _o={ms:1,seconds:1000,minutes:60000,hours:3600000,days:86400000,weeks:604800000,months:2629743840,years:31556926080};var _p=_a.convert=function(_q,_r,_s){return _q*_o[_r+'']/_o[_s+''];};var _t=_a.resolve=function(_i,_u){return(_i instanceof Date?_i:_i==null||_i===''?(_u!==_j?_u:new Date):typeof _i=='string'?_a.fromIso8601(_i)||new Date(_i):new Date(+_i));};_a.equal=function(_v,_w,_x){return _a.inRange(_v,_a.getRangeAround(_w,_x||'day'));};_a.toIso8601=function(_i){return(_n((_i=_t(_i)).getFullYear())+'-'+_k(_i.getMonth()+1)+'-'+_k(_i.getDate()));};_a.fromIso8601=function(_y){
var _z=_y.match(/(\d{2,})-(\d\d?)-(\d\d?)(?:\D|$)/);return(_z?_a(+_z[1]+(_z[1].length<3)*1900,_z[2],_z[3]):_j);};var _A={date:'Invalid Date',YYYY:'????',YY:'??',MM:'??',monthNo:'?',monthName:'?????????',shortMonthName:'???',DD:'??',dayNo:'?',dayNoSuffix:'??',dayName:'????????',shortDayName:'???',hh:'??',h12:'?',hh12:'??',mm:'??',minutes:'?',ss:'??',seconds:'?',zzz:'???',milliseconds:'?',ampm:'??'};_a.format=_a.toPretty=function(_i,_B){var _C=_A;if(!isNaN(_i=_t(_i))){var _D=_n(_i.getFullYear()),_E=_i.getMonth()+1,_d=_i.getDate(),_F=_d%10,_G=_i.getDay(),_H=_i.getHours(),_I=_H>11,_J=(_H-(_I&&12))||12,_f=_i.getMinutes(),_g=_i.getSeconds(),_h=_i.getMilliseconds();_C={date:_i,YYYY:_D,YY:_D.slice(-2),MM:_k(_E),monthNo:_E,monthName:_a.monthNames[_E-1],shortMonthName:_a.shortMonthNames[_E-1],DD:_k(_d),dayNo:_d,dayNoSuffix:_a.dayNoSuffixes[(_F<4&&Math.floor(_d/10)%10!=1)*_F],dayName:_a.dayNames[_G],shortDayName:_a.shortDayNames[_G],hh:_k(_H),h12:_J,hh12:_k(_J),mm:_k(_f),minutes:_f,ss:_k(_g),seconds:_g,zzz:_m(_h),
milliseconds:_h,ampm:_I?'pm':'am'};}return Uize.substituteInto(_B||'{dayName}, {dayNo}{dayNoSuffix} {monthName} {YYYY}',_C,'{KEY}');};_a.getRangeAround=function(_i,_K){var _L=new Date(_i=_t(_i)),_M=new Date(_L);function _N(_O,_P,_Q){_L[_O](_P);_M[_O](_Q);}function _R(_S,_T){var _U=Math.floor(_i['get'+_S]()/_T)*_T;_N('set'+_S,_U,_U+_T-1);}switch(_K||(_K='month')){case'millennium':case'century':case'decade':_R('FullYear',_K=='millennium'?1000:_K=='century'?100:10);case'year':case'quarter':_K=='quarter'?_R('Month',3):_N('setMonth',0,11);case'month':case'week':if(_K=='week'){var _V=_i.getDate()-_i.getDay();_N('setDate',_V,_V+6);}else{_N('setDate',1,_a.getDaysInMonth(_M.getMonth(),_M.getFullYear()));}case'day':case'am/pm':_K=='am/pm'?_R('Hours',12):_N('setHours',0,23);case'hour':_N('setMinutes',0,59);case'minute':_N('setSeconds',0,59);case'second':_N('setMilliseconds',0,999);}return{minValue:_L,maxValue:_M};};_a.inRange=function(_i,_W){if(typeof _i!='number')_i= +_t(_i);
return _i>=_t(_W.minValue,-Infinity)&&_i<=_t(_W.maxValue,Infinity);};_a.isLeapYear=function(_b){return _b%4==0&&(_b%100!=0||_b%400==0);};_a.getDaysInMonth=function(_c,_b){return 30+((2773>>_c)&1)-(_c==1&&(2-_a.isLeapYear(_b)));};_a.isRecent=function(_i,_X,_Y){return _a.inRange(_i,{minValue:_t(_Y)-_p(_X,'days','ms')});};_a.dayNames=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];_a.dayNoSuffixes=['th','st','nd','rd'];_a.monthNames=['January','February','March','April','May','June','July','August','September','October','November','December'];_a.shortDayNames=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'];_a.shortMonthNames=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];return _a;}});


Uize.module({name:'Uize.Date.Formatter',builder:function(){var _a=function(){},_b=Uize.Date;var _c,_d={YYYY:'\\d{4}',YY:'\\d\\d',MM:'1[0-2]|0[1-9]',monthNo:'1[0-2]|0?[1-9]',DD:'30|31|[1-2]\\d|0[1-9]',dayNo:'30|31|[1-2]\\d|0?[1-9]',dayNoSuffix:_b.dayNoSuffixes.join('|'),hh:'[0-1]\\d|2[0-3]',h12:'1[0-2]|0?[1-9]',hh12:'1[0-2]|0[1-9]',mm:'[0-5]\\d',minutes:'[0-5]?\\d',ss:'[0-5]\\d',seconds:'[0-5]?\\d',zzz:'\\d{3}',milliseconds:'\\d{1,3}',ampm:'am|pm'},_e={monthName:1,shortMonthName:1,dayName:1,shortDayName:1},_f=String.fromCharCode(7);function _g(_h,_i){_i=_i.toLowerCase();for(var _j= -1,_k=_h.length;++_j<_k;)if(_i==_h[_j].toLowerCase())return _j;return-1;}_a.format=_a.toPretty=_b.format;_a.parse=function(_l,_m){var _n;if(typeof _l=='object'&&_l&& !(_l instanceof Date))_l=_l.valueOf();if(_l instanceof Date)return _l;if(_l==null||_l=='')return;if(typeof _l=='number')return new Date(_l);if(!_m)return _b.resolve(_l);for(_n in _e)_d[_n]=null;if(!_c){var _o=[];for(_n in _d)_o.push(_n);
_c=new RegExp('\\{('+_o.join('|')+')\\}','g');}var _p=[],_q=0,_r=new RegExp(Uize.escapeRegExpLiteral(_m.replace(_c,function(_s,_n){_p.push(_n);return _f;})).replace(/\s+/g,'\\s+').replace(/\x07/g,function(){return('\\s*('+(_d[_n=_p[_q++]]||(_d[_n]=_b[_n+'s'].join('|')))+')\\s*');}),'i'),_t=(_l+'').match(_r);if(_t){var _u=0,_v=1,_w=1,_x,_y=0,_z=0,_A=0,_B=0,_C=false;for(var _D=0,_E=_t.length;++_D<_E;){var _F=_t[_D];switch(_p[_D-1]){case'YYYY':_u= +_F;break;case'YY':_u=1900+ +_F;break;case'MM':case'monthNo':_v= +_F;break;case'monthName':_v=_g(_b.monthNames,_F)+1;break;case'shortMonthName':_v=_g(_b.shortMonthNames,_F)+1;break;case'DD':case'dayNo':_w= +_F;break;case'hh':_x= +_F;break;case'h12':case'hh12':_y= +_F;break;case'mm':case'minutes':_z= +_F;break;case'ss':case'seconds':_A= +_F;break;case'zzz':case'milliseconds':_B= +_F;case'ampm':_C=/^pm$/i.test(_F)}}return _b(_u,_v,_w,_x!==undefined?_x:_y*(_y!=12)+_C*12,_z,_A,_B);}};return _a;}});


Uize.module({name:'Uize.Widget.Calendar',required:['Uize.Widget.Button','Uize.Date','Uize.Date.Formatter'],builder:function(c_a){var c_b=true,c_c=false,c_d=null,c_e=Uize.Date,c_f=c_e.dayNames,c_g=c_e.monthNames;var c_h=c_a.subclass(c_d,function(){var c_i=this;c_i.c_j=c_i.c_k('nextMonth',function(){c_i.set({c_l:c_i.c_l+1})});c_i.c_m=c_i.c_k('previousMonth',function(){c_i.set({c_l:c_i.c_l-1})});c_i.c_n=c_i.c_k('nextYear',function(){c_i.set({c_o:c_i.c_o+1})});c_i.c_p=c_i.c_k('previousYear',function(){c_i.set({c_o:c_i.c_o-1})});c_i.c_q=c_b;c_i.c_r();}),c_s=c_h.prototype;c_s.c_k=Uize.Widget.Button.addChildButton;var c_t=c_s.c_t=function(){var c_i=this,c_u={minValue:c_i.c_v,maxValue:c_i.c_w};c_i.c_x&& !c_e.inRange(c_i.c_x,c_u)&&c_i.set({c_x:c_d});var c_y=c_i.c_x||new Date;if(!c_e.inRange(c_y,c_u))c_y=c_i.c_v||c_i.c_w;c_i.set({c_l:c_y.getMonth(),c_o:c_y.getFullYear()});};var c_r=c_s.c_r=function(){var c_i=this;if(c_i.c_q){var c_z=new Date(c_i.c_o,c_i.c_l,1),c_A=c_e.getRangeAround(c_z,'month'),
c_B=c_e.getRangeAround(c_z,'year'),c_v=c_i.c_v,c_w=c_i.c_w;function c_C(c_D,c_E){c_D.set({enabled:c_E?'inherit':c_c});}c_C(c_i.c_m,!c_v||c_v<c_A.minValue);c_C(c_i.c_j,!c_w||c_w>c_A.maxValue);c_C(c_i.c_p,!c_v||c_v<c_B.minValue);c_C(c_i.c_n,!c_w||c_w>c_B.maxValue);}};c_s.c_F=function(){this.isWired&&this.setNodeValue('month',c_g[this.c_l]);};c_s.c_G=function(){this.isWired&&this.setNodeValue('year',this.c_o);};var c_H=c_s.c_H=function(){var c_i=this;if(c_i.isWired){function c_I(c_y,c_J){return(c_y?c_y.getFullYear()*10000+(c_y.getMonth()+1)*100+c_y.getDate():c_J);}var c_x=c_i.c_x,c_v=c_i.c_v,c_w=c_i.c_w,c_o=c_i.c_o,c_l=c_i.c_l,c_K=c_e.getDaysInMonth(c_l,c_o),c_L=new Date(c_o,c_l,1),c_M=c_I(c_L),c_N=Uize.constrain(c_I(c_v,0)-c_M+1,1,c_K+1),c_O=Uize.constrain(c_I(c_w,Infinity)-c_M+1,-1,c_K),c_P=c_i.c_P;if(!c_P||c_x!=c_P.c_x||c_l!=c_P.c_l||c_o!=c_P.c_o||c_N!=c_P.c_N||c_O!=c_P.c_O){if(c_P){for(var c_Q=0,c_R;++c_Q<32;){c_i.unwireNode(c_R='day'+c_Q);c_i.flushNodeCache(c_R);}}if(!c_P)c_P=c_i.c_P={};c_P.c_x=c_x;
c_P.c_l=c_l;c_P.c_o=c_o;c_P.c_N=c_N;c_P.c_O=c_O;var c_S=['<table class="calendarGrid" cellpadding="0" cellspacing="0"><tr>'];for(var c_Q= -1;++c_Q<7;)c_S.push('<th title="'+c_f[c_Q]+'">'+c_f[c_Q].charAt(0)+'</th>');c_S.push('</tr><tr>');var c_T=c_I(c_x,c_d),c_U=c_i.get('idPrefix'),c_Q=1-c_L.getDay();for(var c_V= -1;++c_V<6;){c_S.push('<tr>');for(var c_W= -1;++c_W<7;){if(c_Q>0&&c_Q<=c_K){var c_X=c_I(new Date(c_o,c_l,c_Q))==c_T;c_S.push(c_Q>=c_N&&c_Q<=c_O?('<td'+(c_X?' class="selected"':'')+'><a href="javascript://" id="'+c_U+'-day'+c_Q+'" style="display:block; width:100%; text-align:center;">'+c_Q+'</a></td>'):('<td class="'+(c_X?'selected ':'')+'grayed">'+c_Q+'</td>'),'</td>');}else{c_S.push('<td>&nbsp;</td>');}c_Q++;}c_S.push('</tr>');}c_S.push('</table>');c_i.setNodeInnerHtml('grid',c_S.join(''));function c_Y(c_Q){c_i.wireNode('day'+c_Q,'click',function(){c_i.set({c_x:new Date(c_o,c_l,c_Q)})});}for(var c_Q=c_K+1;--c_Q>0;)c_Y(c_Q);}}else{c_i.c_P=c_d;}};c_s.updateUi=function(){this.c_F();this.c_G();
this.c_H();};function c_Z(c_x){return c_e.Formatter.parse(c_x,this.c_0)||null;}c_h.registerProperties({c_0:'displayFormat',c_w:{name:'maxValue',conformer:c_Z,onChange:[c_t,c_H,c_r]},c_v:{name:'minValue',conformer:c_Z,onChange:[c_t,c_H,c_r]},c_l:{name:'month',conformer:function(c_x){var c_1=Math.floor(c_x/12);c_1&&this.set({c_o:this.c_o+c_1});return((c_x%12)+12)%12;},onChange:[c_s.c_F,c_H,c_r]},c_2:{name:'snapViewOnValueChange',value:c_b},c_x:{name:'value',conformer:c_Z,value:new Date,onChange:[function(){this.c_2&&this.c_t()},c_H,c_r]},c_o:{name:'year',onChange:[c_s.c_G,c_H,c_r]}});return c_h;}});


Uize.module({name:'Uize.Templates.Calendar',builder:function(){var _a=function(){};_a.process=function(input){var output=[];
output.push('<div class="calendarContainer">\r\n	<div id="',input.idPrefix,'-controls" class="calendarControls">\r\n		<div id="',input.idPrefix,'-indicator" class="calendarIndicator">\r\n			<span id="',input.idPrefix,'-month" class="monthIndicator">Month</span>\r\n			<span id="',input.idPrefix,'-year" class="yearIndicator">Year</span>\r\n		</div>\r\n		<a href="javascript://" id="',input.idPrefix,'_previousMonth" class="calendarControl previousMonth" title="previous month">&#9668;</a>\r\n		<a href="javascript://" id="',input.idPrefix,'_nextMonth" class="calendarControl nextMonth" title="next month">&#9658;</a>\r\n		<a href="javascript://" id="',input.idPrefix,'_previousYear" class="calendarControl previousYear" title="previous year">&laquo;</a>\r\n		<a href="javascript://" id="',input.idPrefix,'_nextYear" class="calendarControl nextYear" title="next year">&raquo;</a>\r\n	</div>\r\n	<div id="',input.idPrefix,'-grid" class="calendarGrid"></div>\r\n</div>\r\n');return output.join('');};_a.input={idPrefix:'string'
};return _a;}});


Uize.module({name:'UizeDotCom.WidgetToGoPage.Calendar'});

Uize.module ({name:'UizeDotCom.WidgetToGoPage.Calendar.library'});

