/*
	UIZE JAVASCRIPT FRAMEWORK 2011-04-01

	http://www.uize.com/reference/Uize.Widget.Drag.html
	Available under MIT License or GNU General Public License -- http://www.uize.com/license.html
*/
Uize.module({name:'Uize.Widget.Drag',required:['Uize.Node','Uize.Node.Event'],builder:function(c_a){var c_b,c_c=true,c_d=false,c_e=Uize.Node,c_f=c_e.getEventAbsPos,c_g=c_e.isIe;var c_h,c_i=typeof navigator!='undefined'&&(!c_g||navigator.appVersion.indexOf('MSIE 6')== -1)&&navigator.userAgent.indexOf('Firefox/2')<0;var c_j=c_a.subclass(function(){var c_k=this;c_k.eventStartPos=c_k.c_l=[0,0];c_k.eventPos=c_k.c_m=[0,0];c_k.c_n=[0,0];c_k.c_o=c_k.c_p=0;c_k.eventDeltaPos=c_k.c_q=[0,0];}),c_r=c_j.prototype;c_r.c_s=function(){this.c_t=null;this.fire('Drag Rest');};c_r.c_u=function(){this.c_t&&clearTimeout(this.c_t);this.c_t=null;};c_r.c_v=function(){var c_k=this;if(c_k.isWired){var c_w=c_k.getNode();c_k.c_x?c_e.setStyle(c_k.c_y?[c_w,c_h]:c_w,{cursor:c_k.get('enabledInherited')?c_k.c_x:'not-allowed'}):c_k.set({c_x:c_e.getStyle(c_w,'cursor')});}};c_r.initiate=c_r.mousedown=function(c_z,c_A){var c_k=this,c_l=c_k.c_l,c_m=c_k.c_m,c_n=c_k.c_n;function c_B(c_z){if(c_k.c_y){if(c_k.c_C){c_k.c_C.stop();c_k.c_C=c_b;}c_D=c_c;
if(c_k.c_t){c_k.c_u();c_k.c_s();}c_k.set({c_E:c_d,c_y:c_d,c_F:c_d,c_G:c_d});c_k.fire({name:'Drag Done',domEvent:c_z});c_k.set({c_H:c_d,c_I:c_d});if(c_G){c_k.unwireNode(c_A?'':c_z.target,{touchmove:null,touchend:null,touchcancel:null});}}}function c_J(c_K,c_L,c_M,c_N){c_k.set(c_K,c_c);(c_k.c_C=Uize.Fade.fade(c_O,[c_m[0],c_m[1]],c_L,c_M,c_N)).wire('Done',function(){c_B(c_z)});}function c_P(c_z){if(c_k.c_Q&&Uize.Fade&&Uize.Fade.fade){var c_R=c_m[0]-c_n[0],c_S=c_m[1]-c_n[1];if(c_R||c_S){var c_T=Math.sqrt(Math.pow(c_R,2)+Math.pow(c_S,2)),c_U=c_k.c_Q(c_T/((c_k.c_o-c_k.c_p)||1)*1000),c_V=1+(c_U.distance/c_T);c_J('inReleaseTravel',[c_n[0]+c_R*c_V,c_n[1]+c_S*c_V],c_U.duration*1000,{curve:c_U.curve});return;}}c_B(c_z);}function c_O(c_W,c_X){c_k.c_p=c_k.c_o;c_k.c_o= +new Date;c_n[0]=c_m[0];c_n[1]=c_m[1];var c_q=[(c_m[0]=c_W)-c_l[0],(c_m[1]=c_X)-c_l[1]],c_Y=[Math.abs(c_q[0]),Math.abs(c_q[1])];for(var c_Z= -1;++c_Z<2;)c_k.c_q[c_Z]=(c_k.c_0=='both'||c_Y[c_Z]>c_Y[1-c_Z]||(c_Y[c_Z]==c_Y[1-c_Z]&&c_Z==1))?c_q[c_Z]:0;
c_k.fire('Drag Update');c_k.c_u();c_k.c_t=setTimeout(function(){c_k.c_s()},c_k.c_1);}function c_2(c_z){if(!c_D&& !c_k.c_H){if(!c_k.c_I){if(!c_G){c_j.resizeShield(c_h);c_e.display(c_h);}c_k.set({c_I:c_c});c_k.fire({name:'Drag Start',domEvent:c_z});}var c_3=c_f(c_z);c_O(c_3.left,c_3.top);}}function c_4(c_z){c_k.set({c_H:c_c});if(c_k.c_5&&Uize.Fade&&Uize.Fade.fade){c_J('inCancel',c_l,500,c_k.c_5);}else{c_O(c_l[0],c_l[1]);c_B(c_z);}}if(c_k.c_E||c_k.c_F)c_B(c_z);if(!c_k.c_y&&c_k.get('enabledInherited')){var c_G= !!c_z.targetTouches;c_k.set({c_y:c_c,c_G:c_G});c_k.c_v();Uize.Node.Event.abort(c_z);c_k.c_0=c_z.shiftKey?'one':'both';c_k.fire({name:'Before Drag Start',domEvent:c_z});var c_3=c_f(c_z);c_l[0]=c_m[0]=c_n[0]=c_3.left;c_l[1]=c_m[1]=c_n[1]=c_3.top;c_k.c_o=c_k.c_p= +new Date;var c_D=c_d,c_6;if(!c_G)c_6={onkeyup:document.onkeyup,onmousemove:document.onmousemove,onmouseup:document.onmouseup};if(c_G){c_k.wireNode(c_A?'':c_z.target,{touchmove:function(c_z){c_z.preventDefault();c_2(c_z);},touchend:function(c_z){
c_z.preventDefault();c_P(c_z);},touchcancel:function(c_z){c_z.preventDefault();c_4(c_z);}});}else{function c_7(c_z){Uize.copyInto(document,c_6);c_e.display(c_h,c_d);c_k.c_H||c_P(c_z);}document.onmousemove=function(c_z){c_z||(c_z=window.event);c_g&&c_z.button==0?c_k.c_y&&c_7(c_z):c_2(c_z);return c_d;};document.onmouseup=function(c_z){c_7(c_z||window.event);return c_d;};document.onkeyup=function(c_z){Uize.Node.Event.isKeyEscape(c_z)&&c_k.c_y&&c_4(c_z);};}}return c_d;};c_r.updateUi=function(){var c_k=this;c_k.isWired&& !c_k.get('enabledInherited')||c_k.c_x&&c_k.c_v();};c_r.wireUi=function(){var c_k=this;if(!c_k.isWired){var c_8=c_k.getNode();if(c_8){c_8.onmousedown=c_e.returnFalse;function c_9(c_z){return c_k.initiate(c_z,c_c)}c_k.wireNode(c_8,{mousedown:c_9,touchstart:c_9});}if(!c_h){c_h=c_j.insertShield({zIndex:50000});c_i||c_e.wire(window,'resize',function(){c_j.resizeShield(c_h)});}c_k.wire({'Changed.enabledInherited':function(){c_k.c_v()}});c_a.prototype.wireUi.call(c_k);}};c_j.insertShield=function(c_ba){
var c_bb={display:'none',position:'absolute'};if(c_g)c_bb.background='url('+c_j.getBlankImageUrl()+')';var c_bc=document.createElement('div');c_e.setStyle(c_bc,Uize.copyInto(c_bb,c_ba));c_bc.Uize_Widget_Drag_shield=c_c;document.body.appendChild(c_bc);c_j.resizeShield(c_bc);return c_bc;};c_j.resizeShield=function(c_bc){if(c_i){c_e.setStyle(c_bc,{left:'0',top:'0',width:'100%',height:'100%',position:'fixed'});}else{var c_bd=c_e.getStyle(c_bc,'display'),c_be=document.documentElement,c_bf=document.body;c_e.display(c_bc,c_d);c_e.setStyle(c_bc,{left:0,top:0,width:c_be.scrollWidth,height:Math.max(typeof window.innerHeight=='number'?window.innerHeight:(c_be&&c_be.clientHeight?c_be.clientHeight:(c_bf&&c_bf.clientHeight?c_bf.clientHeight:0)),c_be.scrollHeight),display:c_bd});}};c_j.registerProperties({c_bg:{name:'animation',onChange:function(){this.set({c_5:this.c_bg?{duration:500}:c_b})}},c_5:'cancelFade',c_x:{name:'cursor',onChange:c_r.c_v},c_H:'dragCancelled',c_1:{name:'dragRestTime',value:250},c_I:'dragStarted',
c_E:'inCancel',c_y:'inDrag',c_F:'inReleaseTravel',c_G:'isTouch',c_Q:'releaseTravel'});return c_j;}});