/*
	UIZE JAVASCRIPT FRAMEWORK 2012-01-10

	http://www.uize.com/reference/Uize.Fx.html
	Available under MIT License or GNU General Public License -- http://www.uize.com/license.html
*/
Uize.module({name:'Uize.Fx',required:['Uize.Fade.xFactory','Uize.Node','Uize.Color'],builder:function(){var _a=function(){},_b;var _c=[],_d,_e={},_f=Uize.Node.isIe;function _g(_h){if((_d||(_d={}))[_h])return _d[_h];for(var _i=_c.length,_j;--_i> -1;){if(typeof(_j=_c[_i].test)=='string'?_h==_j:Uize.isFunction(_j)?_j(_h):_j.test(_h))return _d[_h]=_c[_i];}}var _k=_a.defineStylePropertiesProfile=function(_l){_c.push(_l);if(_d)_d=_b;};_a.fadeStyle=function(_m,_n,_o,_p,_q,_r){if(!(_m=Uize.Node.getById(_m)))return;var _h,_s={};for(_h in _n)_s[_h]=1;for(_h in _o)_s[_h]=1;var _t=[],_u={},_v={},_w={},_x;function _y(_z){var _A=_z&&_z[_h];return(_x(_A!=_b?_A:Uize.Node.getStyle(_m,_h)));}for(_h in _s){_t.push(_h);var _l=_g(_h);_x=_l.decoder;_u[_h]=_y(_n);_v[_h]=_y(_o);_w[_h]=_l.quantization;}var _B=_t.sort().join(),_C=_e[_B];if(!_e[_B]){var _D=['var nodeStyle = this.style;','if (!nodeStyle) return;'];for(_h in _s){var _l=_g(_h);_D.push('nodeStyle.'+(_l.remappedProperty||_h)+'='+_l.encoderExpression.replace('VALUE',
'style.'+_h)+';');}_C=_e[_B]=new Function('style',_D.join(''));}return Uize.Fade.fade({context:_m,handler:_C},_u,_v,_p,Uize.copyInto({quantization:_w},_q),_r);};_a.fadeStyleAcrossNodes=function(_E,_n,_o,_q){var _F={},_G={style:_F},_H=_a.fadeStyle(_G,_n,_o,0,_q,false),_I=_H.get('reverse');_H.set({progress:1});for(var _J= -1,_K=(_E=Uize.Node.find(_E)).length-1;++_J<=_K;){_K&&_H.set({progress:(_I?_K-_J:_J)/_K});Uize.copyInto(_E[_J].style,_F);}};_k({test:Uize.returnTrue,decoder:Uize.returnX,encoderExpression:'VALUE'});function _L(_M){return typeof _M=='number'?_M:parseInt(_M)||0;}_k({test:/(left|top|right|bottom|padding|margin|spacing|textIndent)/i,decoder:_L,encoderExpression:'VALUE+"px"',quantization:1});_k({test:/(fontSize|width|height)/i,decoder:_L,encoderExpression:'Math.max(VALUE,0)+"px"',quantization:1});_k({test:/color|^background$/i,decoder:function(_M){return Uize.Color.to(_M,'RGB array')},encoderExpression:'"Rgb("+VALUE.join(",")+")"',quantization:1});
var _N={left:'0%',right:'100%',top:'0%',bottom:'100%',center:'50%'};_k({test:'backgroundPosition',decoder:function(_M){if(_M){if(Uize.isArray(_M)&&_M.length==2)_M=_M[0]+' '+_M[1];if(typeof _M=='string'){_M=_M.replace(/left|right|top|bottom|center/gi,function(_O){return _N[_O]}).match(/(left|center|right|[\+\-]?\d+)(%|px)?\s+(top|center|bottom|[\+\-]?\d+)(%|px)?/);_M&&_M.shift();}}if(!_M)_M=[0,'px',0,'px'];return[parseInt(_M[0])||0,(_M[1]||'px')+' ',parseInt(_M[2])||0,(_M[3]||'px')+' '];},encoderExpression:'VALUE.join("")',quantization:1});var _P='(\\d+)\\s*(?:px)?\\s*,?\\s*',_Q=new RegExp(_P+_P+_P+_P,'i');_k({test:'clip',decoder:function(_M){Uize.isArray(_M)||((_M=_M.match(_Q))?_M.shift():(_M=[0,0,0,0]));return[parseInt(_M[0]),parseInt(_M[1]),parseInt(_M[2]),parseInt(_M[3])];},encoderExpression:'"rect("+VALUE.join("px,")+"px)"',quantization:1});_k({test:'opacity',remappedProperty:_f?'filter':'opacity',decoder:function(_M){return+_M},encoderExpression:_f?'"alpha(opacity="+Math.round(VALUE*100)+")"':'VALUE'});
return _a;}});