/*
	UIZE Web Site 2012-01-10

	http://www.uize.com/reference/UizeDotCom.Page.Doc.html
	Available under MIT License or GNU General Public License -- http://www.uize.com/license.html
*/
Uize.module({name:'UizeDotCom.Page.Doc',required:['Uize.Node','Uize.Node.Tree','Uize.Widget.Tree.List','Uize.Url'],builder:function(e_a){var e_b=e_a.subclass(null,function(){var e_c=this;e_c.addChild('contents',Uize.Widget.Tree.List,{levelClasses:['contents-tree-level1','contents-tree-level2','contents-tree-level3','contents-tree-level4'],iconTheme:'arrows-black',iconBgColor:'',tooltip:'contentsTooltip',built:false});}),e_d=e_b.prototype;function e_e(e_f){function e_g(e_h){var e_i=e_h.indexOf('#');return e_i> -1?e_h.slice(0,e_i):e_h;}var e_j=e_f.getAttribute('href');return((e_j.charCodeAt(0)==35||(e_j.indexOf('#')> -1&&e_g(e_j)==e_g(location.href)))?e_j.slice(e_j.indexOf('#')+1):'');}e_d.wireUi=function(){var e_c=this;if(!e_c.isWired){var e_k=e_c.children.contents,e_l=Uize.Node.Tree.getTreeFromList(e_k.getNode());e_c.set({contentsTreeItems:e_l});e_k.set({items:e_l});e_k.setExpandedDepth(1);Uize.Node.injectHtml(document.body,'<div id="contentsTooltip" class="contents-tooltip"></div>'+
'<div id="bodyLinkTooltip" class="body-link-tooltip">'+'<div id="bodyLinkTooltipTitle" class="body-link-tooltip-title"></div>'+'<div id="bodyLinkTooltipDescription" class="body-link-tooltip-description"></div>'+'<div class="body-link-tooltip-more">MORE...</div>'+'</div>');var e_m=document.title.match(/^\s*(.*?)\s*\|/)[1];e_c.wireNode('search','click',function(){location.href=e_c.getPathToRoot()+'search-sections.html?'+e_m;});e_c.wireNode('examples','click',function(){e_c.performSearch('"'+e_m+'"','/examples')});e_c.wireNode('test','click',function(){location.href=Uize.Url.resolve(e_c.getPathToRoot()+'examples/uize-unit-tests.html',{runtest:Uize.Url.from(location.href).fileName.replace(/^Uize\.Test\./,'')});});var e_n=Uize.Node.find({tagName:'h1',className:'document-title'})[0];Uize.Node.getStyle(e_n,'position')=='fixed'&&e_c.wireNode(document.body,'click',function(e_o){var e_p=e_o.target||e_o.srcElement;e_p.tagName=='A'&&e_e(e_p)&&setTimeout(function(){
var e_q=Uize.Node.isSafari?document.body:document.documentElement;e_q.scrollTop&&(e_q.scrollTop-=48);},100);});var e_r=Uize.Node.find({root:Uize.Node.find({className:'contents0'})[0],tagName:'A',href:/.+/}),e_s=0;function e_t(){var e_u=e_r.length-1;if(e_s<=e_u){for(var e_v=Math.min(e_u,e_s+19);e_s<=e_v;e_s++)Uize.Node.wire(e_r[e_s],{onmouseover:function(){var e_w=e_e(this),e_x,e_y;if(e_w){var e_z=[0];e_w.replace(/\d+/g,function(e_A){e_z.push(e_A-1)});var e_B=e_k.getItemInfoFromSpecifier(e_z);if(e_B&&e_B.item){e_x=e_B.titleParts.slice(1).join(' ... ');e_y=e_B.item.description||'';}}else{var e_j=this.getAttribute('href'),e_C=Uize.Url.from(e_j);if(e_C.protocol=='http:'&&e_C.host.indexOf('uize.com')== -1){e_x='LINK TO EXTERNAL SITE';e_y=e_j;}}if(e_x&&e_y){Uize.Node.setValue('bodyLinkTooltipTitle',e_x);Uize.Node.setValue('bodyLinkTooltipDescription',e_y);Uize.Tooltip.showTooltip('bodyLinkTooltip');}},onmouseout:function(){Uize.Tooltip.showTooltip('bodyLinkTooltip',false);}});setTimeout(e_t,0);}}e_t();
e_a.prototype.wireUi.call(e_c);e_k.setNodeStyle('',{maxHeight:'none',overflow:'visible'});}};return e_b;}});