/*
	UIZE JAVASCRIPT FRAMEWORK 2012-08-18

	http://www.uize.com/reference/Uize.Class.html
	Available under MIT License or GNU General Public License -- http://www.uize.com/license.html
*/
Uize.module({name:'Uize.Class',builder:function(a_a){var a_b,a_c='string',a_d='object',a_e=Uize,a_f=a_e.clone,a_g=a_e.copyInto,a_h=a_e.forEach,a_i=a_e.getClass,a_j=a_e.getGuid,a_k=a_e.globalEval,a_l=a_e.isArray,a_m=a_e.isFunction,a_n=a_e.isInstance,a_o=a_e.isObject,a_p=a_e.noNew,a_q=a_e.pairUp;var a_r=[],a_s={};var a_t=a_u(function(){},function(){this.instanceId=a_j();},function(a_v){a_v||(a_v=a_s);var a_w={},a_x=this.Class.a_x,a_y,a_z;for(a_y in a_x){if(a_y in a_v)a_w[a_y]=a_v[a_y];else if((a_z=a_x[a_y])!==a_b)a_w[a_y]=a_z;}for(a_y in a_v)a_y in a_w||(a_w[a_y]=a_v[a_y]);this.set(a_w);}),a_A=a_t.prototype,a_B=a_t.nonInheritableStatics;function a_C(a_D,a_E){var a_t=a_i(a_D);return(a_t.a_F[a_E]||a_t.a_G[a_E]);}function a_H(a_D,a_E){var a_I=a_C(a_D,a_E);return a_I?a_I.a_J:a_E;}a_t.a_K=a_A.a_K=function(a_L,a_M){if(a_L.charCodeAt(0)==67&& !a_L.indexOf('Changed.')){var a_D=this,a_N=a_L.slice(8),a_I=a_C(a_D,a_N);if(a_I&&a_N!=a_I.a_O)a_L='Changed.'+(a_N=a_I.a_O);a_M(a_L);(a_D.a_P||(a_D.a_P={}))[a_N]=
a_D.a_Q&&a_D.a_Q[a_L];}else{a_M(a_L);}};a_t.wire=a_A.wire=function(a_R,a_S){var a_D=this;if(arguments.length==2){a_D.a_K(a_R,function(a_L){var a_Q=a_D.a_Q||(a_D.a_Q={});(a_Q[a_L]||(a_Q[a_L]=[])).push({a_L:a_L,a_S:a_m(a_S)?a_S:typeof a_S==a_c?new Function(a_S):function(a_T){a_S.fire(a_T)},a_U:a_S});});}else if(a_o(a_R)){for(var a_L in a_R)this.wire(a_L,a_R[a_L]);}};a_t.fire=a_A.fire=function(a_T){if(typeof a_T!=a_d)a_T={name:a_T};var a_D=this,a_Q=a_D.a_Q;if(a_Q){var a_V=a_Q[a_T.name],a_W=a_Q['*'];if(a_V||a_W){a_T.source||(a_T.source=a_D);var a_X=a_W&&a_V?a_W.concat(a_V):a_W||a_V,a_Y=a_X.length;if(a_Y==1){a_X[0].a_S(a_T);}else if(a_Y==2){var a_Z=a_X[0].a_S,a_0=a_X[1].a_S;a_Z(a_T);a_0(a_T);}else{if(!a_W|| !a_V)a_X=a_X.concat();for(var a_1= -1;++a_1<a_Y;)a_X[a_1].a_S(a_T);}}}if(a_T.bubble&&a_D.parent&&a_n(a_D)){a_T.source||(a_T.source=a_D);a_D.parent.fire(a_T);}return a_T;};a_t.unwire=a_A.unwire=function(a_R,a_S){var a_D=this,a_Q=a_D.a_Q;if(a_Q){if(a_o(a_R)){for(var a_L in a_R)a_D.unwire(a_L,a_R[a_L]);}else{
a_D.a_K(a_R,function(a_L){var a_2=a_Q[a_L];if(a_2){if(a_S){for(var a_1=a_2.length;--a_1>=0;)a_2[a_1].a_U==a_S&&a_2.splice(a_1,1);}(a_S&&a_2.length)||delete a_Q[a_L];}});}}};a_A.once=function(a_y,a_S){var a_3={};if(a_S){var a_4=a_y.charCodeAt(0)==33;if(a_4)a_y=a_y.slice(1);var a_D=this,a_5=a_D.get(a_y);if(!a_5==a_4){a_S(a_5);}else{a_3['Changed.'+a_y]=function(){if(!(a_5=a_D.get(a_y))==a_4){a_D.unwire(a_3);a_S(a_5);}};a_D.wire(a_3);}}return a_3;};a_A.is=function(a_y){return!!this[a_H(this,a_y)];};a_A.met=function(a_6){this.set(a_6,true);};a_A.unmet=function(a_6){this.set(a_6,false);};a_t.get=a_A.get=function(a_y){if(typeof a_y==a_c){return this[a_H(this,a_y)];}else{var a_D=this,a_7={};if(!a_y){var a_t=a_i(a_D),a_G=a_t.a_G;for(var a_8 in a_G)a_7[a_G[a_8].a_O]=a_D[a_8];}else if(a_l(a_y)){for(var a_9= -1,a_ba=a_y.length;++a_9<a_ba;){var a_bb=a_y[a_9];a_7[a_bb]=a_D[a_H(a_D,a_bb)];}}else{for(var a_bb in a_y)a_7[a_bb]=a_D[a_H(a_D,a_bb)];}return a_7;}};a_t.registerProperties=function(a_bc){var a_D=this,a_G=a_D.a_G,
a_F=a_D.a_F;for(var a_8 in a_bc){var a_bd=a_bc[a_8],a_be=a_o(a_bd),a_N=(a_be?a_bd.name:a_bd)||a_8,a_bf=a_N,a_I=a_G[a_8]={a_J:a_8};if(a_N.indexOf('|')> -1){var a_bg=a_N.split('|');a_bf=a_bg[0];a_e.lookup(a_bg,a_I,a_F);}else{a_F[a_N]=a_I;}a_I.a_O=a_bf;if(a_be){if(a_bd.onChange)a_I.a_bh=a_bd.onChange;if(a_bd.conformer)a_I.a_bi=a_bd.conformer;a_D[a_8]=a_bd.value;}}a_D.a_x=this.get();};a_t.set=a_A.set=function(a_v){var a_bj=arguments,a_bk=a_bj.length;if(a_bk>1)a_v=a_bk>2||typeof a_v==a_c?a_q.apply(0,a_bj):a_e.lookup(a_v,a_bj[1]);var a_D=this,a_bl=a_n(a_D),a_t=a_bl?a_D.Class:a_D,a_F=a_t.a_F,a_G=a_t.a_G,a_I,a_bm,a_bn,a_bo,a_P=a_bl&&a_D.a_P,a_bp=a_P&&a_P['*'],a_bq,a_br,a_8,a_N,a_bs,a_5,a_bt;for(var a_E in a_v){a_5=a_v[a_E];if(a_I=a_F[a_E]||a_G[a_E]){a_8=a_I.a_J;a_N=a_I.a_O;}else{(a_bs||(a_bs={}))[a_8=a_N=a_E]=a_I=a_bl?{}:{value:a_5};}if(a_bl)(a_bt||(a_bt={}))[a_N]=a_I.a_bi?(a_5=a_I.a_bi.call(a_D,a_5,a_D[a_8])):a_5;if(a_5!==a_D[a_8]){if(a_bl){a_bp&&((a_bq||(a_bq={}))[a_N]=a_5);a_P&&a_P[a_N]&&
(a_br||(a_br=[])).push(a_N);function a_bu(a_bo){if(a_m(a_bo)){if(!a_bm){a_bm=[];a_bn=a_D.instanceId+'_handlerAlreadyAdded';}if(!a_bo[a_bn]){a_bo[a_bn]=1;a_bm.push(a_bo);}}else if(typeof a_bo==a_c){a_bu(a_D[a_bo]);}else if(a_l(a_bo)){a_h(a_bo,a_bu);}}a_I.a_bh&&a_bu(a_I.a_bh);}a_D[a_8]=a_5;}}a_bs&&a_t.registerProperties(a_bs);if(a_bl){if(a_bm){for(var a_1= -1,a_bv=a_bm.length;++a_1<a_bv;){delete(a_bo=a_bm[a_1])[a_bn];a_bo.call(a_D,a_bt);}}a_bq&&a_D.fire({name:'Changed.*',properties:a_bq});if(a_br){for(var a_bw= -1,a_bx=a_br.length;++a_bw<a_bx;)a_D.fire('Changed.'+a_br[a_bw]);}}else{a_t.a_x=this.get();}};a_t.toggle=a_A.toggle=function(a_by){var a_bz= !this.get(a_by);this.set(a_by,a_bz);return a_bz;};a_A.kill=function(){var a_bA=this.instanceId;a_k('if(typeof '+a_bA+'!=\'undefined\')'+a_bA+'=null');};function a_u(a_t,a_bB,a_bC){function a_bD(){var a_bE=[],a_bF=a_e.toString;a_h(this.get(),function(a_5,a_by){a_bE.push(a_by+' : '+(a_5&&(a_n(a_5)||a_m(a_5))?a_bF.call(a_5):a_5));});
return a_bF.call(this)+'\n\n'+a_bE.sort().join('\n');}function a_bG(){return this[a_H(this,'value')];}var a_A=a_t.prototype,a_bH=a_p(function(){for(var a_bI= -1,a_bJ=a_bK.length;++a_bI<a_bJ;)a_bK[a_bI].apply(this,arguments);for(var a_bL= -1,a_bM=a_bN.length;++a_bL<a_bM;)a_bN[a_bL].apply(this,arguments);}),a_bO=a_bH.prototype;var a_5,a_bP=a_t.nonInheritableStatics||a_s;for(var a_y in a_t)if(!a_bP[a_y]&&(a_5=a_t[a_y])!=a_A&& !(a_m(a_5)&&a_5.moduleName&&/[A-Z]/.test(a_y.charAt(0))))a_bH[a_y]=a_f(a_5);a_g(a_bO,a_A);a_bO.toString=a_bD;a_bO.valueOf=a_bG;a_bO.Class=a_bH;a_bH.nonInheritableStatics={a_bQ:1,nonInheritableStatics:1,toString:0,valueOf:0};a_bH.superclass=a_t;a_bH.toString=a_bD;a_bH.valueOf=a_bG;var a_bK=a_bH.a_bK=(a_t.a_bK||a_r).concat(),a_bN=a_bH.a_bN=(a_t.a_bN||a_r).concat();a_bB&&a_bK.push(a_bB);a_bC&&a_bN.push(a_bC);a_bH.a_G||(a_bH.a_G={});a_bH.a_F||(a_bH.a_F={});return a_bH;};a_t.subclass=function(a_bB,a_bC){return a_u(this,a_bB,a_bC);};a_t.singleton=function(a_bR,a_v){var
 a_bQ=this.a_bQ||(this.a_bQ={}),a_bS=a_bQ[a_bR||(a_bR='')];a_bS?a_v&&a_bS.set(a_v):(a_bS=a_bQ[a_bR]=this(a_v));return a_bS;};return a_t;}});