/*
	UIZE JAVASCRIPT FRAMEWORK 2011-04-01

	http://www.uize.com/reference/Uize.Widget.Collection.Dynamic.html
	Available under MIT License or GNU General Public License -- http://www.uize.com/license.html
*/
Uize.module({name:'Uize.Widget.Collection.Dynamic',required:['Uize.Node','Uize.Widget.Drag','Uize.Tooltip'],builder:function(d_a){var d_b=true,d_c=false,d_d=null,d_e=Uize.Node,d_f=Uize.Tooltip;var d_g=d_a.subclass(d_d,function(){var d_h=this;var d_i,d_j,d_k,d_l,d_m,d_n,d_o,d_p,d_q,d_r,d_s,d_t,d_u,d_v,d_w,d_x,d_y,d_z=d_h.addChild('drag',Uize.Widget.Drag,{nodeMap:{'':d_d}});function d_A(d_B){var d_C=d_B?d_h.d_D:1,d_E=d_h.getNode('tooltipDragging');for(var d_F=d_l;--d_F> -1;)d_k[d_F].setNodeOpacity('',d_C);d_B&&d_e.setInnerHtml(d_E,d_h.localize('draggingToReorder'+(d_l>1?'Plural':'Singular'),{totalItems:d_l}));d_f.showTooltip(d_E,d_B,d_b);}d_z.wire({'Drag Start':function(){d_j=d_h.d_G=='reverse'?1:0;d_i.set({over:d_c});var d_H=d_i.get('selected');if(!d_H){d_h.selectAll(d_c);d_h.d_I&&d_i.set({selected:d_b});}if(!d_h.d_J){if(d_H){for(var d_K= -1,d_L=d_h.getSelected(),d_M=d_L.length;++d_K<d_M;)d_L[d_K].get('locked')&&d_L[d_K].set({selected:d_c});d_h.get('totalSelected')||d_z.set({dragCancelled:d_b});}
else if(d_i.get('locked'))d_z.set({dragCancelled:d_b});}d_k=d_H?d_h.getSelected():[d_i];d_l=d_k.length;d_m=[];d_h.forAll(function(d_N){d_m.push(d_e.getCoords(d_N.getNode()));});var d_O=d_m.length,d_P=d_O-1,d_Q=d_m[d_j?d_P:0],d_R=d_m[d_j?d_P-1:1];d_u=d_P&&d_R.top>d_Q.bottom?1:0;d_x=d_u?'top':'left';d_y=d_u?'height':'width';d_p=d_q=d_r=d_s=d_t=d_d;d_v=d_h.getNode('insertionMarker');d_w=d_e.getDimensions(d_v);for(var d_S= -1,d_T=d_P?d_R[d_x]-(d_Q[d_x]+d_Q[d_y]-1):0,d_U=d_T/2;++d_S<d_O;){var d_V=d_m[d_S];d_V[d_x]-=d_U;d_V[d_y]+=d_T;}d_A(d_b);},'Drag Update':function(d_W){var d_X=document.documentElement,d_Y=d_z.eventPos;d_f.positionTooltip(d_h.getNode('tooltipDragging'),{pageX:d_Y[0],pageY:d_Y[1]});function d_Z(d_0){return(d_0&&d_e.doRectanglesOverlap(d_0.left,d_0.top,d_0.width,d_0.height,d_Y[0],d_Y[1],1,1));}if(!d_Z(d_o)){d_n=d_o=d_d;d_h.forAll(function(d_N,d_S){var d_V=d_m[d_S];if(d_Z(d_V)){d_n=d_N;d_o=d_V;}return!d_n;});}if(!d_Z(d_r)){d_p=d_r=d_d;if(d_n&& !Uize.isIn(d_k,d_n)){var d_1=d_o[d_y],d_2=d_1/2,
d_3=d_o[d_x],d_4=d_3+d_2;d_p=d_n;d_q=d_Y[d_u]<d_4?0:1;d_r=Uize.clone(d_o);d_r[d_x]=d_q?d_4:d_3;d_r[d_y]=d_2;}}if(d_p!=d_s||d_q!=d_t){d_h.displayNode(d_v,!!d_p);if(d_p){var d_5=Uize.clone(d_r);d_5[d_x]+=(d_q?d_r[d_y]:0)-d_w[d_y]/2;delete d_5[d_y];d_e.setCoords(d_v,d_5);}d_s=d_p;d_t=d_q;}d_z.set({cursor:d_p||d_n?'move':'not-allowed'});},'Drag Done':function(d_W){if(d_z.get('dragStarted')){d_A(d_c);d_h.displayNode('insertionMarker',d_c);function d_6(){if(d_p&& !d_z.get('dragCancelled')){var d_7=d_h.itemWidgets;if(d_q^d_j){var d_8=d_7.length,d_9=Uize.indexIn(d_7,d_p)+1;d_p=d_d;while(d_9<d_8){var d_N=d_7[d_9];if(!Uize.isIn(d_k,d_N)){d_p=d_N;break;}else{d_9++;}}}for(var d_F= -1;++d_F<d_l;)d_h.move(d_k[d_F],d_p);d_h.fire('Items Reordered');d_h.d_ba();}}d_h.d_bb?d_h.confirm({state:'warning',title:d_h.localize('confirmDragToReorderTitle'),message:d_h.localize('confirmDragToReorderPrompt'),yesHandler:function(){d_h.d_bb=d_c;d_h.fire('Drag Confirmed');d_6();},noHandler:function(){d_z.set({dragCancelled:true});}}):d_6();
}}});d_h.wire('Item Mouse Down',function(d_W){if(d_h.d_bc){d_i=d_W.source;d_z.initiate(d_W.domEvent);}d_W.bubble=d_c;});}),d_bd=d_g.prototype;d_bd.d_be=function(d_bf){var d_h=this,d_bg=d_bf.properties,d_bh=d_h.makeItemWidgetName(d_bg);d_h.get('items').push(d_bg);return d_h.addItemWidget(d_bh,d_bf);};d_bd.d_ba=function(){this.fire('Items Changed')};var d_bi={selected:d_b};d_bd.add=function(d_bj){var d_h=this,d_bk=[];if(!Uize.isArray(d_bj))d_bj=[d_bj];var d_bl=d_bj.length;if(d_bl){d_h.d_bm&&d_h.selectAll(d_c);var d_bn=d_h.d_bm?d_bi:d_d;for(var d_bo= -1;++d_bo<d_bl;)d_bk.push(d_h.d_be(Uize.copyInto(d_bj[d_bo],d_bn)));}d_h.d_ba();return d_bk;};d_bd.getItemWidgetProperties=function(){var d_h=this;return(Uize.copyInto({previewTooltip:function(){return d_h.d_bc?d_h.getNode('tooltipDragToReorder'):d_d}},d_h.get('itemWidgetProperties')));};d_bd.move=function(d_bp,d_bq){var d_h=this,d_br=d_h.d_G=='reverse',d_bs=d_bq?d_bq.getNode():d_d,d_bt=d_h.get('items'),d_7=d_h.itemWidgets,d_bu=d_h.getNode('items'),
d_bv=d_bp.getNode(),d_bw=d_br?(d_bs?d_bs.nextSibling:d_bu.childNodes[0]):d_bs;d_bw?d_bu.insertBefore(d_bv,d_bw):d_bu.appendChild(d_bv);var d_bx=Uize.indexIn(d_7,d_bp),d_by=d_bt[d_bx];d_7.splice(d_bx,1);d_bt.splice(d_bx,1);var d_bz=d_bq?Uize.indexIn(d_7,d_bq):d_7.length-(d_br?0:1);d_7.splice(d_bz,0,d_bp);d_bt.splice(d_bz,0,d_by);};d_bd.wireUi=function(){var d_h=this;if(!d_h.isWired){var d_bA={},d_bB=d_h.getNode('itemTemplate');if(d_bB){var d_bC=d_bB.innerHTML;d_bA.html=Uize.Template&&d_bB.tagName=='SCRIPT'&&d_bB.type=='text/jst'?Uize.Template.compile(d_bC,{openerToken:'[%',closerToken:'%]'}):function(d_bD){return d_bC.replace(/ITEMWIDGETNAME/g,d_bD.name)};}d_bA.built=d_c;d_bA.container=d_h.getNode('items');d_bA.insertionMode=d_h.d_G=='reverse'?'inner top':'inner bottom';d_h.get('built')||d_h.forAll(function(d_N){d_N.set(d_bf)});d_h.set({itemWidgetProperties:Uize.copyInto(d_h.get('itemWidgetProperties')||{},d_bA)});d_a.prototype.wireUi.call(d_h);}};d_g.registerProperties({d_bb:{name:'confirmToDrag',value:d_c},
d_J:{name:'dragIgnoresLocked',value:d_b},d_bc:{name:'dragToReorder',value:d_c},d_I:{name:'ensureItemDraggedIsSelected',value:d_c},d_G:{name:'itemDisplayOrder',value:'normal'},d_bm:{name:'makeNewlyAddedSelected',value:d_b},d_D:{name:'itemVestigeOpacity',value:.2}});return d_g;}});