/*
	UIZE JAVASCRIPT FRAMEWORK 2012-01-10

	http://www.uize.com/reference/Uize.Widget.Form.html
	Available under MIT License or GNU General Public License -- http://www.uize.com/license.html
*/
Uize.module({name:'Uize.Widget.Form',required:['Uize.Widget.FormElements','Uize.Widget.FormElement','Uize.Widget.Committer','Uize.Widget.FormWarnings','Uize.Widget.Button','Uize.Node','Uize.Node.Event'],builder:function(c_a){var c_b=true,c_c=false,c_d=null,c_e,c_f=Uize,c_g=c_f.Widget,c_h='never',c_i='valueChanged',c_j='validated',c_k='finished',c_l='validatedAfterFirstFinish';var c_m=c_a.subclass(function(){this.isForm=this.c_n=c_b;},function(){var c_o=this,c_p=c_o.addChild('committer',c_g.Committer,{watchedProperties:{}}),c_q=c_o.addChild('formWarnings',c_g.FormWarnings,{watchedElements:[]}),c_r=c_o.addChild('elements',c_g.FormElements),c_e;c_o.c_r=c_r;c_o.c_p=c_p;c_o.c_q=c_q;c_r.wire('Element Added',function(c_s){var c_t=c_s.element;c_t.wire({'Changed.isDirtyInherited':function(){c_t.get('isDirtyInherited')&&c_o.set({c_u:c_b})},Ok:function(){c_o.c_v()},'Changed.focused':function(){!c_t.get('focused')&&c_o.c_w(function(c_x,c_y,c_z){if(!c_z){var c_A=c_x.getNodeValue('input');c_A!==c_e&&c_x.valueOf()!=c_A
&&c_x.set({value:c_A});}});}});c_t.isForm&&c_t.set({c_B:c_c});c_q.addWatchedElements(c_t);c_p.addWatchedProperties([{alias:c_t.get('name'),instance:c_t,name:'value'}]);});function c_C(){c_o.c_C()}c_p.wire({'Changed.committedValues':c_C,'Changed.uncommittedValues':c_C,'Changed.allValid':function(){c_o.c_D()}});Uize.Widget.Button.addChildButton.call(c_o,'submit',function(){c_o.c_v()});c_o.c_E=c_b;}),c_F=c_m.prototype;c_F.c_G=function(c_y,c_H,c_I){return this.c_r.addChild(c_y,c_H,c_I)};c_F.c_w=function(c_J){if(this.c_r){var c_r=this.c_r.children;for(var c_y in c_r){var c_x=c_r[c_y];c_J(c_x,c_x.get('name'),c_x.isForm);}}};c_F.c_K=function(){var c_L=this.parent,c_M;if(c_L&&c_L.parent){c_M=c_L.parent;if(!c_M.isForm)c_M=c_d;}return c_M;};c_F.c_N=function(c_O){var c_o=this;c_o.set({c_P:c_c,c_Q:c_c,c_u:'inherit'});c_o.c_w(function(c_x){c_x.restore()});c_o.c_p[c_O]();};c_F.c_v=function(){this.set({c_u:c_b,c_R:c_b,c_Q:!this.c_S})};c_F.c_T=function(){var c_o=this;c_o.set({c_S:c_o.c_Q&&c_o.c_U});};c_F.c_V=function(){
var c_o=this;if(c_o.isWired){c_o.setNodeProperties('form',{action:c_o.c_W,enctype:c_o.c_X,method:c_o.c_Y,target:c_o.c_Z});}};c_F.c_C=function(){var c_o=this,c_p=c_o.c_p;c_o.set({c_0:Uize.copyInto({},c_o.c_0,c_p.get('committedValues'),c_p.get('uncommittedValues'))});};c_F.c_1=function(){var c_o=this,c_q=c_o.c_q,c_2=c_o.c_2;if(c_o.isWired){if(c_q){c_2&&c_o.isWired&&c_o.displayNode('serverWarnings',c_c);c_q.set({shown:c_2});}}};c_F.addForm=function(c_3,c_4,c_5){return this.c_G(c_3,c_4||c_g.Form,c_5)};c_F.addFormElement=function(c_6,c_7,c_8){return this.c_G(c_6,c_7||c_g.FormElement,c_8)};c_F.checkIsEmpty=function(){var c_r=this.c_r.children,c_9=c_b;for(var c_y in c_r){if(!c_r[c_y].get('isEmpty')){c_9=c_c;break;}}return c_9;};c_F.checkWarningShown=c_F.c_ba=function(){var c_o=this,c_bb=c_o.c_bb,c_M=c_o.c_K(),c_bc=c_o.c_2;c_o.set({c_2:c_o.c_bd&&c_o.c_U==c_c&&(c_M?c_M.get('warningShown'):(c_o.c_be&&(c_bb==c_j||(c_bb==c_k&&(c_o.c_R||c_bc))||(c_bb==c_l&&(c_o.c_P||c_bc)))))});};
c_F.clear=function(){this.c_N('clearAll')};c_F.getFormElement=function(c_y){return this.c_r.children[c_y]};c_F.reset=function(){this.c_N('restoreInitial')};c_F.submit=c_F.c_v;c_F.updateUi=function(){var c_o=this;if(c_o.isWired){c_o.c_V();c_o.c_1();c_o.c_w(function(c_x){c_x.updateUi()});c_a.prototype.updateUi.call(c_o);}};c_F.validate=c_F.c_D=function(){this.set({c_U:this.c_p.get('allValid')})};c_F.wireUi=function(){var c_o=this;if(!c_o.isWired){var c_bf=c_o.getNode('form');if(c_bf){function c_bg(c_bh){return c_bh==c_d;}if(c_bg(c_o.c_W))c_o.c_W=c_bf.action;if(c_bg(c_o.c_X))c_o.c_X=c_bf.enctype;if(c_bg(c_o.c_Y))c_o.c_Y=c_bf.method;if(c_bg(c_o.c_Z))c_o.c_Z=c_bf.target;c_o.wireNode(c_bf,'submit',function(c_s){Uize.Node.Event.preventDefault(c_s);c_o.c_v();});}c_a.prototype.wireUi.call(c_o);c_o.c_C();c_o.c_D();}};c_m.registerProperties({c_W:{name:'action',onChange:c_F.c_V},c_X:{name:'enctype',onChange:c_F.c_V},c_9:{name:'isEmpty',value:c_b},c_u:{name:'isDirty',onChange:function(){var c_o=this,c_M=c_o.c_K(),
c_u=c_o.c_u=='inherit'?(c_M?c_M.get('isDirtyInherited'):c_c):c_o.c_u;c_o.set({c_be:c_u});},value:'inherit'},c_be:{name:'isDirtyInherited',onChange:c_F.c_ba,value:c_c},c_R:{name:'isFinished',onChange:function(){var c_o=this;if(c_o.c_R){c_o.c_bi==c_k&&c_o.c_D();!c_o.c_P&&c_o.c_E&&c_o.set({c_P:c_b});}c_o.c_ba();},value:c_b},c_Q:{name:'isSubmitting',onChange:function(){var c_o=this;c_o.c_Q&&c_o.c_p&&c_o.c_p.commit();c_o.c_U==c_c&&c_o.set({c_Q:c_c});c_o.c_ba();c_o.c_T();},value:c_c},c_U:{name:'isValid',onChange:function(){var c_o=this;c_o.c_U==c_c&&c_o.set({c_Q:c_c});c_o.c_ba();c_o.c_T();},value:c_c},c_Y:{name:'method',onChange:c_F.c_V},c_S:{name:'okToSubmit',onChange:function(){var c_o=this;if(c_o.c_S&&c_o.c_B){var c_bf=c_o.getNode('form');c_bf&&c_bf.submit();}},value:c_c},c_Z:{name:'target',onChange:c_F.c_V},c_B:{name:'useNormalSubmit',value:c_b},c_bi:{name:'validateWhen',value:c_i},c_0:{name:'value',onChange:function(){var c_o=this,c_r=c_o.c_r.children,c_0=c_o.c_0||{};for(var c_bj in c_0){var c_x=c_r[c_bj];c_x
&&c_x.set({value:c_0[c_bj]});}c_o.set({c_R:c_c,c_9:c_o.checkIsEmpty()});c_o.c_bi==c_i&&c_o.c_D();}},c_bk:{name:'warningAllowed',onChange:function(){var c_o=this,c_M=c_o.c_K(),c_bk=c_o.c_bk=='inherit'?(c_M?c_M.get('allowWarningsInherited'):c_b):c_o.c_bk;c_o.set({c_bd:c_bk});},value:'inherit'},c_bd:{name:'warningAllowedInherited',onChange:c_F.c_ba,value:c_c},c_2:{name:'warningShown',onChange:function(){var c_o=this;c_o.c_w(function(c_x){c_x.checkWarningShown()});c_o.c_1();},value:c_c},c_bb:{name:'warningShownWhen',onChange:c_F.c_ba,value:c_l},c_P:{onChange:c_F.c_ba,value:c_c}});return c_m;}});