/*
	UIZE JAVASCRIPT FRAMEWORK 2011-04-01

	http://www.uize.com/reference/Uize.Widget.Button.html
	Available under MIT License or GNU General Public License -- http://www.uize.com/license.html
*/
Uize.module({name:'Uize.Widget.Button',required:'Uize.Node',builder:function(c_a){var c_b,c_c=true,c_d=false,c_e=Uize.Node;var c_f=c_a.subclass(null,function(){var c_g=this;function c_h(){if(c_g.isWired){c_g.c_i()||c_g.set({c_j:''});c_g.c_h();}}c_g.wire({'Changed.busyInherited':c_h,'Changed.enabledInherited':c_h});}),c_k=c_f.prototype;var c_l,c_m={},c_n={grayed:16,'':8,over:4,active:2,playing:1},c_o='(Grayed|Over|Active|Playing)',c_p=new RegExp(c_o),c_q=new RegExp('(?:(?:(\\S+)\\s+\\1'+c_o+'))','g'),c_r=new RegExp('\\S*'+c_o+'\\b','g'),c_s=/\b(disabled|over|active|playing)\b/,c_t={},c_u={mouseover:['over','Over'],mouseout:['','Out'],mousedown:['down','Down'],mouseup:['over','Up'],click:['over','Click']};c_k.c_v=c_d;c_k.c_i=function(){var c_g=this;return!!(c_g.get('enabledInherited')&& !c_g.get('busyInherited')&&(!c_g.c_w||c_g.c_x||c_g.c_y));};c_k.c_z=function(){this.c_A!=c_b&&this.isWired&&this.setNodeInnerHtml('text',this.c_A);};var c_h=c_k.c_h=function(){var c_g=this;if(c_g.isWired){var c_B=c_g.c_B,
c_C=c_g.get('enabledInherited'),c_D=c_g.get('busyInherited'),c_E=(!c_C?16:0)|(!c_g.c_j||c_D?8:0)|(c_g==c_l?4:0)|(c_g.c_j=='down'||c_g.c_w?2:0)|(c_g.c_F?1:0),c_G=c_g.c_H[c_E];if(c_G==c_b){for(var c_I= -1,c_J=c_g.c_J,c_K=c_J.length;++c_I<c_K;){var c_L=c_J[c_I];if(c_E&c_n[c_L]){c_G=c_L;break;}}c_g.c_H[c_E]=c_G;}if(c_g.c_M=='classes'){var c_N=c_B.className,c_O='';if(c_g.c_P=='disambiguated'){var c_Q=c_g.c_Q;if(c_Q==c_b){var c_R=c_N.match(c_q);if(c_R){c_Q=c_R[c_R.length-1].split(' ',2)[0];}else{c_R=c_N.replace(c_r,'').match(/(\S+)\s*$/);if(c_R)c_Q=c_R[c_R.length-1];}if(c_g.c_Q=c_Q=c_Q||'')c_g.c_S=c_t[c_Q]||(c_t[c_Q]=new RegExp(c_Q+'(\\s+'+c_Q+c_o+')?'));}var c_T=c_G?' '+c_Q+Uize.capFirstChar(c_G):'';c_O=c_Q?c_N.replace(c_g.c_S,c_Q+c_T):c_N.replace(c_p,'')+c_T;}else{var c_U=c_G=='grayed'?'disabled':c_G;c_O=c_s.test(c_N)?c_N.replace(c_s,c_U):c_N+(c_U?' ':'')+c_U;}if(c_O!=c_N)c_B.className=c_O;}else if(c_g.c_M=='frames'){c_g.c_V.style.top='-'+(c_g.c_W.c_X[c_G]*c_g.c_Y.height)+'px';}if(c_g.c_Z&&Uize.Tooltip){
var c_0=c_g.c_j=='over'&&c_C&& !c_g.c_w;c_0!=c_g.c_v&&Uize.Tooltip.showTooltip(c_g.c_Z,c_g.c_v=c_0);}c_g.get('busyInherited')?c_e.setStyle(c_B,{cursor:'wait'}):c_e.showClickable(c_B,c_g.c_i());}};c_k.c_1=function(c_2){var c_g=this;if(c_g.isWired){var c_3=c_2.type,c_4=c_3=='click',c_i=c_g.c_i();if(!c_g.c_5){c_g.c_5=c_c;function c_1(c_2){c_g.c_1(c_2)}c_g.wireNode(c_g.c_B,{mouseout:c_1,mousedown:c_1,mouseup:c_1});}if(c_4)c_2.cancelBubble=c_c;if(c_i){var c_6=c_u[c_3];c_g.set({c_j:c_6[0]});c_g.fire({name:c_6[1],domEvent:c_2});c_4&&(c_g.c_w?c_g.c_x:c_g.c_7)&&c_g.set({c_w:!c_g.c_w});}}};c_k.updateUi=function(){this.c_h();this.c_z();};c_k.wireUi=function(){var c_g=this;if(!c_g.isWired){c_g.c_V=c_b;var c_B=c_g.c_B=c_g.getNode();if(c_B){var c_8=c_B.childNodes;if(c_8.length&&(c_8.length>1||c_8[0].nodeType!=3)&&(c_g.c_V=c_g.getNode('frames'))){c_g.c_M='frames';c_g.c_Y=c_e.getDimensions(c_g.c_V.parentNode);}if(c_g.c_9&&c_B.tagName=='A'&& !c_B.onclick)c_B.onclick=c_e.returnTrue;function c_1(c_2){c_g.c_1(c_2)}c_g.wireNode(
c_B,{mouseover:c_1,click:c_1});if(c_g.c_A==c_b){var c_ba=c_g.getNode('text');c_ba&&c_g.set({c_A:c_ba.innerHtml});}c_a.prototype.wireUi.call(c_g);}}};c_f.addChildButton=function(c_bb,c_bc){var c_g=this,c_bd;function c_be(){c_bd.wire('Click',function(c_bf){if(c_bc)typeof c_bc=='string'?c_g.fire(c_bc):c_bc(c_bf);c_g.fire(c_bf);});}if(c_g==c_f){c_bd=new c_f({idPrefix:c_bb,name:c_bb,c_9:c_c});c_be();(window[c_bd.instanceId]=c_bd).wireUi();}else{c_bd=c_g.children[c_bb];if(!c_bd){c_bd=c_g.addChild(c_bb,c_f);c_be();}}return c_bd;};c_f.registerProperties({c_y:{name:'allowClickWhenSelected',onChange:c_h},c_7:'clickToSelect',c_x:{name:'clickToDeselect',onChange:c_h},c_P:{name:'classNamingForStates',value:'disambiguated'},c_W:{name:'frameOrder',onChange:function(){var c_W=this.c_W;if(!c_W.c_X){for(var c_bg= -1,c_bh=c_W.length,c_X=c_W.c_X={};++c_bg<c_bh;)c_X[c_W[c_bg]]=c_bg;}},value:['grayed','','over','active','playing']},c_9:{name:'followLink',value:c_d},c_M:{name:'mode',value:'classes'},c_F:{name:'playing',
onChange:c_h,value:c_d},c_w:{name:'selected',onChange:c_h,value:c_d},c_j:{name:'state',onChange:function(){var c_g=this;if(!c_g.c_j){if(c_l==c_g)c_l=c_b;}else if(c_g.c_j=='over'){c_l&&c_l!=c_g&&c_l.set({c_j:''});c_l=c_g;}c_g.isWired&&c_g.c_h();},value:''},c_J:{name:'statePrecedence',onChange:function(){var c_g=this,c_bi=c_g.c_J.c_bj||(c_g.c_J.c_bj=c_g.c_J.join(','));c_g.c_H=c_m[c_bi]||(c_m[c_bi]={});c_g.isWired&&c_g.c_h();},value:['playing','active','grayed','over','']},c_A:{name:'text',onChange:c_k.c_z},c_Z:'tooltip'});return c_f;}});