/*
	UIZE JAVASCRIPT FRAMEWORK 2011-04-01

	http://www.uize.com/reference/Uize.Widget.Form.html
	Available under MIT License or GNU General Public License -- http://www.uize.com/license.html
*/
Uize.module({name:'Uize.Widget.Form',required:['Uize.Widget.FormElements','Uize.Widget.FormElement','Uize.Widget.Committer','Uize.Widget.FormWarnings','Uize.Widget.Button','Uize.Node','Uize.Node.Event'],builder:function(c_a){var c_b=true,c_c=false,c_d=null,c_e,c_f=Uize,c_g=c_f.Widget,c_h='never',c_i='valueChanged',c_j='validated',c_k='finished',c_l='validatedAfterFirstFinish';var c_m=c_a.subclass(function(){this.isForm=this.c_n=c_b;},function(){var c_o=this,c_p=c_o.addChild('committer',c_g.Committer,{watchedProperties:{}}),c_q=c_o.addChild('formWarnings',c_g.FormWarnings,{watchedElements:[]}),c_r=c_o.addChild('elements',c_g.FormElements);c_o.c_r=c_r;c_o.c_p=c_p;c_o.c_q=c_q;c_r.wire('Element Added',function(c_s){var c_t=c_s.element;c_t.wire({'Changed.isDirtyInherited':function(){c_t.get('isDirtyInherited')&&c_o.set({c_u:c_b})},Ok:function(){c_o.c_v()}});c_t.isForm&&c_t.set({c_w:c_c});c_q.addWatchedElements(c_t);c_p.addWatchedProperties([{alias:c_t.get('name'),instance:c_t,name:'value'}]);});
function c_x(){c_o.c_x()}c_p.wire({'Changed.committedValues':c_x,'Changed.uncommittedValues':c_x,'Changed.allValid':function(){c_o.c_y()}});Uize.Widget.Button.addChildButton.call(c_o,'submit',function(){c_o.c_v()});c_o.c_z=c_b;}),c_A=c_m.prototype;c_A.c_B=function(c_C,c_D,c_E){return this.c_r.addChild(c_C,c_D,c_E)};c_A.c_F=function(c_G){if(this.c_r){var c_r=this.c_r.children;for(var c_C in c_r){var c_H=c_r[c_C];c_G(c_H,c_H.get('name'),c_H.c_n);}}};c_A.c_I=function(){var c_J=this.parent,c_K;if(c_J&&c_J.parent){c_K=c_J.parent;if(!c_K.isForm)c_K=c_d;}return c_K;};c_A.c_L=function(c_M){var c_o=this;c_o.set({c_N:c_c,c_O:c_c,c_u:'inherit'});c_o.c_F(function(c_H){c_H.restore()});c_o.c_p[c_M]();};c_A.c_v=function(){this.set({c_u:c_b,c_P:c_b,c_O:!this.c_Q})};c_A.c_R=function(){var c_o=this;c_o.set({c_Q:c_o.c_O&&c_o.c_S});};c_A.c_T=function(){var c_o=this;if(c_o.isWired){c_o.setNodeProperties('form',{action:c_o.c_U,enctype:c_o.c_V,method:c_o.c_W,target:c_o.c_X});}};c_A.c_x=function(){var c_o=this,c_p=c_o.c_p;c_o.set({
c_Y:Uize.copyInto({},c_o.c_Y,c_p.get('committedValues'),c_p.get('uncommittedValues'))});};c_A.c_Z=function(){var c_o=this,c_q=c_o.c_q,c_0=c_o.c_0;if(c_o.isWired){if(c_q){c_0&&c_o.isWired&&c_o.displayNode('serverWarnings',c_c);c_q.set({shown:c_0});}}};c_A.addForm=function(c_1,c_2,c_3){return this.c_B(c_1,c_2||c_g.Form,c_3)};c_A.addFormElement=function(c_4,c_5,c_6){return this.c_B(c_4,c_5||c_g.FormElement,c_6)};c_A.checkIsEmpty=function(){var c_r=this.c_r.children,c_7=c_b;for(var c_C in c_r){if(!c_r[c_C].get('isEmpty')){c_7=c_c;break;}}return c_7;};c_A.checkWarningShown=c_A.c_8=function(){var c_o=this,c_9=c_o.c_9,c_K=c_o.c_I(),c_ba=c_o.c_0;c_o.set({c_0:c_o.c_bb&&c_o.c_S==c_c&&(c_K?c_K.get('warningShown'):(c_o.c_bc&&(c_9==c_j||(c_9==c_k&&(c_o.c_P||c_ba))||(c_9==c_l&&(c_o.c_N||c_ba)))))});};c_A.clear=function(){this.c_L('clearAll')};c_A.getFormElement=function(c_C){return this.c_r.children[c_C]};c_A.reset=function(){this.c_L('restoreInitial')};c_A.submit=c_A.c_v;c_A.updateUi=function(){var c_o=this;
if(c_o.isWired){c_o.c_T();c_o.c_Z();c_o.c_F(function(c_H){c_H.updateUi()});c_a.prototype.updateUi.call(c_o);}};c_A.validate=c_A.c_y=function(){this.set({c_S:this.c_p.get('allValid')})};c_A.wireUi=function(){var c_o=this;if(!c_o.isWired){var c_bd=c_o.getNode('form');if(c_bd){function c_be(c_bf){return c_bf==c_d;}if(c_be(c_o.c_U))c_o.c_U=c_bd.action;if(c_be(c_o.c_V))c_o.c_V=c_bd.enctype;if(c_be(c_o.c_W))c_o.c_W=c_bd.method;if(c_be(c_o.c_X))c_o.c_X=c_bd.target;c_o.wireNode(c_bd,'submit',function(c_s){Uize.Node.Event.preventDefault(c_s);c_o.c_v();});}c_a.prototype.wireUi.call(c_o);c_o.c_x();c_o.c_y();}};c_m.registerProperties({c_U:{name:'action',onChange:c_A.c_T},c_V:{name:'enctype',onChange:c_A.c_T},c_7:{name:'isEmpty',value:c_b},c_u:{name:'isDirty',onChange:function(){var c_o=this,c_K=c_o.c_I(),c_u=c_o.c_u=='inherit'?(c_K?c_K.get('isDirtyInherited'):c_c):c_o.c_u;c_o.set({c_bc:c_u});},value:'inherit'},c_bc:{name:'isDirtyInherited',onChange:c_A.c_8,value:c_c},c_P:{name:'isFinished',onChange:function(){
var c_o=this;if(c_o.c_P){c_o.c_bg==c_k&&c_o.c_y();!c_o.c_N&&c_o.c_z&&c_o.set({c_N:c_b});}c_o.c_8();},value:c_b},c_O:{name:'isSubmitting',onChange:function(){var c_o=this;c_o.c_O&&c_o.c_p&&c_o.c_p.commit();c_o.c_S==c_c&&c_o.set({c_O:c_c});c_o.c_8();c_o.c_R();},value:c_c},c_S:{name:'isValid',onChange:function(){var c_o=this;c_o.c_S==c_c&&c_o.set({c_O:c_c});c_o.c_8();c_o.c_R();},value:c_c},c_W:{name:'method',onChange:c_A.c_T},c_Q:{name:'okToSubmit',onChange:function(){var c_o=this;if(c_o.c_Q&&c_o.c_w){var c_bd=c_o.getNode('form');c_bd&&c_bd.submit();}},value:c_c},c_X:{name:'target',onChange:c_A.c_T},c_w:{name:'useNormalSubmit',value:c_b},c_bg:{name:'validateWhen',value:c_i},c_Y:{name:'value',onChange:function(){var c_o=this,c_r=c_o.c_r.children,c_Y=c_o.c_Y||{};for(var c_bh in c_Y){var c_H=c_r[c_bh];c_H&&c_H.set({value:c_Y[c_bh]});}c_o.set({c_P:c_c,c_7:c_o.checkIsEmpty()});c_o.c_bg==c_i&&c_o.c_y();}},c_bi:{name:'warningAllowed',onChange:function(){var c_o=this,c_K=c_o.c_I(),c_bi=c_o.c_bi=='inherit'
?(c_K?c_K.get('allowWarningsInherited'):c_b):c_o.c_bi;c_o.set({c_bb:c_bi});},value:'inherit'},c_bb:{name:'warningAllowedInherited',onChange:c_A.c_8,value:c_c},c_0:{name:'warningShown',onChange:function(){var c_o=this;c_o.c_F(function(c_H){c_H.checkWarningShown()});c_o.c_Z();},value:c_c},c_9:{name:'warningShownWhen',onChange:c_A.c_8,value:c_l},c_N:{onChange:c_A.c_8,value:c_c}});return c_m;}});