/*
	UIZE JAVASCRIPT FRAMEWORK 2011-04-21

	http://www.uize.com/reference/Uize.Widget.Page.html
	Available under MIT License or GNU General Public License -- http://www.uize.com/license.html
*/
Uize.module({name:'Uize.Widget.Page',required:'Uize.Node',builder:function(c_a){var c_b=true,c_c=false,c_d,c_e=Uize.Node;var c_f=c_a.subclass(null,function(){c_f.xDeferredLinks&&this.wireDeferredLinks()}),c_g=c_f.prototype;function c_h(c_i){return(Uize.isFunction(c_i)&&c_i)||c_i.callback||Object;}c_g.c_j=function(c_k,c_l,c_m){var c_n=this;c_n.useDialog({component:c_n.c_o.component,widgetClassName:c_n.c_o.widgetClassName||'Uize.Widget.Dialog.Confirm',widgetProperties:{name:'confirmDialog',title:c_m.title||'',message:(c_m.message+'').replace(/\n/g,'<br/>'),mode:c_k,state:c_m.state||c_l,okText:c_m.okText||null,cancelText:c_m.cancelText||null},submitHandler:function(c_p){var c_q=c_m.callback||(c_p?c_m.yesHandler:c_m.noHandler);c_q&&c_q(c_p);}});};c_g.c_r=function(c_s){c_s=c_s||Object;var c_n=this,c_t=c_n.get('idPrefix'),c_u='$'+c_t+'_',c_v=window;function c_w(c_x,c_y){var c_z,c_A;for(var c_B in c_y)(typeof(c_z=c_x[c_B])=='object'&&typeof(c_A=c_y[c_B])=='object'&&c_z&&c_A)?c_w(c_z,c_A):(c_x[c_B]=c_y[c_B]);}var
 c_C={},c_D=c_c,c_E=c_u.length,c_F;for(var c_B in c_v){if(c_B.charAt(0)=='$'&&c_B.substr(0,c_E)==c_u&&typeof(c_F=c_v[c_B])=='object'&&c_F&&c_F.widgetClass){c_D=c_b;for(var c_G= -1,c_H=c_C,c_I=c_B.substr(c_E).split('_'),c_J,c_K=c_I.length;++c_G<c_K;){var c_L=c_H[c_J=c_I[c_G]];if(c_G<c_K-1){c_H=(c_L||(c_L=c_H[c_J]={})).children||(c_L.children={});}else{c_L?c_w(c_L,c_F):(c_H[c_J]=c_F);c_v[c_B]=c_d;}}}}if(c_D){function c_M(c_N,c_O){function c_P(c_Q,c_R,c_S){var c_T=c_S.children,c_U=c_N(c_Q,c_R,c_S);c_T&&c_V(c_U,c_T);c_O&&c_O(c_U);}function c_V(c_Q,c_W){for(var c_R in c_W)c_P(c_Q,c_R,c_W[c_R]);}c_V(c_n,c_C);}var c_X={},c_Y=[];c_M(function(c_Q,c_R,c_S){var c_Z=c_S.widgetClass;if(c_Z&& !c_X[c_Z]){c_X[c_Z]=1;c_Y.push(c_Z);}});Uize.module({required:c_Y,builder:function(){function c_0(c_1,c_F,c_2){if(c_2++)c_v[c_1]&&typeof c_v[c_1]=='object'?Uize.copyInto(c_v[c_1],c_F):(c_v[c_1]=c_F);var c_W=c_F.children;if(c_W){for(var c_R in c_W)c_0(c_1+'_'+c_R,c_W[c_R],c_2)}}c_0(c_u.slice(0,-1),{children:c_C},0);c_M(
function(c_Q,c_R,c_S){var c_U=c_Q.children[c_R];if(!c_U){var c_Z=eval(c_S.widgetClass||'Uize.Widget');if(c_R.charCodeAt(0)==36&&c_R.charCodeAt(1)==36){delete c_S.widgetClass;delete c_S.children;c_U=c_Z.spawn(c_S,c_Q);}else{c_U=c_Q.addChild(c_R,c_Z);}}return c_U;},c_n.isWired&&function(c_U){Uize.callOn(c_U,'insertOrWireUi')});c_s();}});}else{c_s();}};c_g.loadHtmlIntoNode=function(c_3,c_4,c_5){var c_n=this,c_6=c_3.rootNodeId,c_s=c_h(c_5),c_7={callback:function(c_8){var c_9=document.body,c_ba=c_3.node!=undefined?c_n.getNode(c_3.node):(c_6?c_e.getById(c_6+'-shell'):c_bb)||c_9;c_e.injectHtml(c_ba,c_8,c_3.injectMode||(c_ba==c_9?'inner bottom':'inner replace'));c_n.c_r(c_s);}};c_3.alwaysReplace===c_c&&c_6&&c_e.getById(c_6)?c_s():c_n.loadHtml(c_4,typeof c_5=='object'&&c_5?Uize.copyInto({},c_5,c_7):c_7);};c_g.performAjax=function(){};c_g.useDialog=function(c_m){var c_n=this,c_bc=Uize.copyInto({},c_n.c_bd,c_m.widgetProperties),c_be=c_bc.parent||c_n,c_bf=c_bc.name,c_bg=c_be.children[c_bf],c_bh=c_m.component,c_bi;
if(c_bh){var c_6=c_bc.idPrefix||(c_be.get('idPrefix')+'_'+c_bf);c_bi={name:c_bh.name,rootNodeId:c_6,params:Uize.copyInto({idPrefix:c_6},c_bh.params)};}function c_bj(c_bk){var c_bl=c_n.get('productType');c_bg.fire({name:'Track Event',extra:c_bk+(c_bl?(' ('+c_bl+')'):''),bubble:c_b});}function c_bm(c_bn){setTimeout(function(){function c_bo(c_bp,c_bq){var c_q=c_m[c_bp];c_q&&c_q.apply(0,c_bq);}function c_br(c_bs){var c_bq=[c_bs];c_bo(c_bs.name.toLowerCase()+'Handler',c_bq);c_bo('dismissHandler',c_bq);}c_bg.unwire(c_bg.eventHandlersForUseDialog||{});c_bg.eventHandlersForUseDialog={'Submission Complete':function(c_bs){c_bo('submitHandler',[c_bs.result,c_bs])},Close:c_br,Cancel:c_br};c_bg.wire(c_bg.eventHandlersForUseDialog);c_bg.set(c_bc);c_bg.set({shown:c_b});c_bj(c_bn);},0);}if(c_bg&&(c_bg.componentProfile==c_bi||Uize.Data.identical(c_bg.componentProfile,c_bi))){c_bm('subsequent');}else{var c_bt=c_bi&& !!c_bg;if(c_bt){c_bg.removeUi();c_be.removeChild(c_bf);}function c_bu(){var c_bv=c_m.widgetClassName;
Uize.module({required:c_bv,builder:function(){(c_bg=c_be.children[c_bf])?c_bg.set(c_bc):(c_bg=c_be.addChild(c_bf,eval(c_bv),c_bc));c_bg.componentProfile=c_bi;c_bg.wire(c_m.widgetEventHandlers);c_bg.insertOrWireUi();c_bm(c_bt?'refetched':'initial');}});}c_bi?c_n.loadHtmlIntoNode({rootNodeId:c_bi.rootNodeId,injectMode:'inner bottom',alwaysReplace:c_c},Uize.copyInto({cp:c_bi.name},c_bi.params),{cache:'memory',callback:c_bu}):c_bu();}};c_g.wireUi=function(){var c_n=this;if(!c_n.isWired){c_n.c_r();c_a.prototype.wireUi.call(c_n);}};var c_bw={yes:1,on:1,1:1,'true':1};c_f.launchPopup=c_g.launchPopup=function(c_m){if(!c_m)c_m={};if(c_m.width==c_d)c_m.width=850;if(c_m.height==c_d)c_m.height=600;var c_bx=window.screen;if(c_m.left==c_d)c_m.left=Math.max((c_bx.width-c_m.width-10)>>1,0);if(c_m.top==c_d)c_m.top=Math.max((c_bx.height-c_m.height-40)>>1,0);function c_by(c_bz){return c_bz+'='+c_m[c_bz];}function c_bA(c_bz,c_bB){return(c_bz+'='+(c_bw[c_m[c_bz]==c_d?c_bB:c_m[c_bz]+'']?'yes':'no'));}var c_bC=window.open(
c_m.url||'',c_m.name==c_d?'popupWindow':c_m.name,[c_by('width'),c_by('height'),c_by('top'),c_by('left'),c_bA('toolbar',0),c_bA('location',0),c_bA('directories',0),c_bA('status',0),c_bA('menubar',0),c_bA('scrollbars',1),c_bA('resizable',1)].join(','));c_bC&&c_bC.focus();return c_bC;};c_f.registerProperties({c_o:{name:'confirmDialog',value:{}},c_bd:'dialogProperties'});c_f.set({idPrefix:'page'});c_g.loadHtml=function(c_4,c_i){c_h(c_i)('');};c_g.showConfirm=function(c_m){this.c_j('confirm','confirm',c_m);};c_g.showInform=function(c_m){this.c_j('alert','info',c_m);};return c_f;}});