/*______________
|       ______  |   B U I L T     O N     U I Z E     F R A M E W O R K
|     /      /  |   ---------------------------------------------------
|    /    O /   |   This JavaScript application is developed using the object
|   /    / /    |   oriented UIZE JavaScript framework as its foundation.
|  /    / /  /| |
| /____/ /__/_| |    ONLINE : http://www.uize.com
|          /___ |   LICENSE : Available under MIT License or GNU General Public License
|_______________|             http://www.uize.com/license.html
*/

/*______________
|       ______  |   U I Z E    J A V A S C R I P T    F R A M E W O R K
|     /      /  |   ---------------------------------------------------
|    /    O /   |    MODULE : UizeDotCom.WidgetToGoPage.Calendar.library Library Module
|   /    / /    |
|  /    / /  /| |    ONLINE : http://www.uize.com
| /____/ /__/_| | COPYRIGHT : (c)2009-2011 UIZE
|          /___ |   LICENSE : Available under MIT License or GNU General Public License
|_______________|             http://www.uize.com/license.html
*/

/*?
	Introduction
		The =UizeDotCom.WidgetToGoPage.Calendar.library= module is a library module that bundles together all the JavaScript modules needed by the calendar Widgets To Go widget.

		*DEVELOPERS:* `Chris van Rensburg`
*/



Uize.module({name:'UizeDotCom'});


Uize.module({name:'Uize.Node',builder:function(){var _a=function(){},_b,_c='string',_d='object',_e='function',_f=true,_g=false,_h=null,_i='hidden',_j=Uize.copyInto;var _k=typeof navigator!='undefined',_l=_k?navigator:{userAgent:'',appName:''},_m=_l.userAgent.toLowerCase(),_n=_l.appName=='Microsoft Internet Explorer',_o={TABLE:_f,THEAD:_f,TFOOT:_f,TBODY:_f,TR:_f,COL:_f,COLGRPUP:_f,FRAMESET:_f,HEAD:_f,HTML:_f,STYLE:_f,TITLE:_f},_p=_m.indexOf('applewebkit')> -1,_q=_m.indexOf('gecko')> -1,_r=_m.indexOf('opera')> -1,_s=_q||_r,_t= +(_n&&(_m.match(/MSIE\s*(\d+)/i)||[0,0])[1]),_u=_n&&_t<9;var _v=_a._v=function(_w){_x.clientX=_w.clientX;_x.clientY=_w.clientY;_x.pageX=_w.pageX;_x.pageY=_w.pageY;};function _y(_z){var _A=document.getElementById(_z);return(!_n||(_A&&_A.id==_z))?_A:_h;}function _B(){return document[_p?'body':'documentElement'];}function _C(_D){var _E=(_D=_D+'').slice(_D.indexOf('(')+1,_D.indexOf(')'));return Function.apply({},(_E?_E.split(','):[]).concat(_D.slice(_D.indexOf('{')+1,_D.lastIndexOf('}'))));}
function _F(_G){if(_G.charCodeAt(0)==111&&_G.charCodeAt(1)==110)_G=_G.slice(2);return(_G.charCodeAt(_G.length-1)==41&&_a.VirtualEvent?_a.VirtualEvent.resolve(_G):_G);}function _H(_I,_J){for(var _K= -1,_A={},_L=Math.min(_I.length,_J.length);++_K<_L;)_A[_I[_K]]=_J[_K];return _A;}var _M=_a._M={},_N={},_O=0,_P={string:1,number:1,boolean:1},_x={clientX:0,clientY:0,pageX:0,pageY:0};var _Q='table-',_R=_Q+'row',_S=_Q+'cell',_T=_j({SPAN:'inline',THEAD:_Q+'header-group',TFOOT:_Q+'footer-group',LI:'list-item'},_n&&typeof DOMImplementation=='undefined'?_h:{TABLE:'table',TR:_R,TH:_S,TD:_S,TBODY:_R+'-group',COLGROUP:_Q+'column-group',COL:_Q+'column',CAPTION:_Q+'caption'});_a.display=function(_U,_V){_V=_V===_b|| !!_V;_W(_U,function(_X){_X.style.display=_V?(_T[_X.tagName]||'block'):'none';});};var _W=_a.doForAll=function(_U,_D,_Y,_Z){if(typeof _U==_c)_U=_0(_U,_Y,_Z);if(_U!=_b){if(_1(_U)){_D(_U);}else{var _2=typeof _U;if((_2==_d||_2==_e)&&typeof _U.length=='number'){for(var _3= -1,_4=_U.length;++_3<_4;)_W(_U[_3],_D,_Y,_Z);
}else if(_2==_d){for(var _5 in _U)_W(_U[_5],_D,_Y,_Z);}}}};var _6=_a.doRectanglesOverlap=function(_7,_8,_9,_ba,_bb,_bc,_bd,_be){return(_9-1+ +_7>=_bb&&_bd-1+ +_bb>=_7&&_ba-1+ +_8>=_bc&&_be-1+ +_bc>=_8);};var _0=_a.getById=function(_X,_Y,_Z){if(typeof _X!=_c)return _X;var _A=_Z?_Z[_X]:_b;if(_A===_b){var _bf=_bg(_Y,_X);(_A=_y(_bf))||(((_A=document.getElementsByName(_bf)).length<2)&&(_A=_A[0]||_h));if(_Z)_Z[_X]=_A;}return _A;};_a.find=function(_bh){if(typeof _bh!=_d|| !_bh||typeof _bh.length=='number'||_1(_bh))return _bh;var _bi=document,_bj=[],_bk=_j({},_bh),_bl='root'in _bk?_0(_bk.root):_bi;delete _bk.root;if(_bl){var _bm=_bk.tagName;if('id'in _bk&&_P[typeof _bk.id]){var _X=_y(_bk.id);_X&&_bj.push(_X);delete _bk.id;}else if('name'in _bk&&_P[typeof _bk.name]){_bj=_bi.getElementsByName(_bk.name);delete _bk.name;}else{var _bn=_P[typeof _bm];_bn&&delete _bk.tagName;_bj=_bl.getElementsByTagName(_bm&&_bn?_bm:'*');_bl=_h;}if(_bl==_bi)_bl=_h;if(!_bm||_bm=='*')delete _bk.tagName;}var _bo=_bj.length;
for(var _bp in _bk)break;if(!_bo||(_bp==_b&& !_bl))return _bj;var _bq=[],_br;for(var _bs= -1;++_bs<_bo;){var _X=_bj[_bs];if(_br=_bl?_bt(_X,_bl):_f){for(var _bu in _bk){var _bv=_X[_bu],_bw=_bk[_bu],_bx=Uize.isFunction;if(!(_P[typeof _bw]?_bv==_bw:(_bw instanceof RegExp?_bw.test(_bv||''):(_bx(_bw)?_bw.call(_X,_bv):_f)))){_br=_g;break;}}}_br&&_bq.push(_X);}return _bq;};var _by=_a.getCoords=function(_X){var _bz=0,_bA=0,_bB=0,_bC=0,_bD=_f,_bE=100,_bF=_B(),_bG=_bH(window);function _bI(){_bz+=_bF.scrollLeft;_bA+=_bF.scrollTop;}if(_X==window){_bI();_bB=_bG.width;_bC=_bG.height;}else if(_1(_X=_0(_X))){_bB=_X.offsetWidth;_bC=_X.offsetHeight;if(!(_bB&&_bC)&&_X.tagName=='DIV'){for(var _bJ=_X.childNodes,_bK=_bJ.length;--_bK>=0;){if(_bJ[_bK].nodeName.charAt(0)!='#'){var _bL=_by(_bJ[_bK]);if(_bL.width||_bL.height){_bB=Math.max(_bB,_bL.right-_bz+1);_bC=Math.max(_bC,_bL.bottom-_bA+1);}}}}function _bM(_X){return _bN(_X,'display')=='none'||_bN(_X,'visibility')==_i;}
if(_X.tagName=='A'&&_X.childNodes.length==1&&_X.childNodes[0].tagName=='IMG')_X=_X.childNodes[0];var _bO=_bD= !_bM(_X),_bP=_X,_bQ=_X,_bR=_bG.width,_bS=_bG.height,_bT=_bF.scrollLeft,_bU=_bF.scrollTop,_bV=_bT+_bR,_bW=_bU+_bS;while(_bQ.parentNode&&typeof _bQ.parentNode!='unknown'){var _bX=_bQ.offsetLeft||0,_bY=_bQ.offsetTop||0,_bZ=_bQ.offsetWidth,_b0=_bQ.offsetHeight;if(_bD&&_bM(_bQ))_bD=_g;if(_bQ==_bP){_bz+=_bX+(parseInt(_bN(_bQ,'borderLeftWidth'))||0);_bA+=_bY+(parseInt(_bN(_bQ,'borderTopWidth'))||0);_bP=_bQ.offsetParent;_bN(_bQ,'position')=='fixed'&&_bI();}if(_bQ!=_X&&_bQ!=document.body&&_bQ!=document.documentElement&&(_bQ.scrollWidth>_bZ||_bQ.scrollHeight>_b0)){_bz-=_bQ.scrollLeft;_bA-=_bQ.scrollTop;if(_n){_bz+=_bQ.clientLeft;_bA+=_bQ.clientTop;}if(_bD)_bD=_6(_bz,_bA,_bB,_bC,_bX,_bY,_bZ,_b0);}_bQ=_bQ.parentNode;}if(_bD)_bD=_6(_bz,_bA,_bB,_bC,_bT,_bU,_bR,_bS);_bE=_bD?((Math.min(_bz+_bB,_bV)-Math.min(Math.max(_bz,_bT),_bV))*(Math.min(_bA+_bC,_bW)-Math.min(Math.max(_bA,_bU),_bW)))/(_bB*_bC)*100:0;}return{x:_bz,
y:_bA,width:_bB,height:_bC,area:_bB*_bC,left:_bz,top:_bA,right:_bz+_bB-1,bottom:_bA+_bC-1,seen:_bD,percentSeen:_bE};};var _bH=_a.getDimensions=function(_X){if(_X==window){var _bF=document.documentElement;return{width:_bF.clientWidth||window.innerWidth||_bF.offsetWidth,height:_bF.clientHeight||window.innerHeight||_bF.offsetHeight};}else if(_X=_0(_X)){return{width:_X.offsetWidth||parseInt(_bN(_X,'width'))||0,height:_X.offsetHeight||parseInt(_bN(_X,'height'))||0};}else{return{width:0,height:0};}};var _b1={borderColor:['border','Color'],borderWidth:['border','Width'],padding:1,margin:1},_bN=_a.getStyle=function(_X,_b2){var _b3='';if(typeof _b2==_c){if(_X){var _b4=_n&&_b2=='opacity',_b5=document.defaultView,_b6=_b5&&_b5.getComputedStyle(_X,'');if(_b4)_b2='filter';if(_b6){if(!(_b3=_b6[_b2])){var _b7=_b1[_b2];if(_b7){var _b8=_b7[0]||_b2,_b9=_b7[1]||'',_ca=_b6[_b8+'Top'+_b9],_cb=_b6[_b8+'Right'+_b9],_cc=_b6[_b8+'Bottom'+_b9],_cd=_b6[_b8+'Left'+_b9];_b3=_ca==_cb&&_cb==_cc&&_cc==_cd?_cd:_ca+' '+_cb+' '+_cc+' '+_cd;}}
}else{var _ce=_X.currentStyle;_b3=_ce?_ce.getAttribute(_b2):_X.style[_b2];}if(_b4){var _cf=(_b3||'').match(/alpha\s*\(\s*opacity\s*=([^\)]*)\)/i);_b3=_cf?_cf[1]/100:1;}}}else{_b3={};if(_X)for(_b2 in _b2)_b3[_b2]=_bN(_X,_b2);}return _b3;};var _cg=_a.getText=function(_X){var _ch='';if(_X=_0(_X)){function _ci(_X){if(typeof _X.innerText==_c){_ch+=_X.innerText.replace(/\r|\n|\r\n/g,'');}else if(typeof _X.textContent==_c){_ch+=_X.textContent;}else{if(_X.nodeType==3)_ch+=_X.data;if(_X.childNodes){for(var _bK= -1,_bJ=_X.childNodes,_cj=_bJ.length;++_bK<_cj;)_cg(_bJ[_bK]);}}}_ci(_X);}return _ch;};_a.getValue=function(_X){var _b3;if(_X=_0(_X)){if(_1(_X)){var _ck=_X.tagName;if(_ck=='TEXTAREA'){_b3=_X.value;}else if(_ck=='INPUT'){_b3=_X.type=='checkbox'?_X.checked:_X.value;}else if(_ck=='SELECT'){if(_X.multiple){_b3=[];for(var _cl= -1,_cm=_X.options,_cn=_cm.length,_co;++_cl<_cn;)(_co=_cm[_cl]).selected&&_b3.push(_co.value);}else{_b3=_X.value;}}else if(_ck=='IMG'){_b3=_X.src;}else{
_b3=_X.innerHTML.replace(/<br\/?>/gi,'\n').replace(/&nbsp;/g,' ');}}else{_b3=(Uize.findRecord(_X,{tagName:'INPUT',type:'radio',checked:_f})||{}).value;}}return _b3;};_a.injectHtml=function(_U,_cp,_cq){var _cr,_cs,_ct,_cu,_cv,_cw,_cx=Uize.isArray(_cp)||(_1(_cp)&&(_cp=[_cp]));((_cr=_cq=='inner replace')||(_cs=_cq=='outer replace')||(_ct=_cq=='inner top')||(_cu=_cq=='outer top')||(_cv=_cq=='outer bottom')||(_cw=_f));_cx||(_cp+='');_W(_U,function(_X){var _cy=_X.childNodes;function _cz(_cA){return _cA&&/<script/i.test(_cA)}function _cB(){return _cz(_cp)}if((_cr||(!_cy.length&&(_ct||_cw)))&& !_1&& !_cB()){_X.innerHTML=_cp;}else if(_cs&&_n&& !_1&& !_cB()){_X.outerHTML=_cp;}else{if(_cr)if(_n&&_o[_X.tagName]){var _cC=_X.cloneNode();_X.replaceNode(_cC);_X=_cC;}else _X.innerHTML='';if(_cx){var _cD=[];for(var _bs= -1,_cE=_cp.length;++_bs<_cE;)_cD.push(_cp[_bs].cloneNode(_f));}else{var _cF=document.createElement('DIV');_cF.innerHTML='<i>e</i>'+_cp;var _cD=_cF.childNodes}var _cG=_ct?_cy[0]:_cv?_X.nextSibling:_X,
_cH=_X.parentNode,_cI= +!_cx;function _cJ(_X){if(_X.tagName=='SCRIPT'){var _cK=document.createElement('script');if(_X.id)_cK.id=_X.id;if(_X.type)_cK.type=_X.type;_cK.text=_X.text;if(_X.src)_cK.src=_X.src;_X.parentNode.replaceChild(_cK,_X);}else if(_cz(_X.innerHTML)){for(var _bK= -1,_cy=_X.childNodes,_cL=_cy.length;++_bK<_cL;)_cJ(_cy[_bK]);}}while(_cD.length>_cI){var _cM=_cx?_cD.shift():_cD[_cI];if(_cw||_cr){_X.appendChild(_cM);}else if(_ct){_cG?_X.insertBefore(_cM,_cG):_X.appendChild(_cM);}else if(_cu||_cs){_cH.insertBefore(_cM,_cG);}else if(_cv){_cG?_cH.insertBefore(_cM,_cG):_cH.appendChild(_cM);}_cx||_cJ(_cM);}_cs&&_cH.removeChild(_X);}});};var _1=_a.isNode=function(_X){return!!(_X&&typeof _X==_d&&(_X.getAttribute||_X.documentElement||(_X.self&&_X.self==_X)));};var _bt=_a.isOnNodeTree=function(_X,_cN){_X=_0(_X);_cN=_0(_cN);while(_X){if(_X==_cN)return _f;_X=_X.parentNode;}return _g;};var _bg=_a.joinIdPrefixAndNodeId=function(_Y,_z){return(_Y||'')+(_Y&&_z?'-':'')+_z;};_a.remove=function(_U){
_W(_U,function(_X){_X.parentNode.removeChild(_X)});};_a.setClipRect=function(_U,_ca,_cb,_cc,_cd){var _cO='rect('+_ca+'px, '+_cb+'px, '+_cc+'px, '+_cd+'px)';_W(_U,function(_X){_X.style.clip=_cO});};var _cP=['left','top','width','height'];_a.setCoords=function(_U,_cQ){_cR(_U,typeof _cQ.length=='number'?_H(_cP,_cQ):_cQ);};_a.centerInWindow=function(_U){var _cS=_by(window);_W(_U,function(_X){var _cT=_bH(_X);_a.setCoords(_X,{left:_cS.x+((_cS.width-_cT.width)>>1),top:_cS.y+((_cS.height-_cT.height)>>1)});});};_a.getEventAbsPos=function(_cU){var _cV=(_cU||(_cU=_x)).targetTouches;if(_cV&&_cV.length)_cU=_cV[0];if(_cU.pageX!=_b){return{left:_cU.pageX,top:_cU.pageY};}else{var _bF=_B();return{left:_cU.clientX+_bF.scrollLeft,top:_cU.clientY+_bF.scrollTop};}};var _cW=_a.setAbsPos=function(_U,_cX,_cY){_cY=typeof _cY=='number'?{x:_cY,y:_cY}:(_cY||{x:0,y:0});var _bF=document[_p?'body':'documentElement'],_cZ=_bH(window);_W(_U,function(_X){function _c0(_c1,_c2,_c3,_c4){var _c5=_cX[_c1],_c6=_cY[_c4],_c7=_c5-_bF[_c2],
_c8=_c6+_cT[_c3];return(_c5+(_c7+_c8>_cZ[_c3]?Math.max(-_c8,-_c7):_c6));}var _cT=_bH(_X);_cR(_X,{left:_c0('left','scrollLeft','width','x'),top:_c0('top','scrollTop','height','y'),right:'auto',bottom:'auto'});});};_a.setAbsPosAdjacentTo=function(_U,_c9,_da){_c9=_0(_c9);var _db=_by(_c9),_dc=_db.width/2,_dd=_db.height/2,_de=_da=='x'? -1:1;if(!_dc&& !_dd)_db=_a.getEventAbsPos();_W(_U,function(_X){_cW(_X,{left:_db.left+_dc,top:_db.top+_dd},{x:-_dc*_de,y:_dd*_de});});};_a.setInnerHtml=function(_U,_cA){_cA+='';_W(_U,function(_X){_X.innerHTML=_cA});};var _df={};_a.setOpacity=function(_U,_dg){_df.opacity=_dg;_cR(_U,_df);};_a.setProperties=function(_U,_bh){_W(_U,function(_X){_j(_X,_bh)});};var _cR=_a.setStyle=function(_U,_bh){_W(_U,function(_X){var _dh=_X.style,_di;if(_n&&'opacity'in _bh)_dh.filter=(_di=Math.round(_bh.opacity*100))<100?'alpha(opacity='+_di+')':'';for(var _b2 in _bh)_dh[_b2]=(typeof(_di=_bh[_b2])==_d&&_di?(_di=_di.valueOf()):_di)!=_b?(typeof _di=='number'&&_b2!='opacity'&&_b2!='zIndex'
?Math.round(_di)+'px':_di+''):'';});};_a.setValue=function(_U,_b3){_b3+='';_W(_U,function(_X){var _ck=_X.tagName,_dj=_X.readOnly;if(_dj)_X.readOnly=_g;if(_ck=='TEXTAREA'){_X.value=_b3;}else if(_ck=='INPUT'){var _dk=_X.type;if(_dk=='text'||_dk==_i||_dk=='password'){_X.value=_b3;}else if(_dk=='checkbox'){_X.checked=_b3=='true';}else if(_dk=='radio'){_X.checked=_X.value==_b3;}}else if(_ck=='SELECT'){if(!_b3){_X.selectedIndex= -1;}else{var _cm=_X.options;if(_X.multiple&&(_b3=='*'||_b3.indexOf(',')> -1)){var _dl;if(_b3!='*'){_dl={};for(var _J=_b3.split(','),_K=_J.length;--_K>=0;)_dl[_J[_K]]=1;}for(var _cl=_cm.length,_co;--_cl>=0;)(_co=_cm[_cl]).selected= !_dl||_dl[_co.value];}else{_X.selectedIndex=Uize.findRecordNo(_cm,{value:_b3},_X.selectedIndex);}}}else if(_ck=='IMG'){if(_b3)_X.src=_b3;}else{_ck=='PRE'&&_n?(_X.innerText=_b3):(_X.innerHTML=_b3.replace(/</g,'&lt;').replace(/\n/g,'<br/>'));}if(_dj)_X.readOnly=_dj;});};_a.show=function(_U,_dm){_cR(_U,{visibility:_dm||_dm===_b?'inherit':_i});};
_a.showClickable=function(_U,_dn){_cR(_U,{cursor:_dn||_dn===_b?(_u?'hand':'pointer'):'default'});};var _do=_a.unwire=function(_U,_dp,_dq,_dr){if(typeof _dp==_d&&_dp&& !_dp.virtualDomEvent){for(var _G in _dp)_do(_U,_G,_dp[_G],_dq);}else{_a.unwireEventsByOwnerId(_dr,_U!==_b||_dp!=_b||_dq!=_b?{node:_U,eventName:_dp,handler:_dq}:_b);}};_a.unwireEventsByOwnerId=function(_ds,_dt){var _du=_N[_ds=_ds||''];if(_du){function _dv(_dw){if(_dw!==_h){var _dx=_dt&&_dt.eventName,_dy=_dt&&_dt.handler,_dz=_dw||_dx||_dy;if(_dx&&_dx.charCodeAt)_dx=_F(_dx);for(var _dA=_du.length;--_dA>=0;){var _dB=_du[_dA],_dC=_M[_dB],_X=_dC._X,_G=_dC._G;if(!_dz||((!_dw||_dw==(_dC._dD||_X))&&(!_dx||_dx==_G)&&(!_dy||_dy==_dC._dE))){_dz&&_du.splice(_dA,1);if(_dC._dF){_a.unwireEventsByOwnerId(_dC._dF)}else{try{_X==window?_dG.unwire(_G,_dC._dH):_n?_X.detachEvent('on'+_G,_dC._dH):_X.removeEventListener(_G,_dC._dH,_g);}catch(_dI){}}delete _M[_dB];}}(_dz&&_du.length)||delete _N[_ds];}}_dt&&_dt.node!==_b?_W(_dt.node,_dv):_dv();}};var _dJ=_C(function(_dB){
return(function(_w){var _dC=window.Uize&&Uize.Node._M[_dB];return _dC&&_dC._dE.call(_dC._X,_w.windowEvent);});}),_dK=_C(function(_dB){return(function(_w){var _dC=window.Uize&&Uize.Node._M[_dB];return _dC&&_dC._dE.call(_dC._X,_w||window.event);});}),_dL={click:_dK,mouseover:_C(function(_dB){return(function(_w){var _dC=window.Uize&&Uize.Node._M[_dB],_dM=(_w||(_w=window.event)).fromElement||_w.relatedTarget;if(_dC){if(_dM){try{if(!_dM.Uize_Widget_Drag_shield&& !Uize.Node.isOnNodeTree(_dM,_dC._X))_dM=null;}catch(_dI){_dM=null;}}if(!_dM){Uize.Node._v(_w);return _dC._dE.call(_dC._X,_w);}}});}),mouseout:_C(function(_dB){return(function(_w){var _dC=window.Uize&&Uize.Node._M[_dB],_dN=(_w||(_w=window.event)).toElement||_w.relatedTarget;if(_dC){if(_dN){try{if(!_dN.Uize_Widget_Drag_shield&& !Uize.Node.isOnNodeTree(_dN,_dC._X))_dN=null;}catch(_dI){_dN=null;}}if(!_dN)return _dC._dE.call(_dC._X,_w);}});}),mousedown:_dK,mouseup:_dK};_a.wire=function(_U,_G,_dE,_ds){if(!_G)return;if(_ds==_b)_ds='';var _dO;if(_G.charCodeAt)
_G=_F(_G);if(typeof _G==_d&& !(_dO= !!_G.virtualDomEvent)){_ds=arguments[2]||'';for(var _w in _G)_a.wire(_U,_w,_G[_w],_ds);return;}_W(_U,function(_X){var _ck=_X.tagName;(_N[_ds]||(_N[_ds]=[])).push(_O);var _dH=(_dO?_a.returnFalse:_X==window?_dJ:_dL[_G]||_dK)(_O);var _dC=_M[_O++]={_X:_X,_G:_G,_dE:_dE,_dH:_dH};if(_s&&_ck=='BODY'&&_G=='scroll'){_dC._dD=_X;_X=_dC._X=document;}if(_dH){var _dP='on'+_G;_X==window?_dG.wire(_G,_dH):_n?_X.attachEvent(_dP,_dH):_X.addEventListener(_G,_dH,_g);if(_ck=='A'&&(_G=='mousedown'||_G=='click')&& !_X[_dP])_X[_dP]=_a.returnFalse;}else if(_dO){_G.wire(_X,_dE,_dC._dF=Uize.getGuid());}});};_a.returnFalse=new Function('return false');_a.returnTrue=new Function('return true');_a.ieMajorVersion=_t;_a.isIe=_n;_a.isSafari=_p;_a.isMozilla=_q;if(_k){_a.wire(document.documentElement,'mousemove',_v);var _dG=new Uize,_dQ=setTimeout(function(){_dG.fire('load')},15000);function _dR(_dS){var _dT='on'+_dS,_dU=window[_dT]||_a.returnFalse;window[_dT]=function(_w){_dS=='load'&&clearTimeout(_dQ);
_dU.call(window,_w||(_w=window.event));_dG.fire({name:_dS,windowEvent:_w});};}for(var _dS in{focus:1,blur:1,load:1,beforeunload:1,unload:1,resize:1,scroll:1})_dR(_dS);;}return _a;}});


Uize.module({name:'Uize.Widget',required:'Uize.Node',builder:function(b_a){var b_b=null,b_c=true,b_d=false,b_e='string',b_f=Uize.isFunction,b_g='concatenated',b_h,b_i=Uize.Node,b_j=b_i.doForAll,b_k=b_i.isNode,b_l=b_i.getById;var b_m=b_a.subclass(function(b_n){var b_o=this;if(b_n){var b_p=b_o.b_q(b_n.idPrefix,b_n.parent);b_p&&Uize.copyInto(b_n,b_p);delete b_n.widgetClass;}b_o.b_r={};b_o.children=b_o.b_s={};}),b_t=b_m.prototype;b_t.b_q=function(b_u,b_v){var b_n,b_w;(b_u&&(b_n=window[b_w='$'+b_u])&&typeof b_n=='object'&&(!b_v||b_u!=b_v.b_u))?(window[b_w]=b_h):(b_n=b_h);return b_n;};b_t.b_x=function(){var b_o=this,b_p=b_o.b_q(b_o.b_u,b_o.parent);b_p&&b_o.set(b_p);};b_t.b_y=function(b_z,b_A,b_B,b_C){return((!b_C||b_C==b_g)&&b_z!=b_h?(b_z+(b_B!==''?'_':'')+b_B):(b_C=='same as parent'?b_z:b_A));};var b_D={b_E:b_d,b_F:b_c};b_t.b_G=function(){(this.b_H=='inherit'?(this.parent||b_D).b_E:this.b_H)!=this.b_E&&this.set({b_E:!this.b_E});};b_t.b_I=function(){(this.b_J=='inherit'?(this.parent||b_D).b_F:this.b_J)!=this.b_F&&
this.set({b_F:!this.b_F});};b_t.b_K=function(b_L,b_M,b_N){var b_O='show'+Uize.capFirstChar(b_L);this.getProvider(b_O)?this.callInherited(b_O)(b_M):setTimeout(function(){var b_P=b_N();(b_M.callback||(b_P?b_M.yesHandler:b_M.noHandler)||function(){})(b_P)},0);};b_t.confirm=function(b_M){this.b_K('confirm',b_M,function(){return confirm(b_M.message)});};b_t.showInform=b_t.showConfirm=b_h;b_t.inform=function(b_M){this.b_K('inform',b_M,function(){alert(b_M.message);return b_c})};b_t.ajax=function(b_Q,b_R){this.callInherited('performAjax')(b_Q,Uize.isFunction(b_R)?{callback:b_R}:b_R||{})};b_t.localize=function(b_S,b_T,b_U){var b_V,b_W=this;while(!(b_V=b_W.b_X?b_W.b_X[b_S]:b_h)&&(b_W=b_W.parent));return(b_f(b_V)?b_V.call(this,b_T):Uize.substituteInto(b_V,b_T,b_U||'{KEY}'));};b_t.buildHtml=function(b_Y){var b_o=this,b_Z=b_o.b_Z;if(b_Z!=b_h){var b_0=b_o.b_1||b_o.getNode('shell')||b_o.getNode();if(b_Z===b_c){b_Z=b_o.b_Z=Uize.Template&&b_0?{process:Uize.Template.compile((
b_i.find({root:b_0,tagName:'SCRIPT',type:'text/jst'})[0]||b_0).innerHTML,{openerToken:'[%',closerToken:'%]'})}:b_h;if(!b_Z)return;}b_o.b_u||b_o.set({b_u:b_o.instanceId});var b_2=Uize.copyInto({pathToResources:Uize.pathToResources,blankGif:b_m.getBlankImageUrl()},b_Y||b_o.get()),b_3;b_i.injectHtml(b_0||document.body,typeof b_Z!=b_e&&b_f(b_Z.process)?b_Z.process.call(b_o,b_2):b_f(b_Z)?typeof(b_3=b_Z(b_2))==='string'?Uize.substituteInto(b_3,b_2):b_3:Uize.substituteInto(b_Z,b_2),b_o.b_4||(b_0?'inner replace':'inner bottom'));b_o.b_5=b_b;b_o.set({b_6:b_c});}};function b_7(b_8,b_9){b_t[b_8+'Node'+b_9]=new Function('arguments.length'+'?(arguments[0]=this.getNode(arguments[0]))'+':(arguments[arguments.length++]=this.getNode());'+'return Uize.Node.'+b_8+b_9+'.apply(0,arguments)');}b_t.getNode=function(b_ba){if(b_ba==b_b){if(b_ba===b_b)return b_b;b_ba='';}var b_o=this;if(b_o.b_bb&&typeof b_ba==b_e){var b_bc=b_o.b_bb[b_ba];if(b_bc!==b_h)b_ba=b_bc;}if(typeof b_ba==b_e){return b_l(b_ba,b_o.b_u,b_o.b_5||(b_o.b_5={}));
}else if(b_k(b_ba)){return b_ba;}else{var b_bd=b_b;b_j(b_ba,function(b_be){(b_bd||(b_bd=[])).push(b_be)},b_o.b_u,b_o.b_5||(b_o.b_5={}));return b_bd;}};b_7('get','Style');b_7('get','Value');b_t.flushNodeCache=function(b_bf){if(this.b_5)b_bf==b_h?(this.b_5=b_b):delete this.b_5[b_bf];};b_t.globalizeNode=function(b_bg){var b_o=this,b_bh=document.body;b_j(b_o.getNode(b_bg),function(b_be){if(b_be.parentNode!=b_bh){(b_o.b_bi||(b_o.b_bi=[])).push(b_be);b_i.setStyle(b_be,{position:'absolute',left:-10000,top:-10000});b_bh.appendChild(b_be);}});};b_7('display','');b_7('inject','Html');b_t.removeNode=function(b_bg){b_i.remove(this.getNode(b_bg));this.flushNodeCache(b_bg);};b_7('set','Properties');b_7('set','Opacity');b_7('set','Style');b_7('set','ClipRect');b_7('set','InnerHtml');b_7('set','Value');b_7('show','');b_t.wireNode=function(b_bg,b_bj,b_bk){arguments.length==3?b_i.wire(this.getNode(b_bg),b_bj,b_bk,this.instanceId):b_i.wire(this.getNode(b_bg),b_bj,this.instanceId);};b_t.unwireNode=function(b_bg,b_bj,b_bk){
if(b_bg!==b_h)b_bg=this.getNode(b_bg);arguments.length==2&&typeof b_bj=='object'&&b_bj&& !b_bj.virtualDomEvent?b_i.unwire(b_bg,b_bj,this.instanceId):b_i.unwire(b_bg,b_bj,b_bk,this.instanceId);};b_t.unwireNodeEventsByMatch=function(b_bg,b_bl){this.unwireNode(b_bg,(b_bl||(b_bl={})).eventName,b_bl.handler);};b_t.addChild=function(b_B,b_bm,b_n){if(!b_n)b_n={};var b_o=this,b_u=b_o.b_u,b_bn=Uize.isInstance(b_bm)?b_bm:b_b,b_A='idPrefix'in b_n?b_n.idPrefix:b_n.node,b_bo=b_n.idPrefixConstruction;b_n.parent=b_o;if(b_B==b_h)b_B=b_n.name;if(b_bn){if(b_B==b_h)b_B=b_bn.b_bp;if(b_A==b_h)b_A=b_bn.b_u;if(!b_bo)b_bo=b_bn.b_C;}b_n.idPrefix=b_o.b_y(b_u,b_A,b_n.name=b_B,b_n.idPrefixConstruction=b_bo||(b_A==b_h?b_g:'explicit'));var b_r=b_o.b_r,b_bq=b_r[b_B];if(b_bq){Uize.copyInto(b_n,b_bq);delete b_r[b_B];}b_bn&&b_bn.set(b_n);return b_o.b_s[b_B]=b_bn||new b_bm(b_n);};b_t.removeChild=function(b_br){var b_s=this.b_s,b_B=typeof b_br==b_e||Uize.isNumber(b_br)?b_br:b_br.b_bp,b_bn=b_s[b_B];if(b_bn){b_bn.unwireUi();delete b_bn.parent;
delete b_s[b_B];}};b_t.getProvider=function(b_bs){var b_bt=this,b_bu;while(((b_bu=b_bt.get(b_bs))==='inherit'||b_bu===b_h)&&(b_bt=b_bt.parent));return b_bt;};b_t.getInherited=function(b_bs){var b_bv=this.getProvider(b_bs);return b_bv?b_bv.get(b_bs):b_h;};b_t.setInherited=function(b_n){var b_bv;for(var b_bw in b_n){if(b_bv=this.getProvider(b_bw))b_bv.set(b_bw,b_n[b_bw]);}};b_t.callInherited=function(b_bs){var b_o=this;return(function(){var b_bv=b_o.getProvider(b_bs),b_bd;if(b_bv){var b_bx=b_bv.get(b_bs);if(b_f(b_bx))b_bd=b_bx.apply(b_bv,arguments);}return b_bd;});};b_t.kill=function(){Uize.callOn(this.b_s,'kill');b_a.prototype.kill.call(this);};b_t.insertOrWireUi=function(){this.b_6?this.wireUi():this.insertUi();};b_t.insertUi=function(){this.buildHtml();this.wireUi();};b_t.removeUi=function(){this.unwireUi();this.removeNode();b_i.remove(this.b_bi);this.b_bi=b_h;Uize.callOn(this.b_s,'removeUi');this.set({b_6:b_d});};b_t.updateUi=function(){};b_t.wireUi=function(){if(!this.isWired){this.b_x();
this.set({wired:b_c});var b_s=this.b_s;for(var b_B in b_s)b_s[b_B].insertOrWireUi();this.updateUi();}};b_t.unwireUi=function(){if(this.isWired){this.b_5=b_b;this.unwireNode();Uize.callOn(this.b_s,'unwireUi');this.set({wired:b_d});}};b_m.getBlankImageUrl=function(){return Uize.pathToResources+'Uize/blank.gif';};b_m.spawn=function(b_n,b_v){var b_o=this,b_by=[],b_bt,b_bz=b_v&&b_v.b_u?b_v.b_u+'_':'',b_bA=b_bz.length;b_j(Uize.Node.find(b_n.idPrefix),function(b_be){b_n.idPrefix=b_be;b_v?(b_bt=b_v.addChild(b_be.id.slice(0,b_bA)==b_bz?b_be.id.slice(b_bA):'generatedChildName'+Uize.getGuid(),b_o,b_n)):(b_bt=new b_o(b_n)).insertOrWireUi();b_by.push(b_bt);});return b_by;};b_m.registerProperties({b_6:{name:'built',value:b_c},b_H:{name:'busy',onChange:b_t.b_G,value:'inherit'},b_E:{name:'busyInherited',onChange:function(){Uize.callOn(this.b_s,b_t.b_G)},value:b_d},b_s:{name:'children',conformer:function(b_bu){if(b_bu){var b_s=this.b_s,b_r=this.b_r;for(var b_B in b_bu){var b_bB=b_bu[b_B];b_s[b_B]?b_s[b_B].set(b_bB)
:b_r[b_B]=b_bB;}}return this.b_s;}},b_1:'container',b_J:{name:'enabled',onChange:b_t.b_I,value:'inherit'},b_F:{name:'enabledInherited',onChange:function(){Uize.callOn(this.b_s,b_t.b_I)},value:b_c},b_Z:'html',b_u:{name:'idPrefix|node',conformer:function(b_u){return b_k(b_u)?(b_u.id||(b_u.id=Uize.getGuid())):b_u;},onChange:function(){var b_o=this,b_u=b_o.b_u;b_o.b_5=b_b;if(b_u!=b_h){b_o.b_x();var b_s=b_o.b_s,b_bn;for(var b_B in b_s)(b_bn=b_s[b_B]).set({b_u:b_o.b_y(b_u,b_bn.b_u,b_B,b_bn.b_C)});if(b_o.isWired){b_o.set({wired:b_d});b_o.wireUi();}}}},b_C:'idPrefixConstruction',b_4:'insertionMode',b_X:'localized',b_bp:'name',b_bb:'nodeMap',isWired:{name:'wired',value:b_d}});return b_m;}});


Uize.module({name:'Uize.Widget.Page',required:'Uize.Node',builder:function(c_a){var c_b=true,c_c=false,c_d=null,c_e,c_f=Uize.Node;var c_g=c_a.subclass(c_d,function(){c_g.xDeferredLinks&&this.wireDeferredLinks()}),c_h=c_g.prototype;function c_i(c_j){return(Uize.isFunction(c_j)&&c_j)||(c_j&&c_j.callback)||Object}c_h.c_k=function(c_l,c_m,c_n){var c_o=this;c_o.useDialog({component:c_o.c_p.component,widgetClassName:c_o.c_p.widgetClassName||'Uize.Widget.Dialog.Confirm',widgetProperties:{name:'confirmDialog',title:c_n.title||'',message:(c_n.message+'').replace(/\n/g,'<br/>'),mode:c_l,state:c_n.state||c_m,okText:c_n.okText||c_d,cancelText:c_n.cancelText||c_d},submitHandler:function(c_q){var c_r=c_n.callback||(c_q?c_n.yesHandler:c_n.noHandler);c_r&&c_r(c_q);}});};c_h.c_s=function(c_t){c_t=c_t||Object;var c_o=this,c_u=c_o.get('idPrefix'),c_v=window;function c_w(c_x,c_y){var c_z,c_A;for(var c_B in c_y)(typeof(c_z=c_x[c_B])=='object'&&typeof(c_A=c_y[c_B])=='object'&&c_z&&c_A)?c_w(c_z,c_A):(c_x[c_B]=c_y[c_B]);}var c_C={},
c_D=c_c,c_E='$'+c_u+'_',c_F=c_E.length,c_G;for(var c_B in c_v){if(c_B.charAt(0)=='$'&&c_B.substr(0,c_F)==c_E&&typeof(c_G=c_v[c_B])=='object'&&c_G&&c_G.widgetClass){c_D=c_b;for(var c_H= -1,c_I=c_C,c_J=c_B.substr(c_F).split('_'),c_K,c_L=c_J.length;++c_H<c_L;){var c_M=c_I[c_K=c_J[c_H]];if(c_H<c_L-1){c_I=(c_M||(c_M=c_I[c_K]={})).children||(c_M.children={});}else{c_M?c_w(c_M,c_G):(c_I[c_K]=c_G);c_v[c_B]=c_e;}}}}if(c_D){function c_N(c_O,c_P){function c_Q(c_R,c_S,c_T){var c_U=c_T.children,c_V=c_O(c_R,c_S,c_T);c_U&&c_W(c_V,c_U);c_P&&c_P(c_V);}function c_W(c_R,c_X){for(var c_S in c_X)c_Q(c_R,c_S,c_X[c_S]);}c_W(c_o,c_C);}var c_Y={},c_Z=[];c_N(function(c_R,c_S,c_T){var c_0=c_T.widgetClass;if(c_0&& !c_Y[c_0]){c_Y[c_0]=1;c_Z.push(c_0);}});Uize.module({required:c_Z,builder:function(){c_o.set({children:c_C});c_N(function(c_R,c_S,c_T){var c_V=c_R.children[c_S];if(!c_V){var c_0=eval(c_T.widgetClass||'Uize.Widget');c_V=c_S.charCodeAt(0)==36&&c_S.charCodeAt(1)==36?c_0.spawn(c_T,c_R):c_R.addChild(c_S,c_0);}return c_V;},
c_o.isWired&&function(c_V){Uize.callOn(c_V,'insertOrWireUi')});c_t();}});}else{c_t();}};c_h.loadHtmlIntoNode=function(c_1,c_2,c_3){var c_o=this,c_4=c_1.rootNodeId,c_t=c_i(c_3),c_5={callback:function(c_6){var c_7=document.body,c_8=c_1.node!=undefined?c_o.getNode(c_1.node):(c_4?c_f.getById(c_4+'-shell'):c_d)||c_7;c_f.injectHtml(c_8,c_6,c_1.injectMode||(c_8==c_7?'inner bottom':'inner replace'));c_o.c_s(c_t);}};c_1.alwaysReplace===c_c&&c_4&&c_f.getById(c_4)?c_t():c_o.loadHtml(c_2,typeof c_3=='object'&&c_3?Uize.copyInto({},c_3,c_5):c_5);};c_h.performAjax=function(){};c_h.useDialog=function(c_n){var c_o=this,c_9=Uize.copyInto({},c_o.c_ba,c_n.widgetProperties),c_bb=c_9.parent||c_o,c_bc=c_9.name,c_bd=c_bb.children[c_bc],c_be=c_n.component,c_bf;if(c_be){var c_4=c_9.idPrefix||(c_bb.get('idPrefix')+'_'+c_bc);c_bf={name:c_be.name,rootNodeId:c_4,params:Uize.copyInto({idPrefix:c_4},c_be.params)};}function c_bg(c_bh){setTimeout(function(){function c_bi(c_bj,c_bk){var c_r=c_n[c_bj];c_r&&c_r.apply(0,c_bk);}
function c_bl(c_bm){var c_bk=[c_bm];c_bi(c_bm.name.toLowerCase()+'Handler',c_bk);c_bi('dismissHandler',c_bk);}function c_bn(c_bm){c_o.fire({name:'Dialog '+c_bm.name,dialogWidget:c_bm.source})}c_bd.unwire(c_bd.eventHandlersForUseDialog||{});c_bd.eventHandlersForUseDialog={'Submission Complete':function(c_bm){c_bi('submitHandler',[c_bm.result,c_bm])},Close:c_bl,Cancel:c_bl,'Before Show':c_bn,'After Show':c_bn,'Before Hide':c_bn,'After Hide':c_bn};c_bd.wire(c_bd.eventHandlersForUseDialog);c_bd.set(c_9);c_bd.set({shown:c_b});},0);}if(c_bd&&(c_bd.componentProfile==c_bf||Uize.Data.identical(c_bd.componentProfile,c_bf))){c_bg('subsequent');}else{var c_bo=c_bf&& !!c_bd;if(c_bo){c_bd.removeUi();c_bb.removeChild(c_bc);}function c_bp(){var c_bq=c_n.widgetClassName;Uize.module({required:c_bq,builder:function(){(c_bd=c_bb.children[c_bc])?c_bd.set(c_9):(c_bd=c_bb.addChild(c_bc,eval(c_bq),c_9));c_bd.componentProfile=c_bf;c_bd.wire(c_n.widgetEventHandlers);c_bd.insertOrWireUi();c_bg(c_bo?'refetched':'initial');}});}c_bf
?c_o.loadHtmlIntoNode({rootNodeId:c_bf.rootNodeId,injectMode:'inner bottom',alwaysReplace:c_c},Uize.copyInto({cp:c_bf.name},c_bf.params),{cache:'memory',callback:c_bp}):c_bp();}};c_h.wireUi=function(){var c_o=this;if(!c_o.isWired){c_o.c_s();c_a.prototype.wireUi.call(c_o);}};var c_br={yes:1,on:1,1:1,'true':1};c_g.launchPopup=c_h.launchPopup=function(c_n){if(!c_n)c_n={};if(c_n.width==c_e)c_n.width=850;if(c_n.height==c_e)c_n.height=600;var c_bs=window.screen;if(c_n.left==c_e)c_n.left=Math.max((c_bs.width-c_n.width-10)>>1,0);if(c_n.top==c_e)c_n.top=Math.max((c_bs.height-c_n.height-40)>>1,0);function c_bt(c_bu){return c_bu+'='+c_n[c_bu];}function c_bv(c_bu,c_bw){return(c_bu+'='+(c_br[c_n[c_bu]==c_e?c_bw:c_n[c_bu]+'']?'yes':'no'));}var c_bx=window.open(c_n.url||'',c_n.name==c_e?'popupWindow':c_n.name,[c_bt('width'),c_bt('height'),c_bt('top'),c_bt('left'),c_bv('toolbar',0),c_bv('location',0),c_bv('directories',0),c_bv('status',0),c_bv('menubar',0),c_bv('scrollbars',1),c_bv('resizable',1)].join(','));
c_bx&&c_bx.focus();return c_bx;};c_g.registerProperties({c_p:{name:'confirmDialog',value:{}},c_ba:'dialogProperties'});c_g.set({idPrefix:'page'});c_h.loadHtml=function(c_2,c_j){c_i(c_j)('');};c_h.showConfirm=function(c_n){this.c_k('confirm','confirm',c_n);};c_h.showInform=function(c_n){this.c_k('alert','info',c_n);};return c_g;}});


Uize.module({name:'UizeDotCom.Templates'});


Uize.module({name:'UizeDotCom.Templates.WidgetToGoTitle',builder:function(){var _a=function(){};_a.process=function(input){var output=[];
output.push('<div class="widgetHeader">\r\n	<div id="',input.idPrefix,'_menu_selector" title="Click to show/hide widget options..." class="widgetTitle">\r\n		<div class="logo"></div>\r\n		<div class="textShadow">',input.title,'</div>\r\n		<div class="textHighlight">',input.title,'</div>\r\n		<div class="textMain">',input.title,'</div>\r\n	</div>\r\n	<div id="',input.idPrefix,'_menu-palette" class="subMenuShell">\r\n		<a id="',input.idPrefix,'_menu-getThisWidget" href="javascript://" class="subMenuItem">GET THIS WIDGET</a>\r\n		<div class="divider"></div>\r\n		<a id="',input.idPrefix,'_menu-aboutThisWidget" href="javascript://" class="subMenuItem">About This Widget</a>\r\n		<a id="',input.idPrefix,'_menu-openInNewWindow" href="javascript://" class="subMenuItem">Open Widget in New Window</a>\r\n		<div class="divider"></div>\r\n		<a id="',input.idPrefix,'_menu-moreWidgets"  href="javascript://" class="subMenuItem">More UIZE Widgets...</a>\r\n		<a id="',input.idPrefix,'_menu-uize" href="javascript://" class="subMenuItem">UIZE JavaScript Framework</a>\r\n	</div>\r\n</div>\r\n\r\n');
return output.join('');};_a.input={idPrefix:'string',title:'string'};return _a;}});


Uize.module({name:'Uize.Fade',builder:function(b_a){var b_b,b_c='object',b_d=Uize.constrain;var b_e={},b_f=[],b_g=false,b_h;function b_i(){if((b_g= !!b_f.length)!= !!b_h)b_h=b_g?setInterval(b_j,10):clearInterval(b_h);}function b_j(){for(var b_k= -1,b_l;++b_k<b_f.length;)(b_l=b_f[b_k]).b_m?b_l.b_j():b_f.splice(b_k--,1);b_i();}function b_n(b_o){return b_o}var b_p=b_a.subclass(),b_q=b_p.prototype;b_q.b_r=function(){var b_s=this,b_o=b_t(b_s.b_u,b_s.b_v,b_s.b_w,b_s.b_x,b_s.b_y,b_s.b_o);if(b_o!=b_e)b_o!=b_s.b_o?b_s.set({b_o:b_o}):b_s.fire('Changed.value');};b_q.b_j=function(){var b_z=Math.min(((Date.now?Date.now(): +new Date)-this.b_A)/this.b_B,1);this.set({b_w:this.b_C?1-b_z:b_z});if(b_z==1){this.stop();this.fire('Done');}};b_q.stop=function(){this.set({b_m:false});};b_q.start=function(b_D){this.stop();this.set(Uize.copyInto({b_m:true},b_D));};var b_t=b_p.blendValues=function(b_E,b_F,b_G,b_x,b_y,b_H){if(b_E===b_F){return b_H!==b_b&&b_E===b_H?b_e:b_E;}else{if(Uize.isFunction(b_y)){b_G=b_y(b_G);b_y=b_b;}
if(typeof b_E==b_c&&b_E&& !(b_E instanceof RegExp)){var b_I=b_H&&typeof b_H==b_c,b_J=b_x&&typeof b_x==b_c,b_K=b_y&&typeof b_y==b_c,b_L=b_I?b_H:Uize.isArray(b_E)?[]:{},b_M;for(var b_N in b_E){var b_O=b_t(b_E[b_N],b_F[b_N],b_G,b_J?b_x[b_N]:b_x,b_K?b_y[b_N]:b_y,b_M=b_L[b_N]);if(b_I)b_I=b_O==b_e||(typeof b_O!=b_c&&b_O==b_M);if(b_O!=b_e)b_L[b_N]=b_O;}return b_I?b_e:b_L;}else{var b_L= !b_G?b_E:b_G==1?b_F: !b_x?b_E+(b_F-b_E)*b_G:b_G>0&&b_G<1?b_d(b_E+Math.round((b_F-b_E)*b_G/b_x)*b_x,b_E,b_F):b_E+Math.round((b_F-b_E)*b_G/b_x)*b_x;return b_H!==b_b&&b_L===b_H?b_e:b_L;}}};b_p.celeration=function(b_P,b_Q){var b_R=1-(b_P=b_P||0)-(b_Q=b_Q||0),b_S=2/(1+b_R),b_T=b_P?b_S/b_P:0,b_U=b_T/2,b_V=b_Q? -b_S/b_Q:0,b_W=b_V/2,b_X=b_P*b_P,b_Y;return(b_R>=1?b_n:function(b_o){return((b_o=(b_P?b_d(b_o*b_o,0,b_X)*b_U:0)+(b_R?b_S*b_d(b_o-b_P,0,b_R):0)+(b_Q?((b_S+(b_Y=b_d(b_o-b_P-b_R,0,b_Q))*b_W)*b_Y):0))>1?1:b_o);});};function b_Z(){this.set({b_y:this.b_P||this.b_Q?b_p.celeration(this.b_P,this.b_Q):null});}function b_0(){this.b_o=null;
this.b_r();}b_p.registerProperties({b_P:{name:'acceleration',onChange:b_Z},b_y:{name:'curve',onChange:b_0},b_Q:{name:'deceleration',onChange:b_Z},b_B:{name:'duration',value:2000},b_v:{name:'endValue',onChange:b_0,value:100},b_m:{name:'inProgress',onChange:function(){var b_s=this;if(b_s.b_m){b_s.b_A=Date.now?Date.now(): +new Date;b_s.fire('Start');b_s.b_o=b_s.b_w=null;b_s.b_j();b_f.push(b_s);b_i();}},value:false},b_w:{name:'progress',onChange:b_q.b_r,value:0},b_C:'reverse',b_u:{name:'startValue',onChange:b_0,value:0},b_x:'quantization',b_o:{name:'value',value:0}});return b_p;}});


Uize.module({name:'Uize.Widget.Button',required:'Uize.Node',builder:function(c_a){var c_b,c_c=true,c_d=false,c_e=Uize.Node;var c_f=c_a.subclass(null,function(){var c_g=this;function c_h(){if(c_g.isWired){c_g.c_i()||c_g.set({c_j:''});c_g.c_h();}}c_g.wire({'Changed.busyInherited':c_h,'Changed.enabledInherited':c_h});}),c_k=c_f.prototype;var c_l,c_m={},c_n={grayed:16,'':8,over:4,active:2,playing:1},c_o='(Grayed|Over|Active|Playing)',c_p=new RegExp(c_o),c_q=new RegExp('(?:(?:(\\S+)\\s+\\1'+c_o+'))','g'),c_r=new RegExp('\\S*'+c_o+'\\b','g'),c_s=/\b(disabled|over|active|playing)\b/,c_t={},c_u={mouseover:['over','Over'],mouseout:['','Out'],mousedown:['down','Down'],mouseup:['over','Up'],click:['over','Click'],dblclick:['over','Double Click']};c_k.c_v=c_d;c_k.c_i=function(c_w){var c_g=this;return!!(c_g.get('enabledInherited')&& !c_g.get('busyInherited')&&(c_w|| !c_g.c_x||c_g.c_y||c_g.c_z));};c_k.c_A=function(){this.c_B!=c_b&&this.isWired&&this.setNodeInnerHtml('text',this.c_B);};var c_h=c_k.c_h=function(){
var c_g=this;if(c_g.isWired){var c_C=c_g.c_C,c_D=c_g.get('enabledInherited'),c_E=c_g.get('busyInherited'),c_F=(!c_D?16:0)|(!c_g.c_j||c_E?8:0)|(c_g==c_l?4:0)|(c_g.c_j=='down'||c_g.c_x?2:0)|(c_g.c_G?1:0),c_H=c_g.c_I[c_F];if(c_H==c_b){for(var c_J= -1,c_K=c_g.c_K,c_L=c_K.length;++c_J<c_L;){var c_M=c_K[c_J];if(c_F&c_n[c_M]){c_H=c_M;break;}}c_g.c_I[c_F]=c_H;}if(c_g.c_N=='classes'){var c_O=c_C.className,c_P='';if(c_g.c_Q=='disambiguated'){var c_R=c_g.c_R;if(c_R==c_b){var c_S=c_O.match(c_q);if(c_S){c_R=c_S[c_S.length-1].split(' ',2)[0];}else{c_S=c_O.replace(c_r,'').match(/(\S+)\s*$/);if(c_S)c_R=c_S[c_S.length-1];}if(c_g.c_R=c_R=c_R||'')c_g.c_T=c_t[c_R]||(c_t[c_R]=new RegExp(c_R+'(\\s+'+c_R+c_o+')?'));}var c_U=c_H?' '+c_R+Uize.capFirstChar(c_H):'';c_P=c_R?c_O.replace(c_g.c_T,c_R+c_U):c_O.replace(c_p,'')+c_U;}else{var c_V=c_H=='grayed'?'disabled':c_H;c_P=c_s.test(c_O)?c_O.replace(c_s,c_V):c_O+(c_V?' ':'')+c_V;}if(c_P!=c_O)c_C.className=c_P;}else if(c_g.c_N=='frames'){
c_g.c_W.style.top='-'+(c_g.c_X.c_Y[c_H]*c_g.c_Z.height)+'px';}if(c_g.c_0&&Uize.Tooltip){var c_1=c_g.c_j=='over'&&c_D&& !c_g.c_x;c_1!=c_g.c_v&&Uize.Tooltip.showTooltip(c_g.c_0,c_g.c_v=c_1);}c_g.get('busyInherited')?c_e.setStyle(c_C,{cursor:'wait'}):c_e.showClickable(c_C,c_g.c_i());}};c_k.c_2=function(c_3){var c_g=this;if(c_g.isWired){var c_4=c_3.type,c_5=c_4=='click',c_i=c_g.c_i(c_4=='dblclick');if(!c_g.c_6){c_g.c_6=c_c;function c_2(c_3){c_g.c_2(c_3)}c_g.wireNode(c_g.c_C,{mouseout:c_2,mousedown:c_2,mouseup:c_2,dblclick:c_2});}if(c_5)c_3.cancelBubble=c_c;if(c_i){var c_7=c_u[c_4];c_g.set({c_j:c_7[0]});c_g.fire({name:c_7[1],domEvent:c_3});c_5&&(c_g.c_x?c_g.c_y:c_g.c_8)&&c_g.set({c_x:!c_g.c_x});}}};c_k.updateUi=function(){if(this.isWired){this.c_h();this.c_A();}};c_k.wireUi=function(){var c_g=this;if(!c_g.isWired){c_g.c_W=c_b;var c_C=c_g.c_C=c_g.getNode();if(c_C){var c_9=c_C.childNodes;if(c_9.length&&(c_9.length>1||c_9[0].nodeType!=3)&&(c_g.c_W=c_g.getNode('frames'))){c_g.c_N='frames';
c_g.c_Z=c_e.getDimensions(c_g.c_W.parentNode);}if(c_g.c_ba&&c_C.tagName=='A'&& !c_C.onclick)c_C.onclick=c_e.returnTrue;function c_2(c_3){c_g.c_2(c_3)}c_g.wireNode(c_C,{mouseover:c_2,click:c_2});c_g.c_B==c_b&&c_g.set({c_B:c_g.getNodeValue('text')});c_a.prototype.wireUi.call(c_g);}}};c_f.addChildButton=function(c_bb,c_bc){var c_g=this,c_bd;function c_be(){c_bd.wire('Click',function(c_bf){if(c_bc)typeof c_bc=='string'?c_g.fire(c_bc):c_bc(c_bf);c_g.fire(c_bf);});}if(c_g==c_f){c_bd=new c_f({idPrefix:c_bb,name:c_bb,c_ba:c_c});c_be();(window[c_bd.instanceId]=c_bd).wireUi();}else{c_bd=c_g.children[c_bb];if(!c_bd){c_bd=c_g.addChild(c_bb,c_f);c_be();}}return c_bd;};c_f.registerProperties({c_z:{name:'allowClickWhenSelected',onChange:c_h},c_8:'clickToSelect',c_y:{name:'clickToDeselect',onChange:c_h},c_Q:{name:'classNamingForStates',value:'disambiguated'},c_X:{name:'frameOrder',onChange:function(){var c_X=this.c_X;if(!c_X.c_Y){for(var c_bg= -1,c_bh=c_X.length,c_Y=c_X.c_Y={};++c_bg<c_bh;)c_Y[c_X[c_bg]]=c_bg;}},
value:['grayed','','over','active','playing']},c_ba:{name:'followLink',value:c_d},c_N:{name:'mode',value:'classes'},c_G:{name:'playing',onChange:c_h,value:c_d},c_x:{name:'selected',onChange:c_h,value:c_d},c_j:{name:'state',onChange:function(){var c_g=this;if(!c_g.c_j){if(c_l==c_g)c_l=c_b;}else if(c_g.c_j=='over'){c_l&&c_l!=c_g&&c_l.set({c_j:''});c_l=c_g;}c_g.isWired&&c_g.c_h();},value:''},c_K:{name:'statePrecedence',onChange:function(){var c_g=this,c_bi=c_g.c_K.c_bj||(c_g.c_K.c_bj=c_g.c_K.join(','));c_g.c_I=c_m[c_bi]||(c_m[c_bi]={});c_g.isWired&&c_g.c_h();},value:['playing','active','grayed','over','']},c_B:{name:'text',onChange:c_k.c_A},c_0:'tooltip'});return c_f;}});


Uize.module({name:'Uize.Widget.PopupPalette',required:['Uize.Node','Uize.Fade','Uize.Widget.Button'],builder:function(c_a){var c_b=true,c_c=false,c_d=null,c_e=Uize.Node;var c_f=c_a.subclass(null,function(){var c_g=this;c_g.fade=new Uize.Fade({duration:750,curve:Uize.Fade.celeration(0,1)});c_g.fade.wire({'Changed.value':function(){c_g.setNodeOpacity('palette',c_g.fade)},Done:function(){c_g.c_h(c_g.c_i)}});var c_j=c_g.c_j=c_g.c_k('selector',function(){c_g.toggle('shown')}),c_l;c_j.set({clickToDeselect:c_b});c_g.c_m();function c_n(c_o){var c_p=c_o.name=='Over',c_q=c_g.c_q;function c_r(){c_g.set({c_i:c_b})}if(c_p){if(c_q===c_b||c_q===0)c_r();else if(c_q>0)c_l=setTimeout(c_r,c_q);c_g.c_s()}else{clearTimeout(c_l);c_g.c_t();}}c_j.wire({Down:c_u,Over:c_n,Out:c_n});c_v[c_g.instanceId]=c_g;}),c_w=c_f.prototype,c_v={};c_w.c_m=function(){this.c_j.set({selected:this.c_i})};c_w.c_x=function(){return this.c_i&&(this.c_q!==c_c||this.c_y);};c_w.c_s=function(){this.c_x()&&this.c_z();this.fire('Over');};c_w.c_t=function(){
this.c_x()&&this.c_A();this.fire('Out');};c_w.c_k=Uize.Widget.Button.addChildButton;c_w.c_h=function(c_B){var c_g=this;c_g.displayNode('palette',c_B);c_B&&c_g.setNodeStyle('palette',{filter:''});c_g.fire({name:'Palette '+(c_B?'Shown':'Dismissed'),bubble:c_b});};c_w.c_z=function(){var c_g=this;if(c_g.c_C){clearTimeout(c_g.c_C);c_g.c_C=null;}};c_w.c_A=function(){var c_g=this;c_g.c_z();c_g.c_C=setTimeout(function(){c_g.set({c_i:c_c})},250);};c_w.kill=function(){delete c_v[this.instanceId];c_a.prototype.kill.call(this);};c_w.wireUi=function(){var c_g=this;if(!c_g.isWired){c_g.wireNode('palette',{mousedown:c_u,mouseup:function(c_o){c_g.c_D&&c_o.target!=c_g.getNode('palette')&&c_g.set({c_i:c_c});},mouseover:function(){c_g.c_s()},mouseout:function(){c_g.c_t()}});c_g.wireNode('paletteClose','click',function(){c_g.set({c_i:c_c})});if(c_g.c_E!='none'){var c_F=document.body,c_G=c_g.getNode('palette');if(c_G&&c_G.parentNode!=c_F){c_F.insertBefore(c_G,c_F.childNodes[0]);c_g.setNodeStyle(c_G,{zIndex:10000,
position:'absolute',left:'',top:'',right:'',bottom:'',width:c_g.getNodeStyle(c_G,'width')});}}c_a.prototype.wireUi.call(c_g);}};c_f.registerProperties({c_H:{name:'exclusive',value:c_b},c_y:{name:'hideWhenOut',value:c_c},c_D:{name:'hideOnClick',value:c_b},c_E:{name:'positioning',value:'none'},c_i:{name:'shown',onChange:function(){var c_g=this,c_i=c_g.c_i,c_E=c_g.c_E;c_g.c_j&&c_g.c_m();if(c_g.isWired){c_g.c_z();if(c_i){c_g.fire('Before Palette Shown');c_g.c_H&&c_I(c_g);if(c_E!='none'){var c_G=c_g.getNode('palette'),c_J=Uize.isFunction(c_E)?c_E(c_G):c_g.c_j.getNode();function c_K(c_L){c_g.showNode('palette',!c_L);c_g.displayNode('palette',c_L);}if(c_e.isNode(c_J)){c_K(c_b);c_e.setAbsPosAdjacentTo(c_G,c_J);c_K(c_c);}}}if(c_g.fade.get('duration')>0){c_i&&c_g.displayNode('palette');c_g.fade.start({startValue:c_i?0:1,endValue:c_i?1:0});}else{c_g.c_h(c_i);}}},value:c_c},c_q:{name:'showWhenOver',value:c_c}});function c_I(c_M){for(var c_N in c_v){var c_O=c_v[c_N];c_O!=c_M&&c_O.c_H&&c_O.set({c_i:c_c});}}
function c_u(){c_P=c_b}if(typeof navigator!='undefined'){var c_P=c_c,c_Q=document.onmousedown;document.onmousedown=function(c_o){if(!c_o)c_o=event;c_P?(c_P=c_c):c_I();Uize.isFunction(c_Q)&&c_Q(c_o);};}return c_f;}});


Uize.module({name:'UizeDotCom.WidgetToGoPage',superclass:'Uize.Widget.Page',required:['Uize.Node','UizeDotCom.Templates.WidgetToGoTitle','Uize.Widget.PopupPalette'],builder:function(d_a){var d_b=d_a.subclass(null,function(){this.addChild('menu',Uize.Widget.PopupPalette,{hideWhenOut:true,positioning:'absolute'}).fade.set({duration:0});}),d_c=d_b.prototype;d_c.wireUi=function(){var d_d=this;if(!d_d.isWired){Uize.Node.injectHtml(document.body,UizeDotCom.Templates.WidgetToGoTitle.process({idPrefix:d_d.get('idPrefix'),title:document.title}));Uize.module({required:[d_d.d_e,d_d.d_f],builder:function(){d_d.addChild('widget',eval(d_d.d_e),{built:false,html:eval(d_d.d_f)}).insertOrWireUi();}});var d_g=d_d.children.menu,d_h='../'+d_d.d_i.toLowerCase().replace(/\s+/g,'-')+'.html';function d_j(d_k,d_l,d_m,d_n,d_o){page.launchPopup({name:d_k,url:d_l,width:d_m,height:d_n,toolbar:d_o,location:d_o,directories:d_o,status:d_o,menubar:d_o,scrollbars:d_o,resizable:d_o});}function d_p(d_q,d_l){
d_g.wireNode(d_q,'click',function(){d_j(null,d_l,1010,690,1)});}d_p('getThisWidget',d_h);d_p('aboutThisWidget',d_h);d_p('moreWidgets','../../javascript-widgets.html');d_p('uize','../../index.html');d_g.wireNode('openInNewWindow','click',function(){var d_r=Uize.Node.getDimensions(window);d_j('',location.href,d_r.width,d_r.height,0);});d_a.prototype.wireUi.call(d_d);}};d_b.registerProperties({d_i:'title',d_e:'widgetToGoClass',d_f:'widgetToGoHtml'});return d_b;}});


Uize.module({name:'Uize.Node.Event',builder:function(){var _a=function(_b){return _b||event};_a.abort=function(_b){_a.preventDefault(_b||(_b=event));_a.stopPropagation(_b);};_a.charCode=function(_b){_b||(_b=event);if(_b.ctrlKey||_b.altKey||_b.which<1)return 0;return'charCode'in _b?_b.charCode:_a.keyCode(_b);};_a.fix=function(_b){_b||(_b=event);_b.target=_a.target(_b);_b.relatedTarget=_a.relatedTarget(_b);_b.charCode=_a.charCode(_b);_b.keyCode=_a.keyCode(_b);_b.preventDefault||(_b.preventDefault=_c);_b.stopPropagation||(_b.stopPropagation=_d);return _b;};var _e={Backspace:8,Delete:46,Insert:45,Enter:13,Escape:27,Space:32,Tab:9,PageUp:33,PageDown:34,End:35,Home:36,LeftArrow:37,RightArrow:39,UpArrow:38,DownArrow:40};function _f(_g,_h){_a['isKey'+_g]=function(_b){return _a.keyCode(_b)==_h};}for(var _g in _e)_f(_g,_e[_g]);_a.keyCode=function(_b){return'which'in(_b||(_b=event))?_b.which:_b.keyCode;};function _c(){this.preventDefault?this.preventDefault():(this.returnValue=false);}
_a.preventDefault=function(_b){_c.call(_b||event)};_a.relatedTarget=function(_b){return('relatedTarget'in(_b||(_b=event))?_b.relatedTarget:(_b.type=='mouseout'?_b.toElement:_b.fromElement));};function _d(){this.stopPropagation?this.stopPropagation():(this.cancelBubble=true);}_a.stopPropagation=function(_b){_d.call(_b||event)};_a.target=function(_b){return(_b||(_b=event)).target||_b.srcElement;};return _a;}});


Uize.module({name:'Uize.Tooltip',required:['Uize.Node','Uize.Fade'],builder:function(){var _a=function(){},_b=true,_c=false,_d,_e=Uize.Node;var _f=Uize.getGuid(),_g=[],_h,_i=16;function _j(_k){return _e.getById(Uize.isFunction(_k)?_k():_k);}function _l(){_m()}function _n(_o){if(_o!=_h){if(_o){if(_h){_p.stop();_q();}if(!_o._r){_e.wire(document.body,'scroll',_l,_f);_e.wire(document.documentElement,'mousemove',_l,_f);}_h=_o;_e.setStyle(_h._s,{position:'absolute',zIndex:5000,left:-50000,top:-50000});_e.display(_h._s);_m();}else{_p.get('duration')>0?_p.start():_q();}}else if(_o){_p.stop();_e.setOpacity(_h._s,1);}}_a.showTooltip=function(_k,_t,_r){if(_k=_j(_k)){if(_t!==_c){_g.push({_s:_k,_r:_r});}else{for(var _u=_g.length;--_u> -1;)if(_g[_u]._s==_k)break;_u> -1&&_g.splice(_u,1);}_n(_g[_g.length-1]);}};_a.hideTooltip=function(_k){_a.showTooltip(_k,_c)};var _m=_a.positionTooltip=function(_k,_v){_h&&(_k===_d?(_k=_h._s):_h._s==_j(_k))&&_e.setAbsPos(_k,_e.getEventAbsPos(_v),_i);};
var _p=_a.fade=new Uize.Fade({duration:0});function _q(){_h._r||_e.unwireEventsByOwnerId(_f);_e.display(_h._s,_c);_e.setOpacity(_h._s,1);_h=null;}_p.wire({'Changed.value':function(){_e.setOpacity(_h._s,1-_p.get('progress'))},Done:_q});return _a;}});


Uize.module({name:'Uize.Templates'});


Uize.module({name:'Uize.Date',builder:function(){var _a=function(_b,_c,_d,_e,_f,_g,_h){var _i=new Date(+_b+(_b<100&&400),(+_c||1)-1,+_d||1,+_e||0,+_f||0,+_g||0,+_h||0);_b<100&&_i.setFullYear(_b);return _i;},_j;function _k(_l){return isNaN(_l)?'??':(_l<10?'0':'')+_l}function _m(_l){return(isNaN(_l)?'???':(_l<10?'00':_l<100?'0':'')+_l);}function _n(_l){return(isNaN(_l)?'????':(_l<10?'000':_l<100?'00':_l<1000?'0':'')+_l);}var _o={ms:1,seconds:1000,minutes:60000,hours:3600000,days:86400000,weeks:604800000,months:2629743840,years:31556926080};var _p=_a.convert=function(_q,_r,_s){return _q*_o[_r+'']/_o[_s+''];};var _t=_a.resolve=function(_i,_u){return(_i instanceof Date?_i:_i==null||_i===''?(_u!==_j?_u:new Date):typeof _i=='string'?_a.fromIso8601(_i)||new Date(_i):new Date(+_i));};_a.equal=function(_v,_w,_x){return _a.inRange(_v,_a.getRangeAround(_w,_x||'day'));};_a.toIso8601=function(_i){return(_n((_i=_t(_i)).getFullYear())+'-'+_k(_i.getMonth()+1)+'-'+_k(_i.getDate()));};_a.fromIso8601=function(_y){
var _z=_y.match(/(\d{2,})-(\d\d?)-(\d\d?)(?:\D|$)/);return(_z?_a(+_z[1]+(_z[1].length<3)*1900,_z[2],_z[3]):_j);};var _A={date:'Invalid Date',YYYY:'????',YY:'??',MM:'??',monthNo:'?',monthName:'?????????',shortMonthName:'???',DD:'??',dayNo:'?',dayNoSuffix:'??',dayName:'????????',shortDayName:'???',hh:'??',h12:'?',hh12:'??',mm:'??',minutes:'?',ss:'??',seconds:'?',zzz:'???',milliseconds:'?',ampm:'??'};_a.format=_a.toPretty=function(_i,_B){var _C=_A;if(!isNaN(_i=_t(_i))){var _D=_n(_i.getFullYear()),_E=_i.getMonth()+1,_d=_i.getDate(),_F=_d%10,_G=_i.getDay(),_H=_i.getHours(),_I=_H>11,_J=(_H-(_I&&12))||12,_f=_i.getMinutes(),_g=_i.getSeconds(),_h=_i.getMilliseconds();_C={date:_i,YYYY:_D,YY:_D.slice(-2),MM:_k(_E),monthNo:_E,monthName:_a.monthNames[_E-1],shortMonthName:_a.shortMonthNames[_E-1],DD:_k(_d),dayNo:_d,dayNoSuffix:_a.dayNoSuffixes[(_F<4&&Math.floor(_d/10)%10!=1)*_F],dayName:_a.dayNames[_G],shortDayName:_a.shortDayNames[_G],hh:_k(_H),h12:_J,hh12:_k(_J),mm:_k(_f),minutes:_f,ss:_k(_g),seconds:_g,zzz:_m(_h),
milliseconds:_h,ampm:_I?'pm':'am'};}return Uize.substituteInto(_B||'{dayName}, {dayNo}{dayNoSuffix} {monthName} {YYYY}',_C,'{KEY}');};_a.getRangeAround=function(_i,_K){var _L=new Date(_i=_t(_i)),_M=new Date(_L);function _N(_O,_P,_Q){_L[_O](_P);_M[_O](_Q);}function _R(_S,_T){var _U=Math.floor(_i['get'+_S]()/_T)*_T;_N('set'+_S,_U,_U+_T-1);}switch(_K||(_K='month')){case'millennium':case'century':case'decade':_R('FullYear',_K=='millennium'?1000:_K=='century'?100:10);case'year':case'quarter':_K=='quarter'?_R('Month',3):_N('setMonth',0,11);case'month':case'week':if(_K=='week'){var _V=_i.getDate()-_i.getDay();_N('setDate',_V,_V+6);}else{_N('setDate',1,_a.getDaysInMonth(_M.getMonth(),_M.getFullYear()));}case'day':case'am/pm':_K=='am/pm'?_R('Hours',12):_N('setHours',0,23);case'hour':_N('setMinutes',0,59);case'minute':_N('setSeconds',0,59);case'second':_N('setMilliseconds',0,999);}return{minValue:_L,maxValue:_M};};_a.inRange=function(_i,_W){if(typeof _i!='number')_i= +_t(_i);
return _i>=_t(_W.minValue,-Infinity)&&_i<=_t(_W.maxValue,Infinity);};_a.isLeapYear=function(_b){return _b%4==0&&(_b%100!=0||_b%400==0);};_a.getDaysInMonth=function(_c,_b){return 30+((2773>>_c)&1)-(_c==1&&(2-_a.isLeapYear(_b)));};_a.isRecent=function(_i,_X,_Y){return _a.inRange(_i,{minValue:_t(_Y)-_p(_X,'days','ms')});};_a.dayNames=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];_a.dayNoSuffixes=['th','st','nd','rd'];_a.monthNames=['January','February','March','April','May','June','July','August','September','October','November','December'];_a.shortDayNames=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'];_a.shortMonthNames=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];return _a;}});


Uize.module({name:'Uize.Date.Formatter',builder:function(){var _a=function(){},_b=Uize.Date;var _c,_d={YYYY:'\\d{4}',YY:'\\d\\d',MM:'1[0-2]|0[1-9]',monthNo:'1[0-2]|0?[1-9]',DD:'30|31|[1-2]\\d|0[1-9]',dayNo:'30|31|[1-2]\\d|0?[1-9]',dayNoSuffix:_b.dayNoSuffixes.join('|'),hh:'[0-1]\\d|2[0-3]',h12:'1[0-2]|0?[1-9]',hh12:'1[0-2]|0[1-9]',mm:'[0-5]\\d',minutes:'[0-5]?\\d',ss:'[0-5]\\d',seconds:'[0-5]?\\d',zzz:'\\d{3}',milliseconds:'\\d{1,3}',ampm:'am|pm'},_e={monthName:1,shortMonthName:1,dayName:1,shortDayName:1},_f=String.fromCharCode(7);function _g(_h,_i){_i=_i.toLowerCase();for(var _j= -1,_k=_h.length;++_j<_k;)if(_i==_h[_j].toLowerCase())return _j;return-1;}_a.format=_a.toPretty=_b.format;_a.parse=function(_l,_m){var _n;if(typeof _l=='object'&&_l&& !(_l instanceof Date))_l=_l.valueOf();if(_l instanceof Date)return _l;if(_l==null||_l=='')return;if(typeof _l=='number')return new Date(_l);if(!_m)return _b.resolve(_l);for(_n in _e)_d[_n]=null;if(!_c){var _o=[];for(_n in _d)_o.push(_n);
_c=new RegExp('\\{('+_o.join('|')+')\\}','g');}var _p=[],_q=0,_r=new RegExp(Uize.escapeRegExpLiteral(_m.replace(_c,function(_s,_n){_p.push(_n);return _f;})).replace(/\s+/g,'\\s+').replace(/\x07/g,function(){return('\\s*('+(_d[_n=_p[_q++]]||(_d[_n]=_b[_n+'s'].join('|')))+')\\s*');}),'i'),_t=(_l+'').match(_r);if(_t){var _u=0,_v=1,_w=1,_x,_y=0,_z=0,_A=0,_B=0,_C=false;for(var _D=0,_E=_t.length;++_D<_E;){var _F=_t[_D];switch(_p[_D-1]){case'YYYY':_u= +_F;break;case'YY':_u=1900+ +_F;break;case'MM':case'monthNo':_v= +_F;break;case'monthName':_v=_g(_b.monthNames,_F)+1;break;case'shortMonthName':_v=_g(_b.shortMonthNames,_F)+1;break;case'DD':case'dayNo':_w= +_F;break;case'hh':_x= +_F;break;case'h12':case'hh12':_y= +_F;break;case'mm':case'minutes':_z= +_F;break;case'ss':case'seconds':_A= +_F;break;case'zzz':case'milliseconds':_B= +_F;case'ampm':_C=/^pm$/i.test(_F)}}return _b(_u,_v,_w,_x!==undefined?_x:_y*(_y!=12)+_C*12,_z,_A,_B);}};return _a;}});


Uize.module({name:'Uize.Widget.Calendar',required:['Uize.Widget.Button','Uize.Date','Uize.Date.Formatter'],builder:function(c_a){var c_b=true,c_c=false,c_d=null,c_e=Uize.Date,c_f=c_e.dayNames,c_g=c_e.monthNames;var c_h=c_a.subclass(c_d,function(){var c_i=this;c_i.c_j=c_i.c_k('nextMonth',function(){c_i.set({c_l:c_i.c_l+1})});c_i.c_m=c_i.c_k('previousMonth',function(){c_i.set({c_l:c_i.c_l-1})});c_i.c_n=c_i.c_k('nextYear',function(){c_i.set({c_o:c_i.c_o+1})});c_i.c_p=c_i.c_k('previousYear',function(){c_i.set({c_o:c_i.c_o-1})});c_i.c_q=c_b;c_i.c_r();}),c_s=c_h.prototype;c_s.c_k=Uize.Widget.Button.addChildButton;var c_t=c_s.c_t=function(){var c_i=this,c_u={minValue:c_i.c_v,maxValue:c_i.c_w};c_i.c_x&& !c_e.inRange(c_i.c_x,c_u)&&c_i.set({c_x:c_d});var c_y=c_i.c_x||new Date;if(!c_e.inRange(c_y,c_u))c_y=c_i.c_v||c_i.c_w;c_i.set({c_l:c_y.getMonth(),c_o:c_y.getFullYear()});};var c_r=c_s.c_r=function(){var c_i=this;if(c_i.c_q){var c_z=new Date(c_i.c_o,c_i.c_l,1),c_A=c_e.getRangeAround(c_z,'month'),
c_B=c_e.getRangeAround(c_z,'year'),c_v=c_i.c_v,c_w=c_i.c_w;function c_C(c_D,c_E){c_D.set({enabled:c_E?'inherit':c_c});}c_C(c_i.c_m,!c_v||c_v<c_A.minValue);c_C(c_i.c_j,!c_w||c_w>c_A.maxValue);c_C(c_i.c_p,!c_v||c_v<c_B.minValue);c_C(c_i.c_n,!c_w||c_w>c_B.maxValue);}};c_s.c_F=function(){this.isWired&&this.setNodeValue('month',c_g[this.c_l]);};c_s.c_G=function(){this.isWired&&this.setNodeValue('year',this.c_o);};var c_H=c_s.c_H=function(){var c_i=this;if(c_i.isWired){function c_I(c_y,c_J){return(c_y?c_y.getFullYear()*10000+(c_y.getMonth()+1)*100+c_y.getDate():c_J);}var c_x=c_i.c_x,c_v=c_i.c_v,c_w=c_i.c_w,c_o=c_i.c_o,c_l=c_i.c_l,c_K=c_e.getDaysInMonth(c_l,c_o),c_L=new Date(c_o,c_l,1),c_M=c_I(c_L),c_N=Uize.constrain(c_I(c_v,0)-c_M+1,1,c_K+1),c_O=Uize.constrain(c_I(c_w,Infinity)-c_M+1,-1,c_K),c_P=c_i.c_P;if(!c_P||c_x!=c_P.c_x||c_l!=c_P.c_l||c_o!=c_P.c_o||c_N!=c_P.c_N||c_O!=c_P.c_O){if(c_P){for(var c_Q=0,c_R;++c_Q<32;){c_i.unwireNode(c_R='day'+c_Q);c_i.flushNodeCache(c_R);}}if(!c_P)c_P=c_i.c_P={};c_P.c_x=c_x;
c_P.c_l=c_l;c_P.c_o=c_o;c_P.c_N=c_N;c_P.c_O=c_O;var c_S=['<table class="calendarGrid" cellpadding="0" cellspacing="0"><tr>'];for(var c_Q= -1;++c_Q<7;)c_S.push('<th title="'+c_f[c_Q]+'">'+c_f[c_Q].charAt(0)+'</th>');c_S.push('</tr><tr>');var c_T=c_I(c_x,c_d),c_U=c_i.get('idPrefix'),c_Q=1-c_L.getDay();for(var c_V= -1;++c_V<6;){c_S.push('<tr>');for(var c_W= -1;++c_W<7;){if(c_Q>0&&c_Q<=c_K){var c_X=c_I(new Date(c_o,c_l,c_Q))==c_T;c_S.push(c_Q>=c_N&&c_Q<=c_O?('<td'+(c_X?' class="selected"':'')+'><a href="javascript://" id="'+c_U+'-day'+c_Q+'" style="display:block; width:100%; text-align:center;">'+c_Q+'</a></td>'):('<td class="'+(c_X?'selected ':'')+'grayed">'+c_Q+'</td>'),'</td>');}else{c_S.push('<td>&nbsp;</td>');}c_Q++;}c_S.push('</tr>');}c_S.push('</table>');c_i.setNodeInnerHtml('grid',c_S.join(''));function c_Y(c_Q){c_i.wireNode('day'+c_Q,'click',function(){c_i.set({c_x:new Date(c_o,c_l,c_Q)})});}for(var c_Q=c_K+1;--c_Q>0;)c_Y(c_Q);}}else{c_i.c_P=c_d;}};c_s.updateUi=function(){this.c_F();this.c_G();
this.c_H();};function c_Z(c_x){return c_e.Formatter.parse(c_x,this.c_0)||null;}c_h.registerProperties({c_0:'displayFormat',c_w:{name:'maxValue',conformer:c_Z,onChange:[c_t,c_H,c_r]},c_v:{name:'minValue',conformer:c_Z,onChange:[c_t,c_H,c_r]},c_l:{name:'month',conformer:function(c_x){var c_1=Math.floor(c_x/12);c_1&&this.set({c_o:this.c_o+c_1});return((c_x%12)+12)%12;},onChange:[c_s.c_F,c_H,c_r]},c_2:{name:'snapViewOnValueChange',value:c_b},c_x:{name:'value',conformer:c_Z,value:new Date,onChange:[function(){this.c_2&&this.c_t()},c_H,c_r]},c_o:{name:'year',onChange:[c_s.c_G,c_H,c_r]}});return c_h;}});


Uize.module({name:'Uize.Templates.Calendar',builder:function(){var _a=function(){};_a.process=function(input){var output=[];
output.push('<div class="calendarContainer">\r\n	<div id="',input.idPrefix,'-controls" class="calendarControls">\r\n		<div id="',input.idPrefix,'-indicator" class="calendarIndicator">\r\n			<span id="',input.idPrefix,'-month" class="monthIndicator">Month</span>\r\n			<span id="',input.idPrefix,'-year" class="yearIndicator">Year</span>\r\n		</div>\r\n		<a href="javascript://" id="',input.idPrefix,'_previousMonth" class="calendarControl previousMonth" title="previous month">&#9668;</a>\r\n		<a href="javascript://" id="',input.idPrefix,'_nextMonth" class="calendarControl nextMonth" title="next month">&#9658;</a>\r\n		<a href="javascript://" id="',input.idPrefix,'_previousYear" class="calendarControl previousYear" title="previous year">&laquo;</a>\r\n		<a href="javascript://" id="',input.idPrefix,'_nextYear" class="calendarControl nextYear" title="next year">&raquo;</a>\r\n	</div>\r\n	<div id="',input.idPrefix,'-grid" class="calendarGrid"></div>\r\n</div>\r\n');return output.join('');};_a.input={idPrefix:'string'
};return _a;}});


Uize.module({name:'UizeDotCom.WidgetToGoPage.Calendar'});

Uize.module ({name:'UizeDotCom.WidgetToGoPage.Calendar.library'});

