/*______________
|       ______  |   B U I L T     O N     U I Z E     F R A M E W O R K
|     /      /  |   ---------------------------------------------------
|    /    O /   |   This JavaScript application is developed using the object
|   /    / /    |   oriented UIZE JavaScript framework as its foundation.
|  /    / /  /| |
| /____/ /__/_| |    ONLINE : http://www.uize.com
|          /___ |   LICENSE : Available under MIT License or GNU General Public License
|_______________|             http://www.uize.com/license.html
*/

/*______________
|       ______  |   U I Z E    J A V A S C R I P T    F R A M E W O R K
|     /      /  |   ---------------------------------------------------
|    /    O /   |    MODULE : UizeDotCom.WidgetToGoPage.Calendar.library Library Module
|   /    / /    |
|  /    / /  /| |    ONLINE : http://www.uize.com
| /____/ /__/_| | COPYRIGHT : (c)2009-2012 UIZE
|          /___ |   LICENSE : Available under MIT License or GNU General Public License
|_______________|             http://www.uize.com/license.html
*/

/*?
	Introduction
		The =UizeDotCom.WidgetToGoPage.Calendar.library= module is a library module that bundles together all the JavaScript modules needed by the calendar Widgets To Go widget.

		*DEVELOPERS:* `Chris van Rensburg`
*/



Uize.module({name:'UizeDotCom'});


Uize.module({name:'Uize.Class',builder:function(a_a){var a_b,a_c='string',a_d='object',a_e=Uize,a_f=a_e.clone,a_g=a_e.copyInto,a_h=a_e.forEach,a_i=a_e.getClass,a_j=a_e.getGuid,a_k=a_e.globalEval,a_l=a_e.isArray,a_m=a_e.isFunction,a_n=a_e.isInstance,a_o=a_e.isObject,a_p=a_e.noNew,a_q=a_e.pairUp;var a_r=[],a_s={};var a_t=a_u(function(){},function(){this.instanceId=a_j();},function(a_v){a_v||(a_v=a_s);var a_w={},a_x=this.Class.a_x,a_y,a_z;for(a_y in a_x){if(a_y in a_v)a_w[a_y]=a_v[a_y];else if((a_z=a_x[a_y])!==a_b)a_w[a_y]=a_z;}for(a_y in a_v)a_y in a_w||(a_w[a_y]=a_v[a_y]);this.set(a_w);}),a_A=a_t.prototype,a_B=a_t.nonInheritableStatics;function a_C(a_D,a_E){var a_t=a_i(a_D);return(a_t.a_F[a_E]||a_t.a_G[a_E]);}function a_H(a_D,a_E){var a_I=a_C(a_D,a_E);return a_I?a_I.a_J:a_E;}a_t.a_K=a_A.a_K=function(a_L,a_M){if(a_L.charCodeAt(0)==67&& !a_L.indexOf('Changed.')){var a_D=this,a_N=a_L.slice(8),a_I=a_C(a_D,a_N);if(a_I&&a_N!=a_I.a_O)a_L='Changed.'+(a_N=a_I.a_O);a_M(a_L);(a_D.a_P||(a_D.a_P={}))[a_N]=
a_D.a_Q&&a_D.a_Q[a_L];}else{a_M(a_L);}};a_t.wire=a_A.wire=function(a_R,a_S){var a_D=this;if(arguments.length==2){a_D.a_K(a_R,function(a_L){var a_Q=a_D.a_Q||(a_D.a_Q=a_D.eventHandlers={});(a_Q[a_L]||(a_Q[a_L]=[])).push({a_L:a_L,a_S:a_m(a_S)?a_S:typeof a_S==a_c?new Function(a_S):function(a_T){a_S.fire(a_T)},a_U:a_S});});}else if(a_o(a_R)){for(var a_L in a_R)this.wire(a_L,a_R[a_L]);}};a_t.fire=a_A.fire=function(a_T){if(typeof a_T!=a_d)a_T={name:a_T};var a_D=this,a_Q=a_D.a_Q;if(a_Q){var a_V=a_Q[a_T.name],a_W=a_Q['*'];if(a_V||a_W){a_T.source||(a_T.source=a_D);var a_X=a_W&&a_V?a_W.concat(a_V):a_W||a_V,a_Y=a_X.length;if(a_Y==1){a_X[0].a_S(a_T);}else if(a_Y==2){var a_Z=a_X[0].a_S,a_0=a_X[1].a_S;a_Z(a_T);a_0(a_T);}else{if(!a_W|| !a_V)a_X=a_X.concat();for(var a_1= -1;++a_1<a_Y;)a_X[a_1].a_S(a_T);}}}if(a_T.bubble&&a_D.parent&&a_n(a_D)){a_T.source||(a_T.source=a_D);a_D.parent.fire(a_T);}return a_T;};a_t.unwire=a_A.unwire=function(a_R,a_S){var a_D=this,a_Q=a_D.a_Q;if(a_Q){if(a_o(a_R)){for(var a_L in a_R)
a_D.unwire(a_L,a_R[a_L]);}else{a_D.a_K(a_R,function(a_L){var a_2=a_Q[a_L];if(a_2){if(a_S){for(var a_1=a_2.length;--a_1>=0;)a_2[a_1].a_U==a_S&&a_2.splice(a_1,1);}(a_S&&a_2.length)||delete a_Q[a_L];}});}}};a_t.get=a_A.get=function(a_y){if(typeof a_y==a_c){return this[a_H(this,a_y)];}else{var a_D=this,a_3={};if(!a_y){var a_t=a_i(a_D),a_G=a_t.a_G;for(var a_4 in a_G)a_3[a_G[a_4].a_O]=a_D[a_4];}else if(a_l(a_y)){for(var a_5= -1,a_6=a_y.length;++a_5<a_6;){var a_7=a_y[a_5];a_3[a_7]=a_D[a_H(a_D,a_7)];}}else{for(var a_7 in a_y)a_3[a_7]=a_D[a_H(a_D,a_7)];}return a_3;}};a_t.registerProperties=function(a_8){var a_D=this,a_G=a_D.a_G,a_F=a_D.a_F;for(var a_4 in a_8){var a_9=a_8[a_4],a_ba=a_o(a_9),a_N=(a_ba?a_9.name:a_9)||a_4,a_bb=a_N,a_I=a_G[a_4]={a_J:a_4};if(a_N.indexOf('|')> -1){var a_bc=a_N.split('|');a_bb=a_bc[0];a_e.lookup(a_bc,a_I,a_F);}else{a_F[a_N]=a_I;}a_I.a_O=a_bb;if(a_ba){if(a_9.onChange)a_I.a_bd=a_9.onChange;if(a_9.conformer)a_I.a_be=a_9.conformer;a_D[a_4]=a_9.value;}}a_D.a_x=this.get();};
a_t.set=a_A.set=function(a_v){if(arguments.length>1)a_v=a_q.apply(0,arguments);var a_D=this,a_bf=a_n(a_D),a_t=a_bf?a_D.Class:a_D,a_F=a_t.a_F,a_G=a_t.a_G,a_I,a_bg,a_bh,a_bi,a_P=a_bf&&a_D.a_P,a_bj=a_P&&a_P['*'],a_bk,a_bl,a_4,a_N,a_bm,a_bn,a_bo;for(var a_E in a_v){a_bn=a_v[a_E];if(a_I=a_F[a_E]||a_G[a_E]){a_4=a_I.a_J;a_N=a_I.a_O;}else{(a_bm||(a_bm={}))[a_4=a_N=a_E]=a_I=a_bf?{}:{value:a_bn};}if(a_bf)(a_bo||(a_bo={}))[a_N]=a_I.a_be?(a_bn=a_I.a_be.call(a_D,a_bn,a_D[a_4])):a_bn;if(a_bn!==a_D[a_4]){if(a_bf){a_bj&&((a_bk||(a_bk={}))[a_N]=a_bn);a_P&&a_P[a_N]&&(a_bl||(a_bl=[])).push(a_N);function a_bp(a_bi){if(a_m(a_bi)){if(!a_bg){a_bg=[];a_bh=a_D.instanceId+'_handlerAlreadyAdded';}if(!a_bi[a_bh]){a_bi[a_bh]=1;a_bg.push(a_bi);}}else if(typeof a_bi==a_c){a_bp(a_D[a_bi]);}else if(a_l(a_bi)){a_h(a_bi,a_bp);}}a_I.a_bd&&a_bp(a_I.a_bd);}a_D[a_4]=a_bn;}}a_bm&&a_t.registerProperties(a_bm);if(a_bf){if(a_bg){for(var a_1= -1,a_bq=a_bg.length;++a_1<a_bq;){delete(a_bi=a_bg[a_1])[a_bh];a_bi.call(a_D,a_bo);}}
a_bk&&a_D.fire({name:'Changed.*',properties:a_bk});if(a_bl){for(var a_br= -1,a_bs=a_bl.length;++a_br<a_bs;)a_D.fire('Changed.'+a_bl[a_br]);}}else{a_t.a_x=this.get();}};a_t.toggle=a_A.toggle=function(a_bt){var a_bu= !this.get(a_bt);this.set(a_bt,a_bu);return a_bu;};a_A.kill=function(){var a_bv=this.instanceId;a_k('if(typeof '+a_bv+'!=\'undefined\')'+a_bv+'=null');};function a_u(a_t,a_bw,a_bx){function a_by(){var a_bz=[],a_bA=a_e.toString;a_h(this.get(),function(a_bn,a_bt){a_bz.push(a_bt+' : '+(a_bn&&(a_n(a_bn)||a_m(a_bn))?a_bA.call(a_bn):a_bn));});return a_bA.call(this)+'\n\n'+a_bz.sort().join('\n');}function a_bB(){return this[a_H(this,'value')];}var a_A=a_t.prototype,a_bC=a_p(function(){for(var a_bD= -1,a_bE=a_bF.length;++a_bD<a_bE;)a_bF[a_bD].apply(this,arguments);for(var a_bG= -1,a_bH=a_bI.length;++a_bG<a_bH;)a_bI[a_bG].apply(this,arguments);}),a_bJ=a_bC.prototype;var a_bn,a_bK=a_t.nonInheritableStatics||a_s;for(var a_y in a_t)if(!a_bK[a_y]&&(a_bn=a_t[a_y])!=a_A&& !(a_m(a_bn)&&a_bn.moduleName&&
/[A-Z]/.test(a_y.charAt(0))))a_bC[a_y]=a_f(a_bn);a_g(a_bJ,a_A);a_bJ.toString=a_by;a_bJ.valueOf=a_bB;a_bJ.Class=a_bC;a_bC.nonInheritableStatics={a_bL:1,nonInheritableStatics:1,toString:0,valueOf:0};a_bC.superclass=a_t;a_bC.toString=a_by;a_bC.valueOf=a_bB;var a_bF=a_bC.a_bF=(a_t.a_bF||a_r).concat(),a_bI=a_bC.a_bI=(a_t.a_bI||a_r).concat();a_bw&&a_bF.push(a_bw);a_bx&&a_bI.push(a_bx);a_bC.a_G||(a_bC.a_G={});a_bC.a_F||(a_bC.a_F={});return a_bC;};a_t.subclass=function(a_bw,a_bx){return a_u(this,a_bw,a_bx);};a_t.singleton=function(a_bM,a_v){var a_bL=this.a_bL||(this.a_bL={}),a_bN=a_bL[a_bM||(a_bM='')];a_bN?a_v&&a_bN.set(a_v):(a_bN=a_bL[a_bM]=this(a_v));return a_bN;};return a_t;}});


Uize.module({name:'Uize.Node',required:'Uize.Class',builder:function(){var _a=function(){},_b,_c='string',_d='object',_e='function',_f=true,_g=false,_h=null,_i='hidden',_j=Uize,_k=_j.copyInto,_l=_j.isPrimitive,_m=_j.returnFalse;var _n=typeof navigator!='undefined',_o=_n?navigator:{userAgent:'',appName:''},_p=_o.userAgent.toLowerCase(),_q=_o.appName=='Microsoft Internet Explorer',_r={TABLE:_f,THEAD:_f,TFOOT:_f,TBODY:_f,TR:_f,COL:_f,COLGRPUP:_f,FRAMESET:_f,HEAD:_f,HTML:_f,STYLE:_f,TITLE:_f},_s=_p.indexOf('applewebkit')> -1,_t=_p.indexOf('gecko')> -1,_u=_p.indexOf('opera')> -1,_v=_t||_u,_w= +(_q&&(_p.match(/MSIE\s*(\d+)/i)||[0,0])[1]),_x=_q&&_w<9,_y=_a._y={},_z={},_A=0,_B={clientX:0,clientY:0,pageX:0,pageY:0};var _C=_a._C=function(_D){_B.clientX=_D.clientX;_B.clientY=_D.clientY;_B.pageX=_D.pageX;_B.pageY=_D.pageY;};function _E(_F){var _G=document.getElementById(_F);return(!_q||(_G&&_G.id==_F))?_G:_h;}function _H(){return document[_s?'body':'documentElement'];}function _I(_J){
var _K=(_J=_J+'').slice(_J.indexOf('(')+1,_J.indexOf(')'));return Function.apply({},(_K?_K.split(','):[]).concat(_J.slice(_J.indexOf('{')+1,_J.lastIndexOf('}'))));}function _L(_M){if(_M.charCodeAt(0)==111&&_M.charCodeAt(1)==110)_M=_M.slice(2);return(_M.charCodeAt(_M.length-1)==41&&_a.VirtualEvent?_a.VirtualEvent.resolve(_M):_M);}var _N='table-',_O=_N+'row',_P=_N+'cell',_Q=_k({SPAN:'inline',THEAD:_N+'header-group',TFOOT:_N+'footer-group',LI:'list-item'},_q&&typeof DOMImplementation=='undefined'?_h:{TABLE:'table',TR:_O,TH:_P,TD:_P,TBODY:_O+'-group',COLGROUP:_N+'column-group',COL:_N+'column',CAPTION:_N+'caption'});_a.display=function(_R,_S){_S=_S===_b|| !!_S;_T(_R,function(_U){_U.style.display=_S?(_Q[_U.tagName]||'block'):'none';});};var _T=_a.doForAll=function(_R,_J,_V,_W){if(typeof _R==_c)_R=_X(_R,_V,_W);if(_R!=_b){if(_Y(_R)){_J(_R);}else{var _Z=typeof _R;if((_Z==_d||_Z==_e)&&typeof _R.length=='number'){for(var _0= -1,_1=_R.length;++_0<_1;)_T(_R[_0],_J,_V,_W);}else if(_Z==_d){for(var _2 in _R)
_T(_R[_2],_J,_V,_W);}}}};var _3=_a.doRectanglesOverlap=function(_4,_5,_6,_7,_8,_9,_ba,_bb){return(_6-1+ +_4>=_8&&_ba-1+ +_8>=_4&&_7-1+ +_5>=_9&&_bb-1+ +_9>=_5);};var _X=_a.getById=function(_U,_V,_W){if(typeof _U!=_c)return _U;var _G=_W?_W[_U]:_b;if(_G===_b){var _bc=_bd(_V,_U);(_G=_E(_bc))||(((_G=document.getElementsByName(_bc)).length<2)&&(_G=_G[0]||_h));if(_W)_W[_U]=_G;}return _G;};_a.find=function(_be){if(typeof _be!=_d|| !_be||typeof _be.length=='number'||_Y(_be))return _be;var _bf=document,_bg=[],_bh=_k({},_be),_bi='root'in _bh?_X(_bh.root):_bf;delete _bh.root;if(_bi){var _bj=_bh.tagName;if('id'in _bh&&_l(_bh.id)){var _U=_E(_bh.id);_U&&_bg.push(_U);delete _bh.id;}else if('name'in _bh&&_l(_bh.name)){_bg=_bf.getElementsByName(_bh.name);delete _bh.name;}else{var _bk=_l(_bj);_bk&&delete _bh.tagName;_bg=_bi.getElementsByTagName(_bj&&_bk?_bj:'*');_bi=_h;}if(_bi==_bf)_bi=_h;if(!_bj||_bj=='*')delete _bh.tagName;}var _bl=_bg.length;for(var _bm in _bh)break;if(!_bl||(_bm==_b&& !_bi))return _bg;var _bn=[],_bo;
for(var _bp= -1;++_bp<_bl;){var _U=_bg[_bp];if(_bo=_bi?_bq(_U,_bi):_f){for(var _br in _bh){var _bs=_U[_br],_bt=_bh[_br],_bu=_j.isFunction;if(!(_l(_bt)?_bs==_bt:(_bt instanceof RegExp?_bt.test(_bs||''):(_bu(_bt)?_bt.call(_U,_bs):_f)))){_bo=_g;break;}}}_bo&&_bn.push(_U);}return _bn;};var _bv=_a.getCoords=function(_U){var _bw=0,_bx=0,_by=0,_bz=0,_bA=_f,_bB=100,_bC=_H(),_bD=_bE(window);function _bF(){_bw+=_bC.scrollLeft;_bx+=_bC.scrollTop;}if(_U==window){_bF();_by=_bD.width;_bz=_bD.height;}else if(_Y(_U=_X(_U))){_by=_U.offsetWidth;_bz=_U.offsetHeight;if(!(_by&&_bz)&&_U.tagName=='DIV'){for(var _bG=_U.childNodes,_bH=_bG.length;--_bH>=0;){if(_bG[_bH].nodeName.charAt(0)!='#'){var _bI=_bv(_bG[_bH]);if(_bI.width||_bI.height){_by=Math.max(_by,_bI.right-_bw+1);_bz=Math.max(_bz,_bI.bottom-_bx+1);}}}}function _bJ(_U){return _bK(_U,'display')=='none'||_bK(_U,'visibility')==_i;}if(_U.tagName=='A'&&_U.childNodes.length==1&&_U.childNodes[0].tagName=='IMG')_U=_U.childNodes[0];var _bL=_bA= !_bJ(_U),_bM=_U,_bN=_U,_bO=_bD.width,
_bP=_bD.height,_bQ=_bC.scrollLeft,_bR=_bC.scrollTop,_bS=_bQ+_bO,_bT=_bR+_bP;while(_bN.parentNode&&typeof _bN.parentNode!='unknown'){var _bU=_bN.offsetLeft||0,_bV=_bN.offsetTop||0,_bW=_bN.offsetWidth,_bX=_bN.offsetHeight;if(_bA&&_bJ(_bN))_bA=_g;if(_bN==_bM){_bw+=_bU+(parseInt(_bK(_bN,'borderLeftWidth'))||0);_bx+=_bV+(parseInt(_bK(_bN,'borderTopWidth'))||0);_bM=_bN.offsetParent;_bK(_bN,'position')=='fixed'&&_bF();}if(_bN!=_U&&_bN!=document.body&&_bN!=document.documentElement&&(_bN.scrollWidth>_bW||_bN.scrollHeight>_bX)){_bw-=_bN.scrollLeft;_bx-=_bN.scrollTop;if(_q){_bw+=_bN.clientLeft;_bx+=_bN.clientTop;}if(_bA)_bA=_3(_bw,_bx,_by,_bz,_bU,_bV,_bW,_bX);}_bN=_bN.parentNode;}if(_bA)_bA=_3(_bw,_bx,_by,_bz,_bQ,_bR,_bO,_bP);_bB=_bA?((Math.min(_bw+_by,_bS)-Math.min(Math.max(_bw,_bQ),_bS))*(Math.min(_bx+_bz,_bT)-Math.min(Math.max(_bx,_bR),_bT)))/(_by*_bz)*100:0;}return{x:_bw,y:_bx,width:_by,height:_bz,area:_by*_bz,left:_bw,top:_bx,right:_bw+_by-1,bottom:_bx+_bz-1,seen:_bA,percentSeen:_bB};};
var _bE=_a.getDimensions=function(_U){if(_U==window){var _bC=document.documentElement;return{width:_bC.clientWidth||window.innerWidth||_bC.offsetWidth,height:_bC.clientHeight||window.innerHeight||_bC.offsetHeight};}else if(_U=_X(_U)){return{width:_U.offsetWidth||parseInt(_bK(_U,'width'))||0,height:_U.offsetHeight||parseInt(_bK(_U,'height'))||0};}else{return{width:0,height:0};}};var _bY={borderColor:['border','Color'],borderWidth:['border','Width'],padding:1,margin:1},_bK=_a.getStyle=function(_U,_bZ){var _b0=typeof _bZ==_c,_b1=_b0?'':{};if(_U=_X(_U)){if(_b0){var _b2=_q&&_bZ=='opacity',_b3=document.defaultView,_b4=_b3&&_b3.getComputedStyle(_U,'');if(_b2)_bZ='filter';if(_b4){if(!(_b1=_b4[_bZ])){var _b5=_bY[_bZ];if(_b5){var _b6=_b5[0]||_bZ,_b7=_b5[1]||'',_b8=_b4[_b6+'Top'+_b7],_b9=_b4[_b6+'Right'+_b7],_ca=_b4[_b6+'Bottom'+_b7],_cb=_b4[_b6+'Left'+_b7];_b1=_b8==_b9&&_b9==_ca&&_ca==_cb?_cb:_b8+' '+_b9+' '+_ca+' '+_cb;}}}else{var _cc=_U.currentStyle;_b1=_cc?_cc.getAttribute(_bZ):_U.style[_bZ];}if(_b2){
var _cd=(_b1||'').match(/alpha\s*\(\s*opacity\s*=([^\)]*)\)/i);_b1=_cd?_cd[1]/100:1;}}else{for(_bZ in _bZ)_b1[_bZ]=_bK(_U,_bZ);}}return _b1;};var _ce=_a.getText=function(_U){var _cf='';if(_U=_X(_U)){function _cg(_U){if(typeof _U.innerText==_c){_cf+=_U.innerText.replace(/\r|\n|\r\n/g,'');}else if(typeof _U.textContent==_c){_cf+=_U.textContent;}else{if(_U.nodeType==3)_cf+=_U.data;_U.childNodes&&_j.forEach(_U.childNodes,_cg);}}_cg(_U);}return _cf;};_a.getValue=function(_U){var _b1;if(_U=_X(_U)){if(_Y(_U)){var _ch=_U.tagName;if(_ch=='TEXTAREA'){_b1=_U.value;}else if(_ch=='INPUT'){_b1=_U.type=='checkbox'?_U.checked:_U.value;}else if(_ch=='SELECT'){if(_U.multiple){_b1=[];_j.forEach(_U.options,function(_ci){_ci.selected&&_b1.push(_ci.value)});}else{_b1=_U.value;}}else if(_ch=='IMG'){_b1=_U.src;}else{_b1=_U.innerHTML.replace(/<br\/?>/gi,'\n').replace(/&nbsp;/g,' ');}}else{_b1=(_j.findRecord(_U,{tagName:'INPUT',type:'radio',checked:_f})||{}).value;}}return _b1;};_a.injectHtml=function(_R,_cj,_ck){var
 _cl,_cm,_cn,_co,_cp,_cq,_cr=_j.isArray(_cj)||(_Y(_cj)&&(_cj=[_cj]));((_cl=_ck=='inner replace')||(_cm=_ck=='outer replace')||(_cn=_ck=='inner top')||(_co=_ck=='outer top')||(_cp=_ck=='outer bottom')||(_cq=_f));_cr||(_cj+='');_T(_R,function(_U){var _cs=_U.childNodes;function _ct(_cu){return _cu&&/<script/i.test(_cu)}function _cv(){return _ct(_cj)}if((_cl||(!_cs.length&&(_cn||_cq)))&& !_Y&& !_cv()){_U.innerHTML=_cj;}else if(_cm&&_q&& !_Y&& !_cv()){_U.outerHTML=_cj;}else{if(_cl)if(_q&&_r[_U.tagName]){var _cw=_U.cloneNode();_U.replaceNode(_cw);_U=_cw;}else _U.innerHTML='';if(_cr){var _cx=[];for(var _bp= -1,_cy=_cj.length;++_bp<_cy;)_cx.push(_cj[_bp].cloneNode(_f));}else{var _cz=document.createElement('DIV');_cz.innerHTML='<i>e</i>'+_cj;var _cx=_cz.childNodes}var _cA=_cn?_cs[0]:_cp?_U.nextSibling:_U,_cB=_U.parentNode,_cC= +!_cr;function _cD(_U){if(_U.tagName=='SCRIPT'){var _cE=document.createElement('script');if(_U.id)_cE.id=_U.id;if(_U.type)_cE.type=_U.type;_cE.text=_U.text;if(_U.src)_cE.src=_U.src;
_U.parentNode.replaceChild(_cE,_U);}else if(_ct(_U.innerHTML)){_j.forEach(_U.childNodes,_cD);}}while(_cx.length>_cC){var _cF=_cr?_cx.shift():_cx[_cC];if(_cq||_cl){_U.appendChild(_cF);}else if(_cn){_cA?_U.insertBefore(_cF,_cA):_U.appendChild(_cF);}else if(_co||_cm){_cB.insertBefore(_cF,_cA);}else if(_cp){_cA?_cB.insertBefore(_cF,_cA):_cB.appendChild(_cF);}_cr||_cD(_cF);}_cm&&_cB.removeChild(_U);}});};var _Y=_a.isNode=function(_U){return!!(_U&&typeof _U==_d&&(_U.getAttribute||_U.documentElement||(_U.self&&_U.self==_U)));};var _bq=_a.isOnNodeTree=function(_U,_cG){_U=_X(_U);_cG=_X(_cG);while(_U){if(_U==_cG)return _f;_U=_U.parentNode;}return _g;};var _bd=_a.joinIdPrefixAndNodeId=function(_V,_F){return(_V||'')+(_V&&_F?'-':'')+_F;};_a.remove=function(_R){_T(_R,function(_U){_U.parentNode.removeChild(_U)});};_a.setClipRect=function(_R,_b8,_b9,_ca,_cb){var _cH='rect('+_b8+'px, '+_b9+'px, '+_ca+'px, '+_cb+'px)';_T(_R,function(_U){_U.style.clip=_cH});};var _cI=['left','top','width','height'];
_a.setCoords=function(_R,_cJ){_cK(_R,_j.isArray(_cJ)?_j.meldKeysValues(_cI,_cJ):_cJ);};_a.centerInWindow=function(_R){var _cL=_bv(window);_T(_R,function(_U){var _cM=_bE(_U);_a.setCoords(_U,{left:_cL.x+((_cL.width-_cM.width)>>1),top:_cL.y+((_cL.height-_cM.height)>>1)});});};_a.getEventAbsPos=function(_cN){var _cO=(_cN||(_cN=_B)).targetTouches;if(_cO&&_cO.length)_cN=_cO[0];if(_cN.pageX!=_b){return{left:_cN.pageX,top:_cN.pageY};}else{var _bC=_H();return{left:_cN.clientX+_bC.scrollLeft,top:_cN.clientY+_bC.scrollTop};}};var _cP=_a.setAbsPos=function(_R,_cQ,_cR){_cR=typeof _cR=='number'?{x:_cR,y:_cR}:(_cR||{x:0,y:0});var _bC=document[_s?'body':'documentElement'],_cS=_bE(window);_T(_R,function(_U){function _cT(_cU,_cV,_cW,_cX){var _cY=_cQ[_cU],_cZ=_cR[_cX],_c0=_cY-_bC[_cV],_c1=_cZ+_cM[_cW];return(_cY+(_c0+_c1>_cS[_cW]?Math.max(-_c1,-_c0):_cZ));}var _cM=_bE(_U);_cK(_U,{left:_cT('left','scrollLeft','width','x'),top:_cT('top','scrollTop','height','y'),right:'auto',bottom:'auto'});});};
_a.setAbsPosAdjacentTo=function(_R,_c2,_c3){_c2=_X(_c2);var _c4=_bv(_c2),_c5=_c4.width/2,_c6=_c4.height/2,_c7=_c3=='x'? -1:1;if(!_c5&& !_c6)_c4=_a.getEventAbsPos();_T(_R,function(_U){_cP(_U,{left:_c4.left+_c5,top:_c4.top+_c6},{x:-_c5*_c7,y:_c6*_c7});});};_a.setInnerHtml=function(_R,_cu){_cu+='';_T(_R,function(_U){_U.innerHTML=_cu});};var _c8={};_a.setOpacity=function(_R,_c9){_c8.opacity=_c9;_cK(_R,_c8);};_a.setProperties=function(_R,_be){_T(_R,function(_U){_k(_U,_be)});};var _cK=_a.setStyle=function(_R,_be){_T(_R,function(_U){var _da=_U.style,_db;if(_q&&'opacity'in _be)_da.filter=(_db=Math.round(_be.opacity*100))<100?'alpha(opacity='+_db+')':'';for(var _bZ in _be)_da[_bZ]=(typeof(_db=_be[_bZ])==_d&&_db?(_db=_db.valueOf()):_db)!=_b?(typeof _db=='number'&&_bZ!='opacity'&&_bZ!='zIndex'?Math.round(_db)+'px':_db+''):'';});};_a.setValue=function(_R,_b1){_b1+='';_T(_R,function(_U){var _ch=_U.tagName,_dc=_U.readOnly;if(_dc)_U.readOnly=_g;if(_ch=='TEXTAREA'){_U.value=_b1;}else if(_ch=='INPUT'){var _dd=_U.type;
if(_dd=='text'||_dd==_i||_dd=='password'){_U.value=_b1;}else if(_dd=='checkbox'){_U.checked=_b1=='true';}else if(_dd=='radio'){_U.checked=_U.value==_b1;}}else if(_ch=='SELECT'){if(!_b1){_U.selectedIndex= -1;}else{var _de=_U.options;if(_U.multiple&&(_b1=='*'||_b1.indexOf(',')> -1)){var _df=_b1!='*'?_j.lookup(_b1.split(',')):_b;for(var _dg=_de.length,_ci;--_dg>=0;)(_ci=_de[_dg]).selected= !_df||_df[_ci.value];}else{_U.selectedIndex=_j.findRecordNo(_de,{value:_b1},_U.selectedIndex);}}}else if(_ch=='IMG'){if(_b1)_U.src=_b1;}else{_ch=='PRE'&&_q?(_U.innerText=_b1):(_U.innerHTML=_b1.replace(/</g,'&lt;').replace(/\n/g,'<br/>'));}if(_dc)_U.readOnly=_dc;});};_a.show=function(_R,_dh){_cK(_R,{visibility:_dh||_dh===_b?'inherit':_i});};_a.showClickable=function(_R,_di){_cK(_R,{cursor:_di||_di===_b?(_x?'hand':'pointer'):'default'});};var _dj=_a.unwire=function(_R,_dk,_dl,_dm){if(typeof _dk==_d&&_dk&& !_dk.virtualDomEvent){for(var _M in _dk)_dj(_R,_M,_dk[_M],_dl);}else{_a.unwireEventsByOwnerId(_dm,_R!==_b||_dk!=_b||_dl!=_b
?{node:_R,eventName:_dk,handler:_dl}:_b);}};_a.unwireEventsByOwnerId=function(_dn,_do){var _dp=_z[_dn=_dn||''];if(_dp){function _dq(_dr){if(_dr!==_h){var _ds=_do&&_do.eventName,_dt=_do&&_do.handler,_du=_dr||_ds||_dt;if(_ds&&_ds.charCodeAt)_ds=_L(_ds);for(var _dv=_dp.length;--_dv>=0;){var _dw=_dp[_dv],_dx=_y[_dw],_U=_dx._U,_M=_dx._M;if(!_du||((!_dr||_dr==(_dx._dy||_U))&&(!_ds||_ds==_M)&&(!_dt||_dt==_dx._dz))){_du&&_dp.splice(_dv,1);if(_dx._dA){_a.unwireEventsByOwnerId(_dx._dA)}else{try{_U==window?_dB.unwire(_M,_dx._dC):_q?_U.detachEvent('on'+_M,_dx._dC):_U.removeEventListener(_M,_dx._dC,_g);}catch(_dD){}}delete _y[_dw];}}(_du&&_dp.length)||delete _z[_dn];}}_do&&_do.node!==_b?_T(_do.node,_dq):_dq();}};var _dE=_I(function(_dw){return(function(_D){var _dx=window.Uize&&Uize.Node._y[_dw];return _dx&&_dx._dz.call(_dx._U,_D.windowEvent);});}),_dF=_I(function(_dw){return(function(_D){var _dx=window.Uize&&Uize.Node._y[_dw];return _dx&&_dx._dz.call(_dx._U,_D||window.event);});}),_dG={click:_dF,mouseover:_I(
function(_dw){return(function(_D){var _dx=window.Uize&&Uize.Node._y[_dw],_dH=(_D||(_D=window.event)).fromElement||_D.relatedTarget;if(_dx){if(_dH){try{if(!_dH.Uize_Widget_Drag_shield&& !Uize.Node.isOnNodeTree(_dH,_dx._U))_dH=null;}catch(_dD){_dH=null;}}if(!_dH){Uize.Node._C(_D);return _dx._dz.call(_dx._U,_D);}}});}),mouseout:_I(function(_dw){return(function(_D){var _dx=window.Uize&&Uize.Node._y[_dw],_dI=(_D||(_D=window.event)).toElement||_D.relatedTarget;if(_dx){if(_dI){try{if(!_dI.Uize_Widget_Drag_shield&& !Uize.Node.isOnNodeTree(_dI,_dx._U))_dI=null;}catch(_dD){_dI=null;}}if(!_dI)return _dx._dz.call(_dx._U,_D);}});}),mousedown:_dF,mouseup:_dF};_a.wire=function(_R,_M,_dz,_dn){if(!_M)return;if(_dn==_b)_dn='';var _dJ;if(_M.charCodeAt)_M=_L(_M);if(typeof _M==_d&& !(_dJ= !!_M.virtualDomEvent)){_dn=arguments[2]||'';for(var _D in _M)_a.wire(_R,_D,_M[_D],_dn);return;}_T(_R,function(_U){var _ch=_U.tagName;(_z[_dn]||(_z[_dn]=[])).push(_A);var _dC=(_dJ?_m:_U==window?_dE:_dG[_M]||_dF)(_A);var _dx=_y[_A++]={_U:_U,_M:_M,
_dz:_dz,_dC:_dC};if(_v&&_ch=='BODY'&&_M=='scroll'){_dx._dy=_U;_U=_dx._U=document;}if(_dC){var _dK='on'+_M;_U==window?_dB.wire(_M,_dC):_q?_U.attachEvent(_dK,_dC):_U.addEventListener(_M,_dC,_g);if(_ch=='A'&&(_M=='mousedown'||_M=='click')&& !_U[_dK])_U[_dK]=_m;}else if(_dJ){_M.wire(_U,_dz,_dx._dA=_j.getGuid());}});};_a.ieMajorVersion=_w;_a.isIe=_q;_a.isSafari=_s;_a.isMozilla=_t;if(_n){_a.wire(document.documentElement,'mousemove',_C);var _dB=Uize.Class(),_dL=setTimeout(function(){_dB.fire('load')},15000);_j.forEach(['focus','blur','load','beforeunload','unload','resize','scroll'],function(_dM){var _dN='on'+_dM,_dO=window[_dN]||_m;window[_dN]=function(_D){_dM=='load'&&clearTimeout(_dL);_dO.call(window,_D||(_D=window.event));_dB.fire({name:_dM,windowEvent:_D});};});}_a.returnFalse=_m;_a.returnTrue=_j.returnTrue;return _a;}});


Uize.module({name:'Uize.Widget',superclass:'Uize.Class',required:'Uize.Node',builder:function(b_a){var b_b=null,b_c=true,b_d=false,b_e='string',b_f=Uize,b_g=b_f.isFunction,b_h='concatenated',b_i,b_j=b_f.Node,b_k=b_j.doForAll,b_l=b_j.isNode,b_m=b_j.getById;var b_n=b_a.subclass(function(b_o){var b_p=this;if(b_o){var b_q=b_p.b_r(b_o.idPrefix,b_o.parent);b_q&&b_f.copyInto(b_o,b_q);delete b_o.widgetClass;}b_p.b_s={};b_p.children=b_p.b_t={};}),b_u=b_n.prototype;b_u.b_r=function(b_v,b_w){var b_o,b_x;(b_v&&(b_o=window[b_x='$'+b_v])&&typeof b_o=='object'&&(!b_w||b_v!=b_w.b_v))?(window[b_x]=b_i):(b_o=b_i);return b_o;};b_u.b_y=function(){var b_p=this,b_q=b_p.b_r(b_p.b_v,b_p.parent);b_q&&b_p.set(b_q);};b_u.b_z=function(b_A,b_B,b_C,b_D){return((!b_D||b_D==b_h)&&b_A!=b_i?(b_A+(b_C!==''?'_':'')+b_C):(b_D=='same as parent'?b_A:b_B));};var b_E={b_F:b_d,b_G:b_c};function b_H(){(this.b_I=='inherit'?(this.parent||b_E).b_F:this.b_I)!=this.b_F&&this.set({b_F:!this.b_F});}function b_J(){
(this.b_K=='inherit'?(this.parent||b_E).b_G:this.b_K)!=this.b_G&&this.set({b_G:!this.b_G});}b_u.b_L=function(b_M,b_N,b_O){var b_P='show'+b_f.capFirstChar(b_M);this.getProvider(b_P)?this.callInherited(b_P)(b_N):setTimeout(function(){var b_Q=b_O();(b_N.callback||(b_Q?b_N.yesHandler:b_N.noHandler)||b_f.nop)(b_Q)},0);};b_u.confirm=function(b_N){this.b_L('confirm',b_N,function(){return confirm(b_N.message)});};b_u.showInform=b_u.showConfirm=b_i;b_u.inform=function(b_N){this.b_L('inform',b_N,function(){alert(b_N.message);return b_c})};b_u.ajax=function(b_R,b_S){this.callInherited('performAjax')(b_R,b_f.isFunction(b_S)?{callback:b_S}:b_S||{})};b_u.localize=function(b_T,b_U,b_V){var b_W,b_X=this;while(!(b_W=b_X.b_Y?b_X.b_Y[b_T]:b_i)&&(b_X=b_X.parent));return(b_g(b_W)?b_W.call(this,b_U):b_f.substituteInto(b_W,b_U,b_V||'{KEY}'));};b_u.buildHtml=function(b_Z){var b_p=this,b_0=b_p.b_0;if(b_0!=b_i){var b_1=b_p.b_2||b_p.getNode('shell')||b_p.getNode();if(b_0===b_c){b_0=b_p.b_0=b_f.Template&&b_1?{
process:b_f.Template.compile((b_j.find({root:b_1,tagName:'SCRIPT',type:'text/jst'})[0]||b_1).innerHTML,{openerToken:'[%',closerToken:'%]'})}:b_i;if(!b_0)return;}b_p.b_v||b_p.set({b_v:b_p.instanceId});var b_3=b_f.copyInto({pathToResources:b_f.pathToResources,blankGif:b_n.getBlankImageUrl()},b_Z||b_p.get()),b_4;b_j.injectHtml(b_1||document.body,typeof b_0!=b_e&&b_g(b_0.process)?b_0.process.call(b_p,b_3):b_g(b_0)?typeof(b_4=b_0(b_3))==='string'?b_f.substituteInto(b_4,b_3):b_4:b_f.substituteInto(b_0,b_3),b_p.b_5||(b_1?'inner replace':'inner bottom'));b_p.b_6=b_b;b_p.set({b_7:b_c});}};function b_8(b_9,b_ba){b_u[b_9+'Node'+b_ba]=new Function('arguments.length'+'?(arguments[0]=this.getNode(arguments[0]))'+':(arguments[arguments.length++]=this.getNode());'+'return Uize.Node.'+b_9+b_ba+'.apply(0,arguments)');}b_u.getNode=function(b_bb){if(b_bb==b_b){if(b_bb===b_b)return b_b;b_bb='';}var b_p=this;if(b_p.b_bc&&typeof b_bb==b_e){var b_bd=b_p.b_bc[b_bb];if(b_bd!==b_i)b_bb=b_bd;}if(typeof b_bb==b_e){
return b_m(b_bb,b_p.b_v,b_p.b_6||(b_p.b_6={}));}else if(b_l(b_bb)){return b_bb;}else{var b_be=b_b;b_k(b_bb,function(b_bf){(b_be||(b_be=[])).push(b_bf)},b_p.b_v,b_p.b_6||(b_p.b_6={}));return b_be;}};b_8('get','Style');b_8('get','Value');b_u.flushNodeCache=function(b_bg){if(this.b_6)b_bg==b_i?(this.b_6=b_b):delete this.b_6[b_bg];};b_u.globalizeNode=function(b_bh){var b_p=this,b_bi=document.body;b_k(b_p.getNode(b_bh),function(b_bf){if(b_bf.parentNode!=b_bi){(b_p.b_bj||(b_p.b_bj=[])).push(b_bf);b_j.setStyle(b_bf,{position:'absolute',left:-10000,top:-10000});b_bi.appendChild(b_bf);}});};b_8('display','');b_8('inject','Html');b_u.removeNode=function(b_bh){b_j.remove(this.getNode(b_bh));this.flushNodeCache(b_bh);};b_8('set','Properties');b_8('set','Opacity');b_8('set','Style');b_8('set','ClipRect');b_8('set','InnerHtml');b_8('set','Value');b_8('show','');b_u.wireNode=function(b_bh,b_bk,b_bl){arguments.length==3?b_j.wire(this.getNode(b_bh),b_bk,b_bl,this.instanceId):b_j.wire(this.getNode(b_bh),b_bk,this.instanceId);
};b_u.unwireNode=function(b_bh,b_bk,b_bl){if(b_bh!==b_i)b_bh=this.getNode(b_bh);arguments.length==2&&typeof b_bk=='object'&&b_bk&& !b_bk.virtualDomEvent?b_j.unwire(b_bh,b_bk,this.instanceId):b_j.unwire(b_bh,b_bk,b_bl,this.instanceId);};b_u.unwireNodeEventsByMatch=function(b_bh,b_bm){this.unwireNode(b_bh,(b_bm||(b_bm={})).eventName,b_bm.handler);};b_u.addChild=function(b_C,b_bn,b_o){if(!b_o)b_o={};var b_p=this,b_v=b_p.b_v,b_bo=b_f.isInstance(b_bn)?b_bn:b_b,b_B='idPrefix'in b_o?b_o.idPrefix:b_o.node,b_bp=b_o.idPrefixConstruction;b_o.parent=b_p;if(b_C==b_i)b_C=b_o.name;if(b_bo){if(b_C==b_i)b_C=b_bo.b_bq;if(b_B==b_i)b_B=b_bo.b_v;if(!b_bp)b_bp=b_bo.b_D;}b_o.idPrefix=b_p.b_z(b_v,b_B,b_o.name=b_C,b_o.idPrefixConstruction=b_bp||(b_B==b_i?b_h:'explicit'));var b_s=b_p.b_s,b_br=b_s[b_C];if(b_br){b_f.copyInto(b_o,b_br);delete b_s[b_C];}b_bo&&b_bo.set(b_o);return b_p.b_t[b_C]=b_bo||new b_bn(b_o);};b_u.removeChild=function(b_bs){var b_t=this.b_t,b_C=typeof b_bs==b_e||b_f.isNumber(b_bs)?b_bs:b_bs.b_bq,b_bo=b_t[b_C];
if(b_bo){b_bo.unwireUi();delete b_bo.parent;delete b_t[b_C];}};b_u.getProvider=function(b_bt){var b_bu=this,b_bv;while(((b_bv=b_bu.get(b_bt))==='inherit'||b_bv===b_i)&&(b_bu=b_bu.parent));return b_bu;};b_u.getInherited=function(b_bt){var b_bw=this.getProvider(b_bt);return b_bw?b_bw.get(b_bt):b_i;};b_u.setInherited=function(b_o){var b_bw;for(var b_bx in b_o){if(b_bw=this.getProvider(b_bx))b_bw.set(b_bx,b_o[b_bx]);}};b_u.callInherited=function(b_bt){var b_p=this;return(function(){var b_bw=b_p.getProvider(b_bt),b_be;if(b_bw){var b_by=b_bw.get(b_bt);if(b_g(b_by))b_be=b_by.apply(b_bw,arguments);}return b_be;});};b_u.kill=function(){b_f.callOn(this.b_t,'kill');b_a.prototype.kill.call(this);};b_u.insertOrWireUi=function(){this.b_7?this.wireUi():this.insertUi();};b_u.insertUi=function(){this.buildHtml();this.wireUi();};b_u.removeUi=function(){this.unwireUi();this.removeNode();b_j.remove(this.b_bj);this.b_bj=b_i;b_f.callOn(this.b_t,'removeUi');this.set({b_7:b_d});};b_u.updateUi=function(){};b_u.wireUi=function(){
if(!this.isWired){this.b_y();this.set({wired:b_c});b_f.callOn(this.b_t,'insertOrWireUi');this.updateUi();}};b_u.unwireUi=function(){if(this.isWired){this.b_6=b_b;this.unwireNode();b_f.callOn(this.b_t,'unwireUi');this.set({wired:b_d});}};b_n.getBlankImageUrl=function(){return b_f.pathToResources+'Uize/blank.gif';};b_n.spawn=function(b_o,b_w){var b_p=this,b_bz=[],b_bu,b_bA=b_w&&b_w.b_v?b_w.b_v+'_':'',b_bB=b_bA.length;b_k(b_f.Node.find(b_o.idPrefix),function(b_bf){b_o.idPrefix=b_bf;b_w?(b_bu=b_w.addChild(b_bf.id.slice(0,b_bB)==b_bA?b_bf.id.slice(b_bB):'generatedChildName'+b_f.getGuid(),b_p,b_o)):(b_bu=new b_p(b_o)).insertOrWireUi();b_bz.push(b_bu);});return b_bz;};b_n.registerProperties({b_7:{name:'built',value:b_c},b_I:{name:'busy',onChange:b_H,value:'inherit'},b_F:{name:'busyInherited',onChange:function(){b_f.callOn(this.b_t,b_H)},value:b_d},b_t:{name:'children',conformer:function(b_bv){if(b_bv){var b_t=this.b_t,b_s=this.b_s;for(var b_C in b_bv){var b_bC=b_bv[b_C];b_t[b_C]?b_t[b_C].set(b_bC):b_s[b_C]=b_bC;}}
return this.b_t;}},b_2:'container',b_K:{name:'enabled',onChange:b_J,value:'inherit'},b_G:{name:'enabledInherited',onChange:function(){b_f.callOn(this.b_t,b_J)},value:b_c},b_0:'html',b_v:{name:'idPrefix|node',conformer:function(b_v){return(b_l(b_v)?(b_v.id||(b_v.id=b_f.getGuid())):b_v);},onChange:function(){var b_p=this,b_v=b_p.b_v;b_p.b_6=b_b;if(b_v!=b_i){b_p.b_y();var b_t=b_p.b_t,b_bo;for(var b_C in b_t)(b_bo=b_t[b_C]).set({b_v:b_p.b_z(b_v,b_bo.b_v,b_C,b_bo.b_D)});if(b_p.isWired){b_p.set({wired:b_d});b_p.wireUi();}}}},b_D:'idPrefixConstruction',b_5:'insertionMode',b_Y:'localized',b_bq:'name',b_bc:'nodeMap',isWired:{name:'wired',value:b_d}});return b_n;}});


Uize.module({name:'Uize.Widget.Page',required:'Uize.Node',builder:function(c_a){var c_b=true,c_c=false,c_d=null,c_e,c_f=Uize.Node;var c_g=c_a.subclass(c_d,function(){c_g.xDeferredLinks&&this.wireDeferredLinks()}),c_h=c_g.prototype;function c_i(c_j){return(Uize.isFunction(c_j)&&c_j)||(c_j&&c_j.callback)||Object}c_h.c_k=function(c_l,c_m,c_n){var c_o=this;c_o.useDialog({component:c_o.c_p.component,widgetClassName:c_o.c_p.widgetClassName||'Uize.Widget.Dialog.Confirm',widgetProperties:{name:'confirmDialog',title:c_n.title||'',message:(c_n.message+'').replace(/\n/g,'<br/>'),mode:c_l,state:c_n.state||c_m,okText:c_n.okText||c_d,cancelText:c_n.cancelText||c_d},submitHandler:function(c_q){var c_r=c_n.callback||(c_q?c_n.yesHandler:c_n.noHandler);c_r&&c_r(c_q);}});};c_h.c_s=function(c_t){c_t=c_t||Object;var c_o=this,c_u=c_o.get('idPrefix'),c_v=window;var c_w={},c_x=c_c,c_y='$'+c_u+'_',c_z=c_y.length,c_A;for(var c_B in c_v){if(c_B.charAt(0)=='$'&&c_B.substr(0,c_z)==c_y&&typeof(c_A=c_v[c_B])=='object'&&c_A&&c_A.widgetClass
){c_x=c_b;for(var c_C= -1,c_D=c_w,c_E=c_B.substr(c_z).split('_'),c_F,c_G=c_E.length;++c_C<c_G;){var c_H=c_D[c_F=c_E[c_C]];if(c_C<c_G-1){c_D=(c_H||(c_H=c_D[c_F]={})).children||(c_H.children={});}else{c_H?Uize.mergeInto(c_H,c_A):(c_D[c_F]=c_A);c_v[c_B]=c_e;}}}}if(c_x){function c_I(c_J,c_K){function c_L(c_M,c_N,c_O){var c_P=c_O.children,c_Q=c_J(c_M,c_N,c_O);c_P&&c_R(c_Q,c_P);c_K&&c_K(c_Q);}function c_R(c_M,c_S){for(var c_N in c_S)c_L(c_M,c_N,c_S[c_N]);}c_R(c_o,c_w);}var c_T={},c_U=[];c_I(function(c_M,c_N,c_O){var c_V=c_O.widgetClass;if(c_V&& !c_T[c_V]){c_T[c_V]=1;c_U.push(c_V);}});Uize.module({required:c_U,builder:function(){c_o.set({children:c_w});c_I(function(c_M,c_N,c_O){var c_Q=c_M.children[c_N];if(!c_Q){var c_V=eval(c_O.widgetClass||'Uize.Widget');c_Q=c_N.charCodeAt(0)==36&&c_N.charCodeAt(1)==36?c_V.spawn(c_O,c_M):c_M.addChild(c_N,c_V);}return c_Q;},c_o.isWired&&function(c_Q){Uize.callOn(c_Q,'insertOrWireUi')});c_t();}});}else{c_t();}};c_h.loadHtmlIntoNode=function(c_W,c_X,c_Y){var c_o=this,
c_Z=c_W.rootNodeId,c_t=c_i(c_Y),c_0={callback:function(c_1){var c_2=document.body,c_3=c_W.node!=undefined?c_o.getNode(c_W.node):(c_Z?c_f.getById(c_Z+'-shell'):c_d)||c_2;c_f.injectHtml(c_3,c_1,c_W.injectMode||(c_3==c_2?'inner bottom':'inner replace'));c_o.c_s(c_t);}};c_W.alwaysReplace===c_c&&c_Z&&c_f.getById(c_Z)?c_t():c_o.loadHtml(c_X,typeof c_Y=='object'&&c_Y?Uize.copyInto({},c_Y,c_0):c_0);};c_h.performAjax=function(){};c_h.useDialog=function(c_n){var c_o=this,c_4=Uize.copyInto({},c_o.c_5,c_n.widgetProperties),c_6=c_4.parent||c_o,c_7=c_4.name,c_8=c_6.children[c_7],c_9=c_n.component,c_ba;if(c_9){var c_Z=c_4.idPrefix||(c_6.get('idPrefix')+'_'+c_7);c_ba={name:c_9.name,rootNodeId:c_Z,params:Uize.copyInto({idPrefix:c_Z},c_9.params)};}function c_bb(c_bc){setTimeout(function(){function c_bd(c_be,c_bf){var c_r=c_n[c_be];c_r&&c_r.apply(0,c_bf);}function c_bg(c_bh){var c_bf=[c_bh];c_bd(c_bh.name.toLowerCase()+'Handler',c_bf);c_bd('dismissHandler',c_bf);}function c_bi(c_bh){c_o.fire({name:'Dialog '+c_bh.name,
dialogWidget:c_bh.source})}c_8.unwire(c_8.eventHandlersForUseDialog||{});c_8.eventHandlersForUseDialog={'Submission Complete':function(c_bh){c_bd('submitHandler',[c_bh.result,c_bh])},Close:c_bg,Cancel:c_bg,'Before Show':c_bi,'After Show':c_bi,'Before Hide':c_bi,'After Hide':c_bi};c_8.wire(c_8.eventHandlersForUseDialog);c_8.set(c_4);c_8.set({shown:c_b});},0);}if(c_8&&(c_8.componentProfile==c_ba||Uize.Data.identical(c_8.componentProfile,c_ba))){c_bb('subsequent');}else{var c_bj=c_ba&& !!c_8;if(c_bj){c_8.removeUi();c_6.removeChild(c_7);}function c_bk(){var c_bl=c_n.widgetClassName;Uize.module({required:c_bl,builder:function(){(c_8=c_6.children[c_7])?c_8.set(c_4):(c_8=c_6.addChild(c_7,eval(c_bl),c_4));c_8.componentProfile=c_ba;c_8.wire(c_n.widgetEventHandlers);c_8.insertOrWireUi();c_bb(c_bj?'refetched':'initial');}});}c_ba?c_o.loadHtmlIntoNode({rootNodeId:c_ba.rootNodeId,injectMode:'inner bottom',alwaysReplace:c_c},Uize.copyInto({cp:c_ba.name},c_ba.params),{cache:'memory',callback:c_bk}):c_bk();}};
c_h.wireUi=function(){var c_o=this;if(!c_o.isWired){c_o.c_s();c_a.prototype.wireUi.call(c_o);}};var c_bm={yes:1,on:1,1:1,'true':1};c_g.launchPopup=c_h.launchPopup=function(c_n){if(!c_n)c_n={};if(c_n.width==c_e)c_n.width=850;if(c_n.height==c_e)c_n.height=600;var c_bn=window.screen;if(c_n.left==c_e)c_n.left=Math.max((c_bn.width-c_n.width-10)>>1,0);if(c_n.top==c_e)c_n.top=Math.max((c_bn.height-c_n.height-40)>>1,0);function c_bo(c_bp){return c_bp+'='+c_n[c_bp];}function c_bq(c_bp,c_br){return(c_bp+'='+(c_bm[c_n[c_bp]==c_e?c_br:c_n[c_bp]+'']?'yes':'no'));}var c_bs=window.open(c_n.url||'',c_n.name==c_e?'popupWindow':c_n.name,[c_bo('width'),c_bo('height'),c_bo('top'),c_bo('left'),c_bq('toolbar',0),c_bq('location',0),c_bq('directories',0),c_bq('status',0),c_bq('menubar',0),c_bq('scrollbars',1),c_bq('resizable',1)].join(','));c_bs&&c_bs.focus();return c_bs;};c_g.registerProperties({c_p:{name:'confirmDialog',value:{}},c_5:'dialogProperties'});c_g.set({idPrefix:'page'});c_h.loadHtml=function(c_X,c_j){c_i(c_j)('');};
c_h.showConfirm=function(c_n){this.c_k('confirm','confirm',c_n);};c_h.showInform=function(c_n){this.c_k('alert','info',c_n);};return c_g;}});


Uize.module({name:'UizeDotCom.Templates'});


Uize.module({name:'UizeDotCom.Templates.WidgetToGoTitle',builder:function(){var _a=function(){};_a.process=function(input){var output=[];
output.push('<div class="widgetHeader">\r\n	<div id="',input.idPrefix,'_menu_selector" title="Click to show/hide widget options..." class="widgetTitle">\r\n		<div class="logo"></div>\r\n		<div class="textShadow">',input.title,'</div>\r\n		<div class="textHighlight">',input.title,'</div>\r\n		<div class="textMain">',input.title,'</div>\r\n	</div>\r\n	<div id="',input.idPrefix,'_menu-palette" class="subMenuShell">\r\n		<a id="',input.idPrefix,'_menu-getThisWidget" href="javascript://" class="subMenuItem">GET THIS WIDGET</a>\r\n		<div class="divider"></div>\r\n		<a id="',input.idPrefix,'_menu-aboutThisWidget" href="javascript://" class="subMenuItem">About This Widget</a>\r\n		<a id="',input.idPrefix,'_menu-openInNewWindow" href="javascript://" class="subMenuItem">Open Widget in New Window</a>\r\n		<div class="divider"></div>\r\n		<a id="',input.idPrefix,'_menu-moreWidgets"  href="javascript://" class="subMenuItem">More UIZE Widgets...</a>\r\n		<a id="',input.idPrefix,'_menu-uize" href="javascript://" class="subMenuItem">UIZE JavaScript Framework</a>\r\n	</div>\r\n</div>\r\n\r\n');
return output.join('');};_a.input={idPrefix:'string',title:'string'};return _a;}});


Uize.module({name:'Uize.Fade',superclass:'Uize.Class',builder:function(b_a){var b_b,b_c='object',b_d=Uize.constrain,b_e=Uize.now;var b_f={},b_g=[],b_h=false,b_i;function b_j(){if((b_h= !!b_g.length)!= !!b_i)b_i=b_h?setInterval(b_k,10):clearInterval(b_i);}function b_k(){for(var b_l= -1,b_m;++b_l<b_g.length;)(b_m=b_g[b_l]).b_n?b_m.b_k():b_g.splice(b_l--,1);b_j();}var b_o=b_a.subclass(),b_p=b_o.prototype,b_q=b_o.nonInheritableStatics;b_p.b_r=function(){var b_s=this,b_t=b_u(b_s.b_v,b_s.b_w,b_s.b_x,b_s.b_y,b_s.b_z,b_s.b_t);if(b_t!=b_f)b_t!=b_s.b_t?b_s.set({b_t:b_t}):b_s.fire('Changed.value');};b_p.b_k=function(){var b_A=Math.min((b_e()-this.b_B)/this.b_C,1);this.set({b_x:this.b_D?1-b_A:b_A});if(b_A==1){this.stop();this.fire('Done');}};b_p.stop=function(){this.set({b_n:false});};b_p.start=function(b_E){this.stop();this.set(Uize.copyInto({b_n:true},b_E));};var b_u=b_o.blendValues=function(b_F,b_G,b_H,b_y,b_z,b_I){if(b_F===b_G){return b_I!==b_b&&b_F===b_I?b_f:b_F;}else{if(Uize.isFunction(b_z)){b_H=b_z(b_H);b_z=b_b;}
if(typeof b_F==b_c&&b_F&& !(b_F instanceof RegExp)){var b_J=b_I&&typeof b_I==b_c,b_K=b_y&&typeof b_y==b_c,b_L=b_z&&typeof b_z==b_c,b_M=b_J?b_I:Uize.isArray(b_F)?[]:{},b_N;for(var b_O in b_F){var b_P=b_u(b_F[b_O],b_G[b_O],b_H,b_K?b_y[b_O]:b_y,b_L?b_z[b_O]:b_z,b_N=b_M[b_O]);if(b_J)b_J=b_P==b_f||(typeof b_P!=b_c&&b_P==b_N);if(b_P!=b_f)b_M[b_O]=b_P;}return b_J?b_f:b_M;}else{var b_M= !b_H?b_F:b_H==1?b_G: !b_y?b_F+(b_G-b_F)*b_H:b_H>0&&b_H<1?b_d(b_F+Math.round((b_G-b_F)*b_H/b_y)*b_y,b_F,b_G):b_F+Math.round((b_G-b_F)*b_H/b_y)*b_y;return b_I!==b_b&&b_M===b_I?b_f:b_M;}}};b_q.blendValues=1;b_o.celeration=function(b_Q,b_R){var b_S=1-(b_Q=b_Q||0)-(b_R=b_R||0),b_T=2/(1+b_S),b_U=b_Q?b_T/b_Q:0,b_V=b_U/2,b_W=b_R? -b_T/b_R:0,b_X=b_W/2,b_Y=b_Q*b_Q,b_Z;return(b_S>=1?Uize.returnX:function(b_t){return((b_t=(b_Q?b_d(b_t*b_t,0,b_Y)*b_V:0)+(b_S?b_T*b_d(b_t-b_Q,0,b_S):0)+(b_R?((b_T+(b_Z=b_d(b_t-b_Q-b_S,0,b_R))*b_X)*b_Z):0))>1?1:b_t);});};b_q.celeration=1;function b_0(){this.set({b_z:this.b_Q||this.b_R?b_o.celeration(this.b_Q,this.b_R)
:null});}function b_1(){this.b_t=null;this.b_r();}b_o.registerProperties({b_Q:{name:'acceleration',onChange:b_0},b_z:{name:'curve',onChange:b_1},b_R:{name:'deceleration',onChange:b_0},b_C:{name:'duration',value:2000},b_w:{name:'endValue',onChange:b_1,value:100},b_n:{name:'inProgress',onChange:function(){var b_s=this;if(b_s.b_n){b_s.b_B=b_e();b_s.fire('Start');b_s.b_t=b_s.b_x=null;b_s.b_k();b_g.push(b_s);b_j();}},value:false},b_x:{name:'progress',onChange:b_p.b_r,value:0},b_D:'reverse',b_v:{name:'startValue',onChange:b_1,value:0},b_y:'quantization',b_t:{name:'value',value:0}});return b_o;}});


Uize.module({name:'Uize.Widget.Button',required:'Uize.Node',builder:function(c_a){var c_b,c_c=true,c_d=false,c_e=Uize.Node;var c_f=c_a.subclass(null,function(){var c_g=this;function c_h(){if(c_g.isWired){c_g.c_i()||c_g.set({c_j:''});c_g.c_h();}}c_g.wire({'Changed.busyInherited':c_h,'Changed.enabledInherited':c_h});}),c_k=c_f.prototype;var c_l,c_m={},c_n={grayed:16,'':8,over:4,active:2,playing:1},c_o='(Grayed|Over|Active|Playing)',c_p=new RegExp(c_o),c_q=new RegExp('(?:(?:(\\S+)\\s+\\1'+c_o+'))','g'),c_r=new RegExp('\\S*'+c_o+'\\b','g'),c_s=/\b(disabled|over|active|playing)\b/,c_t={},c_u={mouseover:['over','Over'],mouseout:['','Out'],mousedown:['down','Down'],mouseup:['over','Up'],click:['over','Click'],dblclick:['over','Double Click']};c_k.c_v=c_d;c_k.c_i=function(c_w){var c_g=this;return!!(c_g.get('enabledInherited')&& !c_g.get('busyInherited')&&(c_w|| !c_g.c_x||c_g.c_y||c_g.c_z));};c_k.c_A=function(){this.c_B!=c_b&&this.isWired&&this.setNodeInnerHtml('text',this.c_B);};var c_h=c_k.c_h=function(){
var c_g=this;if(c_g.isWired){var c_C=c_g.c_C,c_D=c_g.get('enabledInherited'),c_E=c_g.get('busyInherited'),c_F=(!c_D?16:0)|(!c_g.c_j||c_E?8:0)|(c_g==c_l?4:0)|(c_g.c_j=='down'||c_g.c_x?2:0)|(c_g.c_G?1:0),c_H=c_g.c_I[c_F];if(c_H==c_b){for(var c_J= -1,c_K=c_g.c_K,c_L=c_K.length;++c_J<c_L;){var c_M=c_K[c_J];if(c_F&c_n[c_M]){c_H=c_M;break;}}c_g.c_I[c_F]=c_H;}if(c_g.c_N=='classes'){var c_O=c_C.className,c_P='';if(c_g.c_Q=='disambiguated'){var c_R=c_g.c_R;if(c_R==c_b){var c_S=c_O.match(c_q);if(c_S){c_R=c_S[c_S.length-1].split(' ',2)[0];}else{c_S=c_O.replace(c_r,'').match(/(\S+)\s*$/);if(c_S)c_R=c_S[c_S.length-1];}if(c_g.c_R=c_R=c_R||'')c_g.c_T=c_t[c_R]||(c_t[c_R]=new RegExp(c_R+'(\\s+'+c_R+c_o+')?'));}var c_U=c_H?' '+c_R+Uize.capFirstChar(c_H):'';c_P=c_R?c_O.replace(c_g.c_T,c_R+c_U):c_O.replace(c_p,'')+c_U;}else{var c_V=c_H=='grayed'?'disabled':c_H;c_P=c_s.test(c_O)?c_O.replace(c_s,c_V):c_O+(c_V?' ':'')+c_V;}if(c_P!=c_O)c_C.className=c_P;}else if(c_g.c_N=='frames'){
c_g.c_W.style.top='-'+(c_g.c_X.c_Y[c_H]*c_g.c_Z.height)+'px';}if(c_g.c_0&&Uize.Tooltip){var c_1=c_g.c_j=='over'&&c_D&& !c_g.c_x;c_1!=c_g.c_v&&Uize.Tooltip.showTooltip(c_g.c_0,c_g.c_v=c_1);}c_g.get('busyInherited')?c_e.setStyle(c_C,{cursor:'wait'}):c_e.showClickable(c_C,c_g.c_i());}};c_k.c_2=function(c_3){var c_g=this;if(c_g.isWired){var c_4=c_3.type,c_5=c_4=='click',c_i=c_g.c_i(c_4=='dblclick');if(!c_g.c_6){c_g.c_6=c_c;function c_2(c_3){c_g.c_2(c_3)}c_g.wireNode(c_g.c_C,{mouseout:c_2,mousedown:c_2,mouseup:c_2,dblclick:c_2});}if(c_5)c_3.cancelBubble=c_c;if(c_i){var c_7=c_u[c_4];c_g.set({c_j:c_7[0]});c_g.fire({name:c_7[1],domEvent:c_3});c_5&&(c_g.c_x?c_g.c_y:c_g.c_8)&&c_g.set({c_x:!c_g.c_x});}}};c_k.updateUi=function(){if(this.isWired){this.c_h();this.c_A();}};c_k.wireUi=function(){var c_g=this;if(!c_g.isWired){c_g.c_W=c_b;var c_C=c_g.c_C=c_g.getNode();if(c_C){var c_9=c_C.childNodes;if(c_9.length&&(c_9.length>1||c_9[0].nodeType!=3)&&(c_g.c_W=c_g.getNode('frames'))){c_g.c_N='frames';
c_g.c_Z=c_e.getDimensions(c_g.c_W.parentNode);}if(c_g.c_ba&&c_C.tagName=='A'&& !c_C.onclick)c_C.onclick=Uize.returnTrue;function c_2(c_3){c_g.c_2(c_3)}c_g.wireNode(c_C,{mouseover:c_2,click:c_2});c_g.c_B==c_b&&c_g.set({c_B:c_g.getNodeValue('text')});c_a.prototype.wireUi.call(c_g);}}};c_f.addChildButton=function(c_bb,c_bc){var c_g=this,c_bd;function c_be(){c_bd.wire('Click',function(c_bf){if(c_bc)typeof c_bc=='string'?c_g.fire(c_bc):c_bc(c_bf);c_g.fire(c_bf);});}if(c_g==c_f){c_bd=new c_f({idPrefix:c_bb,name:c_bb,c_ba:c_c});c_be();(window[c_bd.instanceId]=c_bd).wireUi();}else{c_bd=c_g.children[c_bb];if(!c_bd){c_bd=c_g.addChild(c_bb,c_f);c_be();}}return c_bd;};c_f.registerProperties({c_z:{name:'allowClickWhenSelected',onChange:c_h},c_8:'clickToSelect',c_y:{name:'clickToDeselect',onChange:c_h},c_Q:{name:'classNamingForStates',value:'disambiguated'},c_X:{name:'frameOrder',onChange:function(){var c_X=this.c_X;c_X.c_Y||(c_X.c_Y=Uize.reverseLookup(c_X));},value:['grayed','','over','active','playing']},c_ba:{
name:'followLink',value:c_d},c_N:{name:'mode',value:'classes'},c_G:{name:'playing',onChange:c_h,value:c_d},c_x:{name:'selected',onChange:c_h,value:c_d},c_j:{name:'state',onChange:function(){var c_g=this;if(!c_g.c_j){if(c_l==c_g)c_l=c_b;}else if(c_g.c_j=='over'){c_l&&c_l!=c_g&&c_l.set({c_j:''});c_l=c_g;}c_g.isWired&&c_g.c_h();},value:''},c_K:{name:'statePrecedence',onChange:function(){var c_g=this,c_bg=c_g.c_K.c_bh||(c_g.c_K.c_bh=c_g.c_K.join(','));c_g.c_I=c_m[c_bg]||(c_m[c_bg]={});c_g.isWired&&c_g.c_h();},value:['playing','active','grayed','over','']},c_B:{name:'text',onChange:c_k.c_A},c_0:'tooltip'});return c_f;}});


Uize.module({name:'Uize.Widget.PopupPalette',required:['Uize.Node','Uize.Fade','Uize.Widget.Button'],builder:function(c_a){var c_b=true,c_c=false,c_d=null,c_e=Uize.Node;var c_f=c_a.subclass(null,function(){var c_g=this;c_g.fade=Uize.Fade({duration:750,curve:Uize.Fade.celeration(0,1)});c_g.fade.wire({'Changed.value':function(){c_g.setNodeOpacity('palette',c_g.fade)},Done:function(){c_g.c_h(c_g.c_i)}});var c_j=c_g.c_j=c_g.c_k('selector',function(){c_g.toggle('shown')}),c_l;c_j.set({clickToDeselect:c_b});c_g.c_m();function c_n(c_o){var c_p=c_o.name=='Over',c_q=c_g.c_q;function c_r(){c_g.set({c_i:c_b})}if(c_p){if(c_q===c_b||c_q===0)c_r();else if(c_q>0)c_l=setTimeout(c_r,c_q);c_g.c_s()}else{clearTimeout(c_l);c_g.c_t();}}c_j.wire({Down:c_u,Over:c_n,Out:c_n});c_v[c_g.instanceId]=c_g;}),c_w=c_f.prototype,c_v={};c_w.c_m=function(){this.c_j.set({selected:this.c_i})};c_w.c_x=function(){return this.c_i&&(this.c_q!==c_c||this.c_y);};c_w.c_s=function(){this.c_x()&&this.c_z();this.fire('Over');};c_w.c_t=function(){
this.c_x()&&this.c_A();this.fire('Out');};c_w.c_k=Uize.Widget.Button.addChildButton;c_w.c_h=function(c_B){var c_g=this;c_g.displayNode('palette',c_B);c_B&&c_g.setNodeStyle('palette',{filter:''});c_g.fire({name:'Palette '+(c_B?'Shown':'Dismissed'),bubble:c_b});};c_w.c_z=function(){var c_g=this;if(c_g.c_C){clearTimeout(c_g.c_C);c_g.c_C=null;}};c_w.c_A=function(){var c_g=this;c_g.c_z();c_g.c_C=setTimeout(function(){c_g.set({c_i:c_c})},250);};c_w.kill=function(){delete c_v[this.instanceId];c_a.prototype.kill.call(this);};c_w.wireUi=function(){var c_g=this;if(!c_g.isWired){c_g.wireNode('palette',{mousedown:c_u,mouseup:function(c_o){c_g.c_D&&c_o.target!=c_g.getNode('palette')&&c_g.set({c_i:c_c});},mouseover:function(){c_g.c_s()},mouseout:function(){c_g.c_t()}});c_g.wireNode('paletteClose','click',function(){c_g.set({c_i:c_c})});if(c_g.c_E!='none'){var c_F=document.body,c_G=c_g.getNode('palette');if(c_G&&c_G.parentNode!=c_F){c_F.insertBefore(c_G,c_F.childNodes[0]);c_g.setNodeStyle(c_G,{zIndex:10000,
position:'absolute',left:'',top:'',right:'',bottom:'',width:c_g.getNodeStyle(c_G,'width')});}}c_a.prototype.wireUi.call(c_g);}};c_f.registerProperties({c_H:{name:'exclusive',value:c_b},c_y:{name:'hideWhenOut',value:c_c},c_D:{name:'hideOnClick',value:c_b},c_E:{name:'positioning',value:'none'},c_i:{name:'shown',onChange:function(){var c_g=this,c_i=c_g.c_i,c_E=c_g.c_E;c_g.c_j&&c_g.c_m();if(c_g.isWired){c_g.c_z();if(c_i){c_g.fire('Before Palette Shown');c_g.c_H&&c_I(c_g);if(c_E!='none'){var c_G=c_g.getNode('palette'),c_J=Uize.isFunction(c_E)?c_E(c_G):c_g.c_j.getNode();function c_K(c_L){c_g.showNode('palette',!c_L);c_g.displayNode('palette',c_L);}if(c_e.isNode(c_J)){c_K(c_b);c_e.setAbsPosAdjacentTo(c_G,c_J);c_K(c_c);}}}if(c_g.fade.get('duration')>0){c_i&&c_g.displayNode('palette');c_g.fade.start({startValue:c_i?0:1,endValue:c_i?1:0});}else{c_g.c_h(c_i);}}},value:c_c},c_q:{name:'showWhenOver',value:c_c}});function c_I(c_M){for(var c_N in c_v){var c_O=c_v[c_N];c_O!=c_M&&c_O.c_H&&c_O.set({c_i:c_c});}}
function c_u(){c_P=c_b}if(typeof navigator!='undefined'){var c_P=c_c,c_Q=document.onmousedown;document.onmousedown=function(c_o){if(!c_o)c_o=event;c_P?(c_P=c_c):c_I();Uize.isFunction(c_Q)&&c_Q(c_o);};}return c_f;}});


Uize.module({name:'UizeDotCom.WidgetToGoPage',superclass:'Uize.Widget.Page',required:['Uize.Node','UizeDotCom.Templates.WidgetToGoTitle','Uize.Widget.PopupPalette'],builder:function(d_a){var d_b=d_a.subclass(null,function(){this.addChild('menu',Uize.Widget.PopupPalette,{hideWhenOut:true,positioning:'absolute'}).fade.set({duration:0});}),d_c=d_b.prototype;d_c.wireUi=function(){var d_d=this;if(!d_d.isWired){Uize.Node.injectHtml(document.body,UizeDotCom.Templates.WidgetToGoTitle.process({idPrefix:d_d.get('idPrefix'),title:document.title}));Uize.module({required:[d_d.d_e,d_d.d_f],builder:function(){d_d.addChild('widget',eval(d_d.d_e),{built:false,html:eval(d_d.d_f)}).insertOrWireUi();}});var d_g=d_d.children.menu,d_h='../'+d_d.d_i.toLowerCase().replace(/\s+/g,'-')+'.html';function d_j(d_k,d_l,d_m,d_n,d_o){page.launchPopup({name:d_k,url:d_l,width:d_m,height:d_n,toolbar:d_o,location:d_o,directories:d_o,status:d_o,menubar:d_o,scrollbars:d_o,resizable:d_o});}function d_p(d_q,d_l){
d_g.wireNode(d_q,'click',function(){d_j(null,d_l,1010,690,1)});}d_p('getThisWidget',d_h);d_p('aboutThisWidget',d_h);d_p('moreWidgets','../../javascript-widgets.html');d_p('uize','../../index.html');d_g.wireNode('openInNewWindow','click',function(){var d_r=Uize.Node.getDimensions(window);d_j('',location.href,d_r.width,d_r.height,0);});d_a.prototype.wireUi.call(d_d);}};d_b.registerProperties({d_i:'title',d_e:'widgetToGoClass',d_f:'widgetToGoHtml'});return d_b;}});


Uize.module({name:'Uize.Node.Event',builder:function(){var _a=function(_b){return _b||event};_a.abort=function(_b){_a.preventDefault(_b||(_b=event));_a.stopPropagation(_b);};_a.charCode=function(_b){_b||(_b=event);if(_b.ctrlKey||_b.altKey||_b.which<1)return 0;return'charCode'in _b?_b.charCode:_a.keyCode(_b);};_a.fix=function(_b){_b||(_b=event);_b.target=_a.target(_b);_b.relatedTarget=_a.relatedTarget(_b);_b.charCode=_a.charCode(_b);_b.keyCode=_a.keyCode(_b);_b.preventDefault||(_b.preventDefault=_c);_b.stopPropagation||(_b.stopPropagation=_d);return _b;};Uize.map({Backspace:8,Delete:46,Insert:45,Enter:13,Escape:27,Space:32,Tab:9,PageUp:33,PageDown:34,End:35,Home:36,LeftArrow:37,RightArrow:39,UpArrow:38,DownArrow:40},function(_e,_f){_a['isKey'+_f]=function(_b){return _a.keyCode(_b)==_e};});_a.keyCode=function(_b){return'which'in(_b||(_b=event))?_b.which:_b.keyCode;};function _c(){this.preventDefault?this.preventDefault():(this.returnValue=false);}_a.preventDefault=function(_b){_c.call(_b||event)};
_a.relatedTarget=function(_b){return('relatedTarget'in(_b||(_b=event))?_b.relatedTarget:(_b.type=='mouseout'?_b.toElement:_b.fromElement));};function _d(){this.stopPropagation?this.stopPropagation():(this.cancelBubble=true);}_a.stopPropagation=function(_b){_d.call(_b||event)};_a.target=function(_b){return(_b||(_b=event)).target||_b.srcElement;};return _a;}});


Uize.module({name:'Uize.Tooltip',required:['Uize.Node','Uize.Fade'],builder:function(){var _a=function(){},_b=true,_c=false,_d,_e=Uize.Node;var _f=Uize.getGuid(),_g=[],_h,_i=16;function _j(_k){return _e.getById(Uize.isFunction(_k)?_k():_k);}function _l(){_m()}function _n(_o){if(_o!=_h){if(_o){if(_h){_p.stop();_q();}if(!_o._r){_e.wire(document.body,'scroll',_l,_f);_e.wire(document.documentElement,'mousemove',_l,_f);}_h=_o;_e.setStyle(_h._s,{position:'absolute',zIndex:5000,left:-50000,top:-50000});_e.display(_h._s);_m();}else{_p.get('duration')>0?_p.start():_q();}}else if(_o){_p.stop();_e.setOpacity(_h._s,1);}}_a.showTooltip=function(_k,_t,_r){if(_k=_j(_k)){if(_t!==_c){_g.push({_s:_k,_r:_r});}else{for(var _u=_g.length;--_u> -1;)if(_g[_u]._s==_k)break;_u> -1&&_g.splice(_u,1);}_n(_g[_g.length-1]);}};_a.hideTooltip=function(_k){_a.showTooltip(_k,_c)};var _m=_a.positionTooltip=function(_k,_v){_h&&(_k===_d?(_k=_h._s):_h._s==_j(_k))&&_e.setAbsPos(_k,_e.getEventAbsPos(_v),_i);};var _p=_a.fade=Uize.Fade({duration:0});
function _q(){_h._r||_e.unwireEventsByOwnerId(_f);_e.display(_h._s,_c);_e.setOpacity(_h._s,1);_h=null;}_p.wire({'Changed.value':function(){_e.setOpacity(_h._s,1-_p.get('progress'))},Done:_q});return _a;}});


Uize.module({name:'Uize.Templates'});


Uize.module({name:'Uize.Date',builder:function(){var _a=function(_b,_c,_d,_e,_f,_g,_h){var _i=new Date(+_b+(_b<100&&400),(+_c||1)-1,+_d||1,+_e||0,+_f||0,+_g||0,+_h||0);_b<100&&_i.setFullYear(_b);return _i;},_j;function _k(_l){return isNaN(_l)?'??':(_l<10?'0':'')+_l}function _m(_l){return(isNaN(_l)?'???':(_l<10?'00':_l<100?'0':'')+_l);}function _n(_l){return(isNaN(_l)?'????':(_l<10?'000':_l<100?'00':_l<1000?'0':'')+_l);}var _o={ms:1,seconds:1000,minutes:60000,hours:3600000,days:86400000,weeks:604800000,months:2629743840,years:31556926080};var _p=_a.convert=function(_q,_r,_s){return _q*_o[_r+'']/_o[_s+''];};var _t=_a.resolve=function(_i,_u){return(_i instanceof Date?_i:_i==null||_i===''?(_u!==_j?_u:new Date):typeof _i=='string'?_a.fromIso8601(_i)||new Date(_i):new Date(+_i));};_a.equal=function(_v,_w,_x){return _a.inRange(_v,_a.getRangeAround(_w,_x||'day'));};_a.toIso8601=function(_i){return(_n((_i=_t(_i)).getFullYear())+'-'+_k(_i.getMonth()+1)+'-'+_k(_i.getDate()));};_a.fromIso8601=function(_y){
var _z=_y.match(/(\d{2,})-(\d\d?)-(\d\d?)(?:\D|$)/);return(_z?_a(+_z[1]+(_z[1].length<3)*1900,_z[2],_z[3]):_j);};var _A={date:'Invalid Date',YYYY:'????',YY:'??',MM:'??',monthNo:'?',monthName:'?????????',shortMonthName:'???',DD:'??',dayNo:'?',dayNoSuffix:'??',dayName:'????????',shortDayName:'???',hh:'??',h12:'?',hh12:'??',mm:'??',minutes:'?',ss:'??',seconds:'?',zzz:'???',milliseconds:'?',ampm:'??'};_a.format=_a.toPretty=function(_i,_B){var _C=_A;if(!isNaN(_i=_t(_i))){var _D=_n(_i.getFullYear()),_E=_i.getMonth()+1,_d=_i.getDate(),_F=_d%10,_G=_i.getDay(),_H=_i.getHours(),_I=_H>11,_J=(_H-(_I&&12))||12,_f=_i.getMinutes(),_g=_i.getSeconds(),_h=_i.getMilliseconds();_C={date:_i,YYYY:_D,YY:_D.slice(-2),MM:_k(_E),monthNo:_E,monthName:_a.monthNames[_E-1],shortMonthName:_a.shortMonthNames[_E-1],DD:_k(_d),dayNo:_d,dayNoSuffix:_a.dayNoSuffixes[(_F<4&&Math.floor(_d/10)%10!=1)*_F],dayName:_a.dayNames[_G],shortDayName:_a.shortDayNames[_G],hh:_k(_H),h12:_J,hh12:_k(_J),mm:_k(_f),minutes:_f,ss:_k(_g),seconds:_g,zzz:_m(_h),
milliseconds:_h,ampm:_I?'pm':'am'};}return Uize.substituteInto(_B||'{dayName}, {dayNo}{dayNoSuffix} {monthName} {YYYY}',_C,'{KEY}');};_a.getRangeAround=function(_i,_K){var _L=new Date(_i=_t(_i)),_M=new Date(_L);function _N(_O,_P,_Q){_L[_O](_P);_M[_O](_Q);}function _R(_S,_T){var _U=Math.floor(_i['get'+_S]()/_T)*_T;_N('set'+_S,_U,_U+_T-1);}switch(_K||(_K='month')){case'millennium':case'century':case'decade':_R('FullYear',_K=='millennium'?1000:_K=='century'?100:10);case'year':case'quarter':_K=='quarter'?_R('Month',3):_N('setMonth',0,11);case'month':case'week':if(_K=='week'){var _V=_i.getDate()-_i.getDay();_N('setDate',_V,_V+6);}else{_N('setDate',1,_a.getDaysInMonth(_M.getMonth(),_M.getFullYear()));}case'day':case'am/pm':_K=='am/pm'?_R('Hours',12):_N('setHours',0,23);case'hour':_N('setMinutes',0,59);case'minute':_N('setSeconds',0,59);case'second':_N('setMilliseconds',0,999);}return{minValue:_L,maxValue:_M};};_a.inRange=function(_i,_W){if(typeof _i!='number')_i= +_t(_i);
return _i>=_t(_W.minValue,-Infinity)&&_i<=_t(_W.maxValue,Infinity);};_a.isLeapYear=function(_b){return _b%4==0&&(_b%100!=0||_b%400==0);};_a.getDaysInMonth=function(_c,_b){return 30+((2773>>_c)&1)-(_c==1&&(2-_a.isLeapYear(_b)));};_a.isRecent=function(_i,_X,_Y){return _a.inRange(_i,{minValue:_t(_Y)-_p(_X,'days','ms')});};_a.dayNames=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];_a.dayNoSuffixes=['th','st','nd','rd'];_a.monthNames=['January','February','March','April','May','June','July','August','September','October','November','December'];_a.shortDayNames=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'];_a.shortMonthNames=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];return _a;}});


Uize.module({name:'Uize.Date.Formatter',builder:function(){var _a=function(){},_b=Uize.Date;var _c,_d={YYYY:'\\d{4}',YY:'\\d\\d',MM:'1[0-2]|0[1-9]',monthNo:'1[0-2]|0?[1-9]',DD:'30|31|[1-2]\\d|0[1-9]',dayNo:'30|31|[1-2]\\d|0?[1-9]',dayNoSuffix:_b.dayNoSuffixes.join('|'),hh:'[0-1]\\d|2[0-3]',h12:'1[0-2]|0?[1-9]',hh12:'1[0-2]|0[1-9]',mm:'[0-5]\\d',minutes:'[0-5]?\\d',ss:'[0-5]\\d',seconds:'[0-5]?\\d',zzz:'\\d{3}',milliseconds:'\\d{1,3}',ampm:'am|pm'},_e=['monthName','shortMonthName','dayName','shortDayName'],_f=String.fromCharCode(7);function _g(_h,_i){_i=_i.toLowerCase();for(var _j= -1,_k=_h.length;++_j<_k;)if(_i==_h[_j].toLowerCase())return _j;return-1;}_a.format=_a.toPretty=_b.format;_a.parse=function(_l,_m){var _n;if(typeof _l=='object'&&_l&& !(_l instanceof Date))_l=_l.valueOf();if(_l instanceof Date)return _l;if(_l==null||_l=='')return;if(typeof _l=='number')return new Date(_l);if(!_m)return _b.resolve(_l);Uize.lookup(_e,null,_d);if(!_c)_c=new RegExp('\\{('+Uize.keys(_d).join('|')+')\\}','g');var _o=[],
_p=0,_q=new RegExp(Uize.escapeRegExpLiteral(_m.replace(_c,function(_r,_n){_o.push(_n);return _f;})).replace(/\s+/g,'\\s+').replace(/\x07/g,function(){return('\\s*('+(_d[_n=_o[_p++]]||(_d[_n]=_b[_n+'s'].join('|')))+')\\s*');}),'i'),_s=(_l+'').match(_q);if(_s){var _t=0,_u=1,_v=1,_w,_x=0,_y=0,_z=0,_A=0,_B=false;for(var _C=0,_D=_s.length;++_C<_D;){var _E=_s[_C];switch(_o[_C-1]){case'YYYY':_t= +_E;break;case'YY':_t=1900+ +_E;break;case'MM':case'monthNo':_u= +_E;break;case'monthName':_u=_g(_b.monthNames,_E)+1;break;case'shortMonthName':_u=_g(_b.shortMonthNames,_E)+1;break;case'DD':case'dayNo':_v= +_E;break;case'hh':_w= +_E;break;case'h12':case'hh12':_x= +_E;break;case'mm':case'minutes':_y= +_E;break;case'ss':case'seconds':_z= +_E;break;case'zzz':case'milliseconds':_A= +_E;case'ampm':_B=/^pm$/i.test(_E)}}return _b(_t,_u,_v,_w!==undefined?_w:_x*(_x!=12)+_B*12,_y,_z,_A);}};return _a;}});


Uize.module({name:'Uize.Widget.Calendar',required:['Uize.Widget.Button','Uize.Date','Uize.Date.Formatter'],builder:function(c_a){var c_b=true,c_c=false,c_d=null,c_e=Uize.Date,c_f=c_e.dayNames,c_g=c_e.monthNames;var c_h=c_a.subclass(c_d,function(){var c_i=this;c_i.c_j=c_i.c_k('nextMonth',function(){c_i.set({c_l:c_i.c_l+1})});c_i.c_m=c_i.c_k('previousMonth',function(){c_i.set({c_l:c_i.c_l-1})});c_i.c_n=c_i.c_k('nextYear',function(){c_i.set({c_o:c_i.c_o+1})});c_i.c_p=c_i.c_k('previousYear',function(){c_i.set({c_o:c_i.c_o-1})});c_i.c_q=c_b;c_i.c_r();}),c_s=c_h.prototype;c_s.c_k=Uize.Widget.Button.addChildButton;var c_t=c_s.c_t=function(){var c_i=this,c_u={minValue:c_i.c_v,maxValue:c_i.c_w};c_i.c_x&& !c_e.inRange(c_i.c_x,c_u)&&c_i.set({c_x:c_d});var c_y=c_i.c_x||new Date;if(!c_e.inRange(c_y,c_u))c_y=c_i.c_v||c_i.c_w;c_i.set({c_l:c_y.getMonth(),c_o:c_y.getFullYear()});};var c_r=c_s.c_r=function(){var c_i=this;if(c_i.c_q){var c_z=new Date(c_i.c_o,c_i.c_l,1),c_A=c_e.getRangeAround(c_z,'month'),
c_B=c_e.getRangeAround(c_z,'year'),c_v=c_i.c_v,c_w=c_i.c_w;function c_C(c_D,c_E){c_D.set({enabled:c_E?'inherit':c_c});}c_C(c_i.c_m,!c_v||c_v<c_A.minValue);c_C(c_i.c_j,!c_w||c_w>c_A.maxValue);c_C(c_i.c_p,!c_v||c_v<c_B.minValue);c_C(c_i.c_n,!c_w||c_w>c_B.maxValue);}};c_s.c_F=function(){this.isWired&&this.setNodeValue('month',c_g[this.c_l]);};c_s.c_G=function(){this.isWired&&this.setNodeValue('year',this.c_o);};var c_H=c_s.c_H=function(){var c_i=this;if(c_i.isWired){function c_I(c_y,c_J){return(c_y?c_y.getFullYear()*10000+(c_y.getMonth()+1)*100+c_y.getDate():c_J);}var c_x=c_i.c_x,c_v=c_i.c_v,c_w=c_i.c_w,c_o=c_i.c_o,c_l=c_i.c_l,c_K=c_e.getDaysInMonth(c_l,c_o),c_L=new Date(c_o,c_l,1),c_M=c_I(c_L),c_N=Uize.constrain(c_I(c_v,0)-c_M+1,1,c_K+1),c_O=Uize.constrain(c_I(c_w,Infinity)-c_M+1,-1,c_K),c_P=c_i.c_P;if(!c_P||c_x!=c_P.c_x||c_l!=c_P.c_l||c_o!=c_P.c_o||c_N!=c_P.c_N||c_O!=c_P.c_O){if(c_P){for(var c_Q=0,c_R;++c_Q<32;){c_i.unwireNode(c_R='day'+c_Q);c_i.flushNodeCache(c_R);}}if(!c_P)c_P=c_i.c_P={};c_P.c_x=c_x;
c_P.c_l=c_l;c_P.c_o=c_o;c_P.c_N=c_N;c_P.c_O=c_O;var c_S=['<table class="calendarGrid" cellpadding="0" cellspacing="0"><tr>'];for(var c_Q= -1;++c_Q<7;)c_S.push('<th title="'+c_f[c_Q]+'">'+c_f[c_Q].charAt(0)+'</th>');c_S.push('</tr><tr>');var c_T=c_I(c_x,c_d),c_U=c_i.get('idPrefix'),c_Q=1-c_L.getDay();for(var c_V= -1;++c_V<6;){c_S.push('<tr>');for(var c_W= -1;++c_W<7;){if(c_Q>0&&c_Q<=c_K){var c_X=c_I(new Date(c_o,c_l,c_Q))==c_T;c_S.push(c_Q>=c_N&&c_Q<=c_O?('<td'+(c_X?' class="selected"':'')+'><a href="javascript://" id="'+c_U+'-day'+c_Q+'" style="display:block; width:100%; text-align:center;">'+c_Q+'</a></td>'):('<td class="'+(c_X?'selected ':'')+'grayed">'+c_Q+'</td>'),'</td>');}else{c_S.push('<td>&nbsp;</td>');}c_Q++;}c_S.push('</tr>');}c_S.push('</table>');c_i.setNodeInnerHtml('grid',c_S.join(''));function c_Y(c_Q){c_i.wireNode('day'+c_Q,'click',function(){c_i.set({c_x:new Date(c_o,c_l,c_Q)})});}for(var c_Q=c_K+1;--c_Q>0;)c_Y(c_Q);}}else{c_i.c_P=c_d;}};c_s.updateUi=function(){this.c_F();this.c_G();
this.c_H();};function c_Z(c_x){return c_e.Formatter.parse(c_x,this.c_0)||null;}c_h.registerProperties({c_0:'displayFormat',c_w:{name:'maxValue',conformer:c_Z,onChange:[c_t,c_H,c_r]},c_v:{name:'minValue',conformer:c_Z,onChange:[c_t,c_H,c_r]},c_l:{name:'month',conformer:function(c_x){var c_1=Math.floor(c_x/12);c_1&&this.set({c_o:this.c_o+c_1});return((c_x%12)+12)%12;},onChange:[c_s.c_F,c_H,c_r]},c_2:{name:'snapViewOnValueChange',value:c_b},c_x:{name:'value',conformer:c_Z,value:new Date,onChange:[function(){this.c_2&&this.c_t()},c_H,c_r]},c_o:{name:'year',onChange:[c_s.c_G,c_H,c_r]}});return c_h;}});


Uize.module({name:'Uize.Templates.Calendar',builder:function(){var _a=function(){};_a.process=function(input){var output=[];
output.push('<div class="calendarContainer">\r\n	<div id="',input.idPrefix,'-controls" class="calendarControls">\r\n		<div id="',input.idPrefix,'-indicator" class="calendarIndicator">\r\n			<span id="',input.idPrefix,'-month" class="monthIndicator">Month</span>\r\n			<span id="',input.idPrefix,'-year" class="yearIndicator">Year</span>\r\n		</div>\r\n		<a href="javascript://" id="',input.idPrefix,'_previousMonth" class="calendarControl previousMonth" title="previous month">&#9668;</a>\r\n		<a href="javascript://" id="',input.idPrefix,'_nextMonth" class="calendarControl nextMonth" title="next month">&#9658;</a>\r\n		<a href="javascript://" id="',input.idPrefix,'_previousYear" class="calendarControl previousYear" title="previous year">&laquo;</a>\r\n		<a href="javascript://" id="',input.idPrefix,'_nextYear" class="calendarControl nextYear" title="next year">&raquo;</a>\r\n	</div>\r\n	<div id="',input.idPrefix,'-grid" class="calendarGrid"></div>\r\n</div>\r\n');return output.join('');};_a.input={idPrefix:'string'
};return _a;}});


Uize.module({name:'UizeDotCom.WidgetToGoPage.Calendar'});

Uize.module ({name:'UizeDotCom.WidgetToGoPage.Calendar.library'});

