/*
	UIZE Web Site 2011-10-31

	http://www.uize.com/reference/UizeDotCom.Page.html
	Available under MIT License or GNU General Public License -- http://www.uize.com/license.html
*/
Uize.module({name:'UizeDotCom.Page',superclass:'Uize.Widget.Page',required:['Uize.Node.VirtualEvent','UizeDotCom.SiteMap','Uize.Widget.Tree.Menu','Uize.Url','Uize.Fx','Uize.Curve','Uize.Curve.Rubber','UizeDotCom.Templates.ShareThisPanel','UizeDotCom.Templates.Footer'],builder:function(d_a){var d_b=d_a.subclass(),d_c=d_b.prototype;d_c.getPathToRoot=function(){var d_d=this.getNode('homeLink').getAttribute('href');return d_d.slice(0,d_d.search(/[\w\-]+.html/));};d_c.performSearch=function(d_e,d_f){location.href=Uize.Url.resolve('http://www.google.com/search',{hl:'en',safe:'off',domains:d_f='uize.com'+(d_f||''),sitesearch:d_f,q:d_e});};d_c.viewSource=function(d_g,d_h){var d_i=this.launchPopup({name:'viewSource',width:1000,height:740});Uize.module({required:'Uize.Comm.Ajax',builder:function(){var d_j=new Uize.Comm.Ajax;d_j.request({url:d_g,requestMethod:'GET',returnType:'text',callback:function(d_k){var d_l=d_i.document;d_l.open('text/html');
d_l.writeln('<html><head><title>'+d_h+'</title></head><body style="padding:0; margin:0;"><div style="font-family:Arial; color:#fff; font-weight:bold; background:#000; border-bottom:5px solid #ccc; text-align:center;">'+d_h+'</div><pre style="padding:8px;">'+d_k.replace(/</g,'&lt;').replace(/\t/g,'   ')+'</pre></body></html>');d_l.close();}});}});};d_c.wireUi=function(){var d_m=this;if(!d_m.isWired){function d_n(){d_m.unwireNode('homeLink','mouseover',d_n);var d_o=[{title:'',link:'index.html',items:UizeDotCom.SiteMap()}],d_p=page.addChild('siteMenu',Uize.Widget.Tree.Menu,{items:d_o,menuCssClass:'siteMenuShell',menuDividerClass:'divider',menuItemActiveCssClass:'siteMenuItemActive',menuItemChildrenIndicatorCssClass:'siteMenuItemWithChildren',menuItemCssClass:'siteMenuItem',subMenuCssClass:'subMenuShell',subMenuDividerClass:'divider',subMenuItemActiveCssClass:'subMenuItemActive',subMenuItemChildrenIndicatorCssClass:'subMenuItemWithChildren',subMenuItemCssClass:'subMenuItem',built:false});
var d_q=d_m.getPathToRoot();d_p.traverseTree({itemHandler:function(d_r){if(d_r.link!=null)d_r.link=d_q+d_r.link;}});var d_s=d_o[0].items;var d_t=d_m.d_u&&d_m.d_u[0];d_t&&d_s.unshift({title:'ON THIS PAGE...',link:'',items:d_t.items},{title:'-'});d_s.push({title:'-'},{title:'WINDOW SIZE',items:[{title:'1024 x 768',link:'javascript:moveTo ((screen.width - 1024) >> 1,0); resizeTo (1024,768)'},{title:'1024 x MAX HEIGHT',link:'javascript:moveTo ((screen.width - 1024) >> 1,0); resizeTo (1024,screen.height)'}]});d_m.injectNodeHtml(d_m.getNode('homeLink').parentNode,'<div id="page_siteMenu-shell" class="siteMenuIcon"></div>');d_p.insertOrWireUi();d_p.setExpandedDepth(1);}d_m.wireNode('homeLink','mouseover',d_n);if(d_m.d_v){function d_w(d_x){var d_y=Uize.Node.find({tagName:'meta',self:function(){return this.name==d_x}})[0];return d_y?d_y.content:'';}Uize.Node.injectHtml(document.body,UizeDotCom.Templates.ShareThisPanel.process({title:document.title.match(/^\s*(.*?)\s*(\||$)/)[1],url:location.href,
keywords:d_w('keywords'),description:d_w('description')}));d_m.wireNode('shareThisPanel',{mouseover:function(){Uize.Fx.fadeStyle(this,null,{opacity:1},300)},'mouserest(250)':function(){Uize.Fx.fadeStyle(this,null,{left:1},600,{curve:Uize.Curve.easeInOutPow(5)})},mouseout:function(){Uize.Fx.fadeStyle(this,null,{opacity:.2},300).wire('Done',function(){Uize.Fx.fadeStyle(d_m.getNode('shareThisPanel'),null,{left:-112},1200,{curve:Uize.Curve.Rubber.easeOutBounce(4,1.5)})});}});Uize.Fx.fadeStyle(d_m.getNode('shareThisPanel'),null,{opacity:.2},1000);}d_m.d_z&&Uize.Node.injectHtml(document.body,UizeDotCom.Templates.Footer.process());d_a.prototype.wireUi.call(d_m);}};d_b.registerProperties({d_u:'contentsTreeItems',d_z:{name:'showFooter',value:true},d_v:{name:'showShareThisPanel',value:true}});d_b.set({confirmDialog:{widgetClassName:'UizeDotCom.DialogConfirm'}});return d_b;}});